/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -O3 -fno-strict-aliasing  -I/root/.choosenim/toolchains/nim-0.18.0/lib -o /mnt/d/Development/bitbucket/java/NetScoutMerger/script/lsrreport/nimcache/checklsrsrc.o /mnt/d/Development/bitbucket/java/NetScoutMerger/script/lsrreport/nimcache/checklsrsrc.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <stdlib.h>
#include <string.h>
#include <dirent.h>
#include <setjmp.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <time.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tySequence_sM4lkSb7zS6F7OVMvW9cffQ tySequence_sM4lkSb7zS6F7OVMvW9cffQ;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack_7fytPA5bBsob6See21YMRA tyObject_GcStack_7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyTuple_ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct tySequence_uB9b75OUPRENsBAu4AnoePA tySequence_uB9b75OUPRENsBAu4AnoePA;
typedef struct TSafePoint TSafePoint;
typedef struct tyObject_SmtpBasecolonObjectType__VksVmFFn8e3v70S4inPcCw tyObject_SmtpBasecolonObjectType__VksVmFFn8e3v70S4inPcCw;
typedef struct tyObject_PSSLContextcolonObjectType__2kCLMA7OHPpiY4mJ42cb7A tyObject_PSSLContextcolonObjectType__2kCLMA7OHPpiY4mJ42cb7A;
typedef struct tyObject_Message_HL5IGwP2RHTpwc47L5s7MQ tyObject_Message_HL5IGwP2RHTpwc47L5s7MQ;
typedef struct tyObject_StringTableObj_DKRIdH9c9cKI7YpQb9c0wKlEw tyObject_StringTableObj_DKRIdH9c9cKI7YpQb9c0wKlEw;
typedef struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w;
typedef struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ;
typedef struct tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA;
typedef struct tyObject_SocketImpl_aIhANOOoETolVz9cccNO9cRQ tyObject_SocketImpl_aIhANOOoETolVz9cccNO9cRQ;
typedef struct tySequence_4eQHGndY6XBYpFOH09apV8Q tySequence_4eQHGndY6XBYpFOH09apV8Q;
typedef struct tyTuple_UV3llMMYFckfui8YMBuUZA tyTuple_UV3llMMYFckfui8YMBuUZA;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef N_NIMCALL_PTR(void, tyProc_T4eqaYlFJYZUv9aG9b1TV0bQ) (void);
struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack_7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* tyArray_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef NU32 tyArray_BHbOSqU1t9b3Gt7K2c6fQig[24];
typedef tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* tyArray_N1u1nqOgmuJN9cSZrnMHgOQ[32];
typedef tyArray_N1u1nqOgmuJN9cSZrnMHgOQ tyArray_B6durA4ZCi1xjJvRtyYxMg[24];
typedef tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* tyArray_lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA {
tyArray_lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* tyArray_0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw {
tyArray_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyArray_LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray_LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray_SiRwrEKZdLgxqz9a9aoVBglg freeSmallChunks;
NU32 flBitmap;
tyArray_BHbOSqU1t9b3Gt7K2c6fQig slBitmap;
tyArray_B6durA4ZCi1xjJvRtyYxMg matrix;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI occ;
NI lastSize;
tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack_7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w additionalRoots;
NI gcThreadId;
};
typedef NimStringDesc* tyArray_nHXaesL0DJZHyVS07ARPRA[1];
typedef NU8 tyEnum_PathComponent_9c1SIU9cO1wHcl09b703A9cDrg;
typedef NU8 tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef NU8 tyEnum_WalkOp_Wfy7gT5VQ8B3aJBxqU8D9cQ;
struct RootObj {
TNimType* m_type;
};
struct Exception {
  RootObj Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
tySequence_uB9b75OUPRENsBAu4AnoePA* trace;
Exception* up;
};
typedef long tyArray_TcvIiMAJvcwzNLsZkfnFnQ[25];
typedef struct {
N_NIMCALL_PTR(NIM_BOOL, ClP_0) (Exception* e, void* ClE_0);
void* ClE_0;
} tyProc_KeeAOYBd84Ofsw6Y7LizaQ;
struct TSafePoint {
TSafePoint* prev;
NI status;
jmp_buf context;
NIM_BOOL hasRaiseAction;
tyProc_KeeAOYBd84Ofsw6Y7LizaQ raiseAction;
};
typedef char tyArray_XKk9bNZbVEtY3RuROG9aRBgw[256];
typedef long tyArray_QS4edQct6fXoghbs69aZ9a8w[3];
struct tyObject_Message_HL5IGwP2RHTpwc47L5s7MQ {
tySequence_sM4lkSb7zS6F7OVMvW9cffQ* msgTo;
tySequence_sM4lkSb7zS6F7OVMvW9cffQ* msgCc;
NimStringDesc* msgSubject;
tyObject_StringTableObj_DKRIdH9c9cKI7YpQb9c0wKlEw* msgOtherHeaders;
NimStringDesc* msgBody;
};
struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w {
NI prevSize;
NI size;
};
struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* next;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* prev;
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* freeList;
NI free;
NI acc;
NF data;
};
struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* next;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* prev;
NF data;
};
struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw {
NI size;
NI acc;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* next;
};
typedef NI tyArray_9a8QARi5WsUggNU9bom7kzTQ[8];
struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw {
tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg {
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA {
NCSTRING procname;
NI line;
NCSTRING filename;
};
struct tyObject_SmtpBasecolonObjectType__VksVmFFn8e3v70S4inPcCw {
tyObject_SocketImpl_aIhANOOoETolVz9cccNO9cRQ* sock;
NIM_BOOL debug;
};
struct tyObject_PSSLContextcolonObjectType__2kCLMA7OHPpiY4mJ42cb7A {
char dummy;
};
typedef NU8 tyEnum_StringTableMode_G9c4wVDFIzf0xHmQvxso9a9cQ;
struct tyObject_StringTableObj_DKRIdH9c9cKI7YpQb9c0wKlEw {
  RootObj Sup;
NI counter;
tySequence_4eQHGndY6XBYpFOH09apV8Q* data;
tyEnum_StringTableMode_G9c4wVDFIzf0xHmQvxso9a9cQ mode;
};
struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ {
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* next;
NI zeroField;
};
typedef NIM_CHAR tyArray_QQGLPNVVwLhYjkngqAxXQQ[4001];
typedef NU8 tyEnum_Domain_Q79bEtFARvq0ekDNtvj3Vqg;
typedef NU8 tyEnum_SockType_NQT1bItGG2X9byGdrWX7ujw;
typedef NU8 tyEnum_Protocol_dqJ1OqRGclxIMMdSLRzzXg;
struct tyObject_SocketImpl_aIhANOOoETolVz9cccNO9cRQ {
int fd;
NIM_BOOL isBuffered;
union{
struct {tyArray_QQGLPNVVwLhYjkngqAxXQQ buffer;
NI currPos;
NI bufLen;
} S1;
} isBufferedU;
NI32 lastError;
tyEnum_Domain_Q79bEtFARvq0ekDNtvj3Vqg domain;
tyEnum_SockType_NQT1bItGG2X9byGdrWX7ujw sockType;
tyEnum_Protocol_dqJ1OqRGclxIMMdSLRzzXg protocol;
};
struct tyTuple_UV3llMMYFckfui8YMBuUZA {
NimStringDesc* Field0;
NimStringDesc* Field1;
};
struct tySequence_sM4lkSb7zS6F7OVMvW9cffQ {
  TGenericSeq Sup;
  NimStringDesc* data[SEQ_DECL_SIZE];
};
struct tySequence_uB9b75OUPRENsBAu4AnoePA {
  TGenericSeq Sup;
  tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA data[SEQ_DECL_SIZE];
};
struct tySequence_4eQHGndY6XBYpFOH09apV8Q {
  TGenericSeq Sup;
  tyTuple_UV3llMMYFckfui8YMBuUZA data[SEQ_DECL_SIZE];
};
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, TM_PFN0uFlSYZ7oiENL9cCUs8A_2)(void);
N_NIMCALL(void, nimRegisterGlobalMarker)(tyProc_T4eqaYlFJYZUv9aG9b1TV0bQ markerProc);
N_LIB_PRIVATE N_NIMCALL(tySequence_sM4lkSb7zS6F7OVMvW9cffQ*, commandLineParams_WoBZMy8AVRATRE9bQuYWzCQ)(void);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr);
static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NOINLINE(void, addZCT_fCDI7oO1NNVXXURtxSzsRw)(tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_NIMCALL(void, echoBinSafe)(NimStringDesc** args, NI argsLen_0);
static N_NIMCALL(void, TM_PFN0uFlSYZ7oiENL9cCUs8A_5)(void);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
N_LIB_PRIVATE N_NIMCALL(NI, nsuParseInt)(NimStringDesc* s);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, checkDirUpdateIn_Tnszk9b6W8ZX89aAxiala2PA)(NimStringDesc* dir, NI minutes);
N_LIB_PRIVATE N_NIMCALL(NI64, getTime_wqmoaGqnr3gMTpWruGQ3FA)(void);
N_NIMCALL(void*, newSeq)(TNimType* typ, NI len);
static N_INLINE(NimStringDesc*, pop_9cDsfK2acP02vJ9bhxIE9caEAchecklsrsrc)(tySequence_sM4lkSb7zS6F7OVMvW9cffQ** s);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
static N_INLINE(TGenericSeq*, setLengthSeq)(TGenericSeq* seq, NI elemSize, NI newLen);
static N_INLINE(NI, resize_bzF9a0JivP3Z4njqaxuLc5wsystem)(NI old);
N_LIB_PRIVATE N_NIMCALL(void*, growObj_AVYny8c0GTk28gxjmat1MA)(void* old, NI newsize);
N_NIMCALL(TNimType*, extGetCellType)(void* c);
N_LIB_PRIVATE N_NIMCALL(void, forAllChildrenAux_YOI1Uo54H9aas13WthjhsfA)(void* dest, TNimType* mt, tyEnum_WalkOp_Wfy7gT5VQ8B3aJBxqU8D9cQ op);
static N_INLINE(void, zeroMem_t0o5XqKanO5QJfXMGEzp2Asystem)(void* p, NI size);
static N_INLINE(void, pushSafePoint)(TSafePoint* s);
N_NIMCALL(NimStringDesc*, cstrToNimstr)(NCSTRING str);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b);
static N_INLINE(NIM_BOOL, equalMem_fmeFeLBvgmAHG9bC8ETS9bYQchecklsrsrc)(void* a, void* b, NI size);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, slash__lXoMhn1ZYc9cAJa9bfA61msg)(NimStringDesc* head, NimStringDesc* tail);
static N_INLINE(NIM_BOOL, dirExists_wf0Ae3eLXw0lSNEFJMV3ogchecklsrsrc)(NimStringDesc* dir);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, nosexistsDir)(NimStringDesc* dir);
N_NIMCALL(TGenericSeq*, incrSeqV2)(TGenericSeq* seq, NI elemSize);
N_LIB_PRIVATE N_NIMCALL(NI64, nosgetLastModificationTime)(NimStringDesc* file);
N_LIB_PRIVATE N_NIMCALL(NI64, toUnix_KOVzgXVRJxxlPUOsrk3eDQ)(NI64 t);
static N_INLINE(void, popSafePoint)(void);
N_LIB_PRIVATE N_NIMCALL(tyEnum_PathComponent_9c1SIU9cO1wHcl09b703A9cDrg, getSymlinkFileKind_WoXOp8qmMec1P4MyA3LBKg)(NimStringDesc* path);
N_NIMCALL(void, reraiseException)(void);
N_LIB_PRIVATE N_NIMCALL(void, sendmail_rZNS5KpVF9aFxMFONtIxYYA)(void);
N_LIB_PRIVATE N_NIMCALL(tyObject_SmtpBasecolonObjectType__VksVmFFn8e3v70S4inPcCw*, newSmtp_Nfj9aqPFVmOAIhqu0AdSnwQ)(NIM_BOOL useSsl, NIM_BOOL debug, tyObject_PSSLContextcolonObjectType__2kCLMA7OHPpiY4mJ42cb7A* sslContext);
N_LIB_PRIVATE N_NIMCALL(void, connect_C7JzaUeEk1v89aIrEUFE6Kw)(tyObject_SmtpBasecolonObjectType__VksVmFFn8e3v70S4inPcCw* smtp, NimStringDesc* address, NU16 port);
N_NIMCALL(void, genericSeqAssign)(void* dest, void* src, TNimType* mt);
N_LIB_PRIVATE N_NIMCALL(void, createMessage_VTgoPMl3ny6cuyc4q9c3iFg)(NimStringDesc* mSubject, NimStringDesc* mBody, tySequence_sM4lkSb7zS6F7OVMvW9cffQ* mTo, tySequence_sM4lkSb7zS6F7OVMvW9cffQ* mCc, tyObject_Message_HL5IGwP2RHTpwc47L5s7MQ* Result);
N_LIB_PRIVATE N_NIMCALL(void, sendMail_quVl9cZasl6ARt2XgBDMBeg)(tyObject_SmtpBasecolonObjectType__VksVmFFn8e3v70S4inPcCw* smtp, NimStringDesc* fromAddr, tySequence_sM4lkSb7zS6F7OVMvW9cffQ* toAddrs, NimStringDesc* msg);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar__QWOX43qXQs7iDJ7vgNvGzQ)(tyObject_Message_HL5IGwP2RHTpwc47L5s7MQ* msg);
N_LIB_PRIVATE N_NIMCALL(void, close_uZ9cBaasaypmmMJ58nGYPOw)(tyObject_SmtpBasecolonObjectType__VksVmFFn8e3v70S4inPcCw* smtp);
static N_INLINE(void, initStackBottomWith)(void* locals);
N_NOINLINE(void, setStackBottom)(void* theStackBottom);
NIM_EXTERNC N_NOINLINE(void, systemInit000)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_posixInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_posixDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_timesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_timesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_ospathsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_ospathsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_osInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_osDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_pcreInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_pcreDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_rtarraysInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_rtarraysDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_reInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_reDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_typetraitsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_typetraitsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_optionsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_optionsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_nativesocketsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_nativesocketsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_hashesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_hashesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_setsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_setsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_netInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_netDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strtabsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strtabsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_base64Init000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_base64DatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_tablesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_tablesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_heapqueueInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_heapqueueDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_listsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_listsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_dequesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_dequesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_cstrutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_cstrutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_asyncfuturesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_asyncfuturesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_asyncstreamsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_asyncstreamsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_epollInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_epollDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_selectorsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_selectorsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_macrosInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_macrosDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_asyncdispatchInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_asyncdispatchDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_asyncnetInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_asyncnetDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_smtpInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_smtpDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void);
NIM_EXTERNC N_NOINLINE(void, checklsrsrcDatInit000)(void);
tySequence_sM4lkSb7zS6F7OVMvW9cffQ* args_xNHvKA9bT79a4bvfmeuKePYg;
extern TNimType NTI_sM4lkSb7zS6F7OVMvW9cffQ_;
extern tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
NimStringDesc* dir_gcU9cI3tJjB63nS1HEJzj2g;
extern TNimType NTI_77mFvmsOLKik79ci2hXkHEg_;
NI minutes_gP8i3Vz6vFrJwUO9bE9arwkA;
extern TSafePoint* excHandler_rqLlY5bs9atDw2OXYqJEn5g;
extern tyObject_PSSLContextcolonObjectType__2kCLMA7OHPpiY4mJ42cb7A* defaultSSLContext_dzzxzfEmWpfrZMRfTcMRBQ;
STRING_LITERAL(TM_PFN0uFlSYZ7oiENL9cCUs8A_4, "usage: checklsrsrc path minutes", 31);
NIM_CONST tyArray_nHXaesL0DJZHyVS07ARPRA TM_PFN0uFlSYZ7oiENL9cCUs8A_3 = {((NimStringDesc*) &TM_PFN0uFlSYZ7oiENL9cCUs8A_4)}
;
STRING_LITERAL(TM_PFN0uFlSYZ7oiENL9cCUs8A_7, ".", 1);
STRING_LITERAL(TM_PFN0uFlSYZ7oiENL9cCUs8A_8, "..", 2);
STRING_LITERAL(TM_PFN0uFlSYZ7oiENL9cCUs8A_10, "Got new source files", 20);
NIM_CONST tyArray_nHXaesL0DJZHyVS07ARPRA TM_PFN0uFlSYZ7oiENL9cCUs8A_9 = {((NimStringDesc*) &TM_PFN0uFlSYZ7oiENL9cCUs8A_10)}
;
STRING_LITERAL(TM_PFN0uFlSYZ7oiENL9cCUs8A_12, "No new file, send warning mail.", 31);
NIM_CONST tyArray_nHXaesL0DJZHyVS07ARPRA TM_PFN0uFlSYZ7oiENL9cCUs8A_11 = {((NimStringDesc*) &TM_PFN0uFlSYZ7oiENL9cCUs8A_12)}
;
STRING_LITERAL(TM_PFN0uFlSYZ7oiENL9cCUs8A_13, "192.168.99.147", 14);
STRING_LITERAL(TM_PFN0uFlSYZ7oiENL9cCUs8A_14, "noc-pmats@aptg.com.tw", 21);
STRING_LITERAL(TM_PFN0uFlSYZ7oiENL9cCUs8A_16, "maxhuang@aptg.com.tw", 20);
NIM_CONST struct {
  TGenericSeq Sup;
  NimStringDesc* data[1];
} TM_PFN0uFlSYZ7oiENL9cCUs8A_17 = {{1, 1}, {((NimStringDesc*) &TM_PFN0uFlSYZ7oiENL9cCUs8A_16)}};
NIM_CONST tySequence_sM4lkSb7zS6F7OVMvW9cffQ* TM_PFN0uFlSYZ7oiENL9cCUs8A_15 = ((tySequence_sM4lkSb7zS6F7OVMvW9cffQ*)&TM_PFN0uFlSYZ7oiENL9cCUs8A_17);
STRING_LITERAL(TM_PFN0uFlSYZ7oiENL9cCUs8A_18, "IMSI Mapping: LSR Source Disconnected Warning", 45);
STRING_LITERAL(TM_PFN0uFlSYZ7oiENL9cCUs8A_19, "As title!!!", 11);
static N_NIMCALL(void, TM_PFN0uFlSYZ7oiENL9cCUs8A_2)(void) {
	nimGCvisit((void*)args_xNHvKA9bT79a4bvfmeuKePYg, 0);
}

static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* result;
	result = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	result = ((tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*) ((NI)((NU64)(((NI) (ptrdiff_t) (usr))) - (NU64)(((NI)sizeof(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g))))));
	return result;
}

static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	addZCT_fCDI7oO1NNVXXURtxSzsRw((&gch_IcYaEuuWivYAS86vFMTS3Q.zct), c);
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
		if (!!((src == NIM_NIL))) goto LA3_;
		c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		(*c).refcount += ((NI) 8);
	}
	LA3_: ;
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c_2;
		if (!!(((*dest) == NIM_NIL))) goto LA7_;
		c_2 = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		{
			(*c_2).refcount -= ((NI) 8);
			if (!((NU64)((*c_2).refcount) < (NU64)(((NI) 8)))) goto LA11_;
			rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c_2);
		}
		LA11_: ;
	}
	LA7_: ;
	(*dest) = src;
}
static N_NIMCALL(void, TM_PFN0uFlSYZ7oiENL9cCUs8A_5)(void) {
	nimGCvisit((void*)dir_gcU9cI3tJjB63nS1HEJzj2g, 0);
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
	c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(p);
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
}

static N_INLINE(NI, resize_bzF9a0JivP3Z4njqaxuLc5wsystem)(NI old) {
	NI result;
	result = (NI)0;
	{
		if (!(old <= ((NI) 0))) goto LA3_;
		result = ((NI) 4);
	}
	goto LA1_;
	LA3_: ;
	{
		if (!(old < ((NI) 65536))) goto LA6_;
		result = (NI)(old * ((NI) 2));
	}
	goto LA1_;
	LA6_: ;
	{
		result = (NI)((NI)(old * ((NI) 3)) / ((NI) 2));
	}
	LA1_: ;
	return result;
}

static N_INLINE(void, zeroMem_t0o5XqKanO5QJfXMGEzp2Asystem)(void* p, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(p, ((int) 0), ((size_t) (size)));
}

static N_INLINE(TGenericSeq*, setLengthSeq)(TGenericSeq* seq, NI elemSize, NI newLen) {
	TGenericSeq* result;
	result = (TGenericSeq*)0;
	result = seq;
	{
		NI r;
		NI T5_;
		void* T6_;
		if (!((NI)((*result).reserved & ((NI) IL64(4611686018427387903))) < newLen)) goto LA3_;
		T5_ = (NI)0;
		T5_ = resize_bzF9a0JivP3Z4njqaxuLc5wsystem((NI)((*result).reserved & ((NI) IL64(4611686018427387903))));
		r = ((T5_ >= newLen) ? T5_ : newLen);
		T6_ = (void*)0;
		T6_ = growObj_AVYny8c0GTk28gxjmat1MA(((void*) (result)), (NI)((NI)(elemSize * r) + ((NI) 16)));
		result = ((TGenericSeq*) (T6_));
		(*result).reserved = r;
	}
	goto LA1_;
	LA3_: ;
	{
		if (!(newLen < (*result).len)) goto LA8_;
		{
			TNimType* T12_;
			T12_ = (TNimType*)0;
			T12_ = extGetCellType(((void*) (result)));
			if (!!((((*(*T12_).base).flags &(1U<<((NU)(((tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ) 0))&7U)))!=0))) goto LA13_;
			{
				NI i;
				NI colontmp_;
				NI res;
				i = (NI)0;
				colontmp_ = (NI)0;
				colontmp_ = (NI)((*result).len - ((NI) 1));
				res = newLen;
				{
					while (1) {
						TNimType* T18_;
						if (!(res <= colontmp_)) goto LA17;
						i = res;
						T18_ = (TNimType*)0;
						T18_ = extGetCellType(((void*) (result)));
						forAllChildrenAux_YOI1Uo54H9aas13WthjhsfA(((void*) ((NI)((NU64)((NI)((NU64)(((NI) (ptrdiff_t) (result))) + (NU64)(((NI) 16)))) + (NU64)((NI)((NU64)(i) * (NU64)(elemSize)))))), (*T18_).base, ((tyEnum_WalkOp_Wfy7gT5VQ8B3aJBxqU8D9cQ) 2));
						res += ((NI) 1);
					} LA17: ;
				}
			}
		}
		LA13_: ;
		zeroMem_t0o5XqKanO5QJfXMGEzp2Asystem(((void*) ((NI)((NU64)((NI)((NU64)(((NI) (ptrdiff_t) (result))) + (NU64)(((NI) 16)))) + (NU64)((NI)((NU64)(newLen) * (NU64)(elemSize)))))), ((NI) ((NI)((NU64)((NI)((NU64)((*result).len) - (NU64)(newLen))) * (NU64)(elemSize)))));
	}
	goto LA1_;
	LA8_: ;
	LA1_: ;
	(*result).len = newLen;
	return result;
}

static N_INLINE(NimStringDesc*, pop_9cDsfK2acP02vJ9bhxIE9caEAchecklsrsrc)(tySequence_sM4lkSb7zS6F7OVMvW9cffQ** s) {
	NimStringDesc* result;
	NI L;
	NI T1_;
	result = (NimStringDesc*)0;
	T1_ = ((*s) ? (*s)->Sup.len : 0);
	L = (NI)(T1_ - ((NI) 1));
	result = copyString((*s)->data[L]);
	(*s) = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*) setLengthSeq(&((*s))->Sup, sizeof(NimStringDesc*), ((NI) (L)));
	return result;
}

static N_INLINE(void, pushSafePoint)(TSafePoint* s) {
	(*s).hasRaiseAction = NIM_FALSE;
	(*s).prev = excHandler_rqLlY5bs9atDw2OXYqJEn5g;
	excHandler_rqLlY5bs9atDw2OXYqJEn5g = s;
}

static N_INLINE(NIM_BOOL, equalMem_fmeFeLBvgmAHG9bC8ETS9bYQchecklsrsrc)(void* a, void* b, NI size) {
	NIM_BOOL result;
	int T1_;
	result = (NIM_BOOL)0;
	T1_ = (int)0;
	T1_ = memcmp(a, b, ((size_t) (size)));
	result = (T1_ == ((NI32) 0));
	return result;
}

static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b) {
	NIM_BOOL result;
	NIM_BOOL T11_;
{	result = (NIM_BOOL)0;
	{
		if (!(a == b)) goto LA3_;
		result = NIM_TRUE;
		goto BeforeRet_;
	}
	LA3_: ;
	{
		NIM_BOOL T7_;
		T7_ = (NIM_BOOL)0;
		T7_ = (a == NIM_NIL);
		if (T7_) goto LA8_;
		T7_ = (b == NIM_NIL);
		LA8_: ;
		if (!T7_) goto LA9_;
		result = NIM_FALSE;
		goto BeforeRet_;
	}
	LA9_: ;
	T11_ = (NIM_BOOL)0;
	T11_ = ((*a).Sup.len == (*b).Sup.len);
	if (!(T11_)) goto LA12_;
	T11_ = equalMem_fmeFeLBvgmAHG9bC8ETS9bYQchecklsrsrc(((void*) ((*a).data)), ((void*) ((*b).data)), ((NI) ((*a).Sup.len)));
	LA12_: ;
	result = T11_;
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NIM_BOOL, dirExists_wf0Ae3eLXw0lSNEFJMV3ogchecklsrsrc)(NimStringDesc* dir) {
	NIM_BOOL result;
	result = (NIM_BOOL)0;
	result = nosexistsDir(dir);
	return result;
}

static N_INLINE(void, popSafePoint)(void) {
	excHandler_rqLlY5bs9atDw2OXYqJEn5g = (*excHandler_rqLlY5bs9atDw2OXYqJEn5g).prev;
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, checkDirUpdateIn_Tnszk9b6W8ZX89aAxiala2PA)(NimStringDesc* dir, NI minutes) {
	NIM_BOOL volatile result;
	NI64 n;
{	result = (NIM_BOOL)0;
	n = getTime_wqmoaGqnr3gMTpWruGQ3FA();
	{
		NimStringDesc* file;
		tySequence_sM4lkSb7zS6F7OVMvW9cffQ* volatile stack;
		NimStringDesc* T2_;
		file = (NimStringDesc*)0;
		stack = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*) newSeq((&NTI_sM4lkSb7zS6F7OVMvW9cffQ_), 1);
		T2_ = (NimStringDesc*)0;
		T2_ = stack->data[0]; stack->data[0] = copyStringRC1(dir);
		if (T2_) nimGCunrefNoCycle(T2_);
		{
			while (1) {
				NI T5_;
				T5_ = (stack ? stack->Sup.len : 0);
				if (!(((NI) 0) < T5_)) goto LA4;
				{
					tyEnum_PathComponent_9c1SIU9cO1wHcl09b703A9cDrg k;
					NimStringDesc* p;
					NimStringDesc* colontmp_;
					DIR* d;
					k = (tyEnum_PathComponent_9c1SIU9cO1wHcl09b703A9cDrg)0;
					p = (NimStringDesc*)0;
					colontmp_ = (NimStringDesc*)0;
					colontmp_ = pop_9cDsfK2acP02vJ9bhxIE9caEAchecklsrsrc((&stack));
					d = opendir(colontmp_->data);
					{
						TSafePoint TM_PFN0uFlSYZ7oiENL9cCUs8A_6;
						if (!!((d == NIM_NIL))) goto LA9_;
						pushSafePoint(&TM_PFN0uFlSYZ7oiENL9cCUs8A_6);
						TM_PFN0uFlSYZ7oiENL9cCUs8A_6.status = setjmp(TM_PFN0uFlSYZ7oiENL9cCUs8A_6.context);
						if (TM_PFN0uFlSYZ7oiENL9cCUs8A_6.status == 0) {
							{
								while (1) {
									{
										struct dirent* x;
										NimStringDesc* volatile y;
										x = readdir(d);
										{
											if (!(x == NIM_NIL)) goto LA17_;
											goto LA12;
										}
										LA17_: ;
										y = cstrToNimstr(((NCSTRING) ((*x).d_name)));
										{
											NIM_BOOL T21_;
											struct stat s;
											tyEnum_PathComponent_9c1SIU9cO1wHcl09b703A9cDrg volatile k_2;
											T21_ = (NIM_BOOL)0;
											T21_ = !(eqStrings(y, ((NimStringDesc*) &TM_PFN0uFlSYZ7oiENL9cCUs8A_7)));
											if (!(T21_)) goto LA22_;
											T21_ = !(eqStrings(y, ((NimStringDesc*) &TM_PFN0uFlSYZ7oiENL9cCUs8A_8)));
											LA22_: ;
											if (!T21_) goto LA23_;
											memset((void*)(&s), 0, sizeof(s));
											{
												if (!NIM_TRUE) goto LA27_;
												y = slash__lXoMhn1ZYc9cAJa9bfA61msg(colontmp_, y);
											}
											LA27_: ;
											k_2 = ((tyEnum_PathComponent_9c1SIU9cO1wHcl09b703A9cDrg) 0);
											{
												if (!!(((*x).d_type == ((NI8) 0)))) goto LA31_;
												{
													if (!((*x).d_type == ((NI8) 4))) goto LA35_;
													k_2 = ((tyEnum_PathComponent_9c1SIU9cO1wHcl09b703A9cDrg) 2);
												}
												LA35_: ;
												{
													if (!((*x).d_type == ((NI8) 10))) goto LA39_;
													{
														NIM_BOOL T43_;
														T43_ = (NIM_BOOL)0;
														T43_ = dirExists_wf0Ae3eLXw0lSNEFJMV3ogchecklsrsrc(y);
														if (!T43_) goto LA44_;
														k_2 = ((tyEnum_PathComponent_9c1SIU9cO1wHcl09b703A9cDrg) 3);
													}
													goto LA41_;
													LA44_: ;
													{
														k_2 = ((tyEnum_PathComponent_9c1SIU9cO1wHcl09b703A9cDrg) 1);
													}
													LA41_: ;
												}
												LA39_: ;
												k = k_2;
												p = y;
												{
													NIM_BOOL T49_;
													NI T53_;
													NimStringDesc* T54_;
													T49_ = (NIM_BOOL)0;
													T49_ = ((12 &(1U<<((NU)(k)&7U)))!=0);
													if (!(T49_)) goto LA50_;
													T49_ = ((4 &(1U<<((NU)(k)&7U)))!=0);
													LA50_: ;
													if (!T49_) goto LA51_;
													stack = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*) incrSeqV2(&(stack)->Sup, sizeof(NimStringDesc*));
													T53_ = stack->Sup.len++;
													T54_ = (NimStringDesc*)0;
													T54_ = stack->data[T53_]; stack->data[T53_] = copyStringRC1(p);
													if (T54_) nimGCunrefNoCycle(T54_);
												}
												LA51_: ;
												{
													NI64 ft;
													NI64 diffminutes;
													NI64 T59_;
													NI64 T60_;
													if (!((1 &(1U<<((NU)(k)&7U)))!=0)) goto LA57_;
													file = p;
													ft = nosgetLastModificationTime(file);
													T59_ = (NI64)0;
													T59_ = toUnix_KOVzgXVRJxxlPUOsrk3eDQ(n);
													T60_ = (NI64)0;
													T60_ = toUnix_KOVzgXVRJxxlPUOsrk3eDQ(ft);
													diffminutes = (NI64)((NI64)(T59_ - T60_) / IL64(60));
													{
														int T65_;
														if (!(diffminutes <= ((NI64) (minutes)))) goto LA63_;
														result = NIM_TRUE;
														popSafePoint();
														T65_ = (int)0;
														T65_ = closedir(d);
														T65_;
														goto BeforeRet_;
													}
													LA63_: ;
												}
												LA57_: ;
												goto LA14;
											}
											LA31_: ;
											{
												int T68_;
												T68_ = (int)0;
												T68_ = lstat(y->data, (&s));
												if (!(T68_ < ((NI32) 0))) goto LA69_;
												goto LA12;
											}
											LA69_: ;
											{
												NIM_BOOL T73_;
												T73_ = (NIM_BOOL)0;
												T73_ = S_ISDIR(s.st_mode);
												if (!T73_) goto LA74_;
												k_2 = ((tyEnum_PathComponent_9c1SIU9cO1wHcl09b703A9cDrg) 2);
											}
											goto LA71_;
											LA74_: ;
											{
												NIM_BOOL T77_;
												T77_ = (NIM_BOOL)0;
												T77_ = S_ISLNK(s.st_mode);
												if (!T77_) goto LA78_;
												k_2 = getSymlinkFileKind_WoXOp8qmMec1P4MyA3LBKg(y);
											}
											goto LA71_;
											LA78_: ;
											LA71_: ;
											k = k_2;
											p = y;
											{
												NIM_BOOL T82_;
												NI T86_;
												NimStringDesc* T87_;
												T82_ = (NIM_BOOL)0;
												T82_ = ((12 &(1U<<((NU)(k)&7U)))!=0);
												if (!(T82_)) goto LA83_;
												T82_ = ((4 &(1U<<((NU)(k)&7U)))!=0);
												LA83_: ;
												if (!T82_) goto LA84_;
												stack = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*) incrSeqV2(&(stack)->Sup, sizeof(NimStringDesc*));
												T86_ = stack->Sup.len++;
												T87_ = (NimStringDesc*)0;
												T87_ = stack->data[T86_]; stack->data[T86_] = copyStringRC1(p);
												if (T87_) nimGCunrefNoCycle(T87_);
											}
											LA84_: ;
											{
												NI64 ft_2;
												NI64 diffminutes_2;
												NI64 T92_;
												NI64 T93_;
												if (!((1 &(1U<<((NU)(k)&7U)))!=0)) goto LA90_;
												file = p;
												ft_2 = nosgetLastModificationTime(file);
												T92_ = (NI64)0;
												T92_ = toUnix_KOVzgXVRJxxlPUOsrk3eDQ(n);
												T93_ = (NI64)0;
												T93_ = toUnix_KOVzgXVRJxxlPUOsrk3eDQ(ft_2);
												diffminutes_2 = (NI64)((NI64)(T92_ - T93_) / IL64(60));
												{
													int T98_;
													if (!(diffminutes_2 <= ((NI64) (minutes)))) goto LA96_;
													result = NIM_TRUE;
													popSafePoint();
													T98_ = (int)0;
													T98_ = closedir(d);
													T98_;
													goto BeforeRet_;
												}
												LA96_: ;
											}
											LA90_: ;
										}
										LA23_: ;
									} LA14: ;
								}
							} LA12: ;
							popSafePoint();
						}
						else {
							popSafePoint();
						}
						{
							int T101_;
							T101_ = (int)0;
							T101_ = closedir(d);
							T101_;
						}
						if (TM_PFN0uFlSYZ7oiENL9cCUs8A_6.status != 0) reraiseException();
					}
					LA9_: ;
				}
			} LA4: ;
		}
	}
	result = NIM_FALSE;
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, sendmail_rZNS5KpVF9aFxMFONtIxYYA)(void) {
	tyObject_SmtpBasecolonObjectType__VksVmFFn8e3v70S4inPcCw* smtpConn;
	NimStringDesc* fromaddr;
	tySequence_sM4lkSb7zS6F7OVMvW9cffQ* toaddrs;
	tyObject_Message_HL5IGwP2RHTpwc47L5s7MQ msg;
	tySequence_sM4lkSb7zS6F7OVMvW9cffQ* T1_;
	NimStringDesc* T2_;
	smtpConn = newSmtp_Nfj9aqPFVmOAIhqu0AdSnwQ(NIM_FALSE, NIM_TRUE, defaultSSLContext_dzzxzfEmWpfrZMRfTcMRBQ);
	connect_C7JzaUeEk1v89aIrEUFE6Kw(smtpConn, ((NimStringDesc*) &TM_PFN0uFlSYZ7oiENL9cCUs8A_13), ((NU16) 25));
	fromaddr = copyString(((NimStringDesc*) &TM_PFN0uFlSYZ7oiENL9cCUs8A_14));
	genericSeqAssign((&toaddrs), TM_PFN0uFlSYZ7oiENL9cCUs8A_15, (&NTI_sM4lkSb7zS6F7OVMvW9cffQ_));
	memset((void*)(&msg), 0, sizeof(msg));
	T1_ = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*)0;
	T1_ = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*) newSeq((&NTI_sM4lkSb7zS6F7OVMvW9cffQ_), 0);
	createMessage_VTgoPMl3ny6cuyc4q9c3iFg(((NimStringDesc*) &TM_PFN0uFlSYZ7oiENL9cCUs8A_18), ((NimStringDesc*) &TM_PFN0uFlSYZ7oiENL9cCUs8A_19), toaddrs, T1_, (&msg));
	T2_ = (NimStringDesc*)0;
	T2_ = dollar__QWOX43qXQs7iDJ7vgNvGzQ((&msg));
	sendMail_quVl9cZasl6ARt2XgBDMBeg(smtpConn, fromaddr, toaddrs, T2_);
	close_uZ9cBaasaypmmMJ58nGYPOw(smtpConn);
}

static N_INLINE(void, initStackBottomWith)(void* locals) {
	setStackBottom(locals);
}
void PreMainInner(void) {
	systemInit000();
	stdlib_parseutilsDatInit000();
	stdlib_mathDatInit000();
	stdlib_algorithmDatInit000();
	stdlib_strutilsDatInit000();
	stdlib_posixDatInit000();
	stdlib_timesDatInit000();
	stdlib_ospathsDatInit000();
	stdlib_osDatInit000();
	stdlib_pcreDatInit000();
	stdlib_rtarraysDatInit000();
	stdlib_reDatInit000();
	stdlib_typetraitsDatInit000();
	stdlib_optionsDatInit000();
	stdlib_nativesocketsDatInit000();
	stdlib_hashesDatInit000();
	stdlib_setsDatInit000();
	stdlib_netDatInit000();
	stdlib_strtabsDatInit000();
	stdlib_base64DatInit000();
	stdlib_tablesDatInit000();
	stdlib_heapqueueDatInit000();
	stdlib_listsDatInit000();
	stdlib_dequesDatInit000();
	stdlib_cstrutilsDatInit000();
	stdlib_asyncfuturesDatInit000();
	stdlib_asyncstreamsDatInit000();
	stdlib_epollDatInit000();
	stdlib_selectorsDatInit000();
	stdlib_macrosDatInit000();
	stdlib_asyncdispatchDatInit000();
	stdlib_asyncnetDatInit000();
	stdlib_smtpDatInit000();
	checklsrsrcDatInit000();
	stdlib_parseutilsInit000();
	stdlib_mathInit000();
	stdlib_algorithmInit000();
	stdlib_strutilsInit000();
	stdlib_posixInit000();
	stdlib_timesInit000();
	stdlib_ospathsInit000();
	stdlib_osInit000();
	stdlib_pcreInit000();
	stdlib_rtarraysInit000();
	stdlib_reInit000();
	stdlib_typetraitsInit000();
	stdlib_optionsInit000();
	stdlib_nativesocketsInit000();
	stdlib_hashesInit000();
	stdlib_setsInit000();
	stdlib_netInit000();
	stdlib_strtabsInit000();
	stdlib_base64Init000();
	stdlib_tablesInit000();
	stdlib_heapqueueInit000();
	stdlib_listsInit000();
	stdlib_dequesInit000();
	stdlib_cstrutilsInit000();
	stdlib_asyncfuturesInit000();
	stdlib_asyncstreamsInit000();
	stdlib_epollInit000();
	stdlib_selectorsInit000();
	stdlib_macrosInit000();
	stdlib_asyncdispatchInit000();
	stdlib_asyncnetInit000();
	stdlib_smtpInit000();
}

void PreMain(void) {
	void (*volatile inner)(void);
	systemDatInit000();
	inner = PreMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	NimMainModule();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)(void);
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void) {
nimRegisterGlobalMarker(TM_PFN0uFlSYZ7oiENL9cCUs8A_2);
nimRegisterGlobalMarker(TM_PFN0uFlSYZ7oiENL9cCUs8A_5);
	{
		NimStringDesc* T10_;
		if (!NIM_TRUE) goto LA3_;
		asgnRefNoCycle((void**) (&args_xNHvKA9bT79a4bvfmeuKePYg), commandLineParams_WoBZMy8AVRATRE9bQuYWzCQ());
		{
			NI T7_;
			T7_ = (args_xNHvKA9bT79a4bvfmeuKePYg ? args_xNHvKA9bT79a4bvfmeuKePYg->Sup.len : 0);
			if (!(T7_ < ((NI) 2))) goto LA8_;
			echoBinSafe(TM_PFN0uFlSYZ7oiENL9cCUs8A_3, 1);
			exit(((NI) 0));
		}
		LA8_: ;
		T10_ = (NimStringDesc*)0;
		T10_ = dir_gcU9cI3tJjB63nS1HEJzj2g; dir_gcU9cI3tJjB63nS1HEJzj2g = copyStringRC1(args_xNHvKA9bT79a4bvfmeuKePYg->data[((NI) 0)]);
		if (T10_) nimGCunrefNoCycle(T10_);
		minutes_gP8i3Vz6vFrJwUO9bE9arwkA = nsuParseInt(args_xNHvKA9bT79a4bvfmeuKePYg->data[((NI) 1)]);
		{
			NIM_BOOL T13_;
			T13_ = (NIM_BOOL)0;
			T13_ = checkDirUpdateIn_Tnszk9b6W8ZX89aAxiala2PA(dir_gcU9cI3tJjB63nS1HEJzj2g, minutes_gP8i3Vz6vFrJwUO9bE9arwkA);
			if (!T13_) goto LA14_;
			echoBinSafe(TM_PFN0uFlSYZ7oiENL9cCUs8A_9, 1);
		}
		goto LA11_;
		LA14_: ;
		{
			echoBinSafe(TM_PFN0uFlSYZ7oiENL9cCUs8A_11, 1);
			sendmail_rZNS5KpVF9aFxMFONtIxYYA();
		}
		LA11_: ;
	}
	LA3_: ;
}

NIM_EXTERNC N_NOINLINE(void, checklsrsrcDatInit000)(void) {
}

