/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   C:\msys64\mingw64\bin\gcc.exe -c  -w -mno-ms-bitfields -DWIN32_LEAN_AND_MEAN  -ID:\Nim\lib -o d:\Development\bitbucket\java\NetScoutMerger\script\lsrreport\nimcache\stdlib_winlean.o d:\Development\bitbucket\java\NetScoutMerger\script\lsrreport\nimcache\stdlib_winlean.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#include "winsock2.h"
#include "ws2tcpip.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tyObject_GUID_J2WQBMgezjwf6Trblkflgg tyObject_GUID_J2WQBMgezjwf6Trblkflgg;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tyObject_FILETIME_bs4NMleDDVF7xsEK0SGLBw tyObject_FILETIME_bs4NMleDDVF7xsEK0SGLBw;
typedef struct tyObject_AddrInfo_C9ahX3gj0cVjII4vjiaSHBQ tyObject_AddrInfo_C9ahX3gj0cVjII4vjiaSHBQ;
typedef struct tyObject_Servent_uHHxGv5hdkoXDHlVaUxvnA tyObject_Servent_uHHxGv5hdkoXDHlVaUxvnA;
typedef struct tyObject_Hostent_s9ci1ibckZ9c2Zr9bnP2iUq9aw tyObject_Hostent_s9ci1ibckZ9c2Zr9bnP2iUq9aw;
typedef struct tyObject_OSVERSIONINFO_X9bg9adzg6FCyP9bd4JAMb7QA tyObject_OSVERSIONINFO_X9bg9adzg6FCyP9bd4JAMb7QA;
typedef struct tyObject_TFdSet_lYo1mv6gU9aT1ZE1etM9ceog tyObject_TFdSet_lYo1mv6gU9aT1ZE1etM9ceog;
typedef struct tyObject_Timeval_9boMTr1l3P8e1j9aAjdqsQtA tyObject_Timeval_9boMTr1l3P8e1j9aAjdqsQtA;
typedef struct tyObject_OVERLAPPED_9ayhTq9cybD7eA9aZA09akSNXg tyObject_OVERLAPPED_9ayhTq9cybD7eA9aZA09akSNXg;
typedef struct tyObject_SECURITY_ATTRIBUTES_P4HW9ceaevTBZ5O3kGC8yyw tyObject_SECURITY_ATTRIBUTES_P4HW9ceaevTBZ5O3kGC8yyw;
typedef struct tyObject_WIN32_FIND_DATA_aYwmSz9bIz0JHAL9ciwIrnhA tyObject_WIN32_FIND_DATA_aYwmSz9bIz0JHAL9ciwIrnhA;
typedef NI8 tyArray_9cWG514ToTTjfTPLhXXV0IQ[8];
struct tyObject_GUID_J2WQBMgezjwf6Trblkflgg {
NI32 D1;
NI16 D2;
NI16 D3;
tyArray_9cWG514ToTTjfTPLhXXV0IQ D4;
};
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef N_STDCALL_PTR(NCSTRING, tyProc_5ctyytqoGFQ0BA1imFGbVw) (int family, void* paddr, NCSTRING pStringBuffer, NI32 stringBufSize);
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef N_STDCALL_PTR(void, tyProc_9bc9cLDdaqTE6n5J78feKRYg) (tyObject_FILETIME_bs4NMleDDVF7xsEK0SGLBw* lpSystemTimeAsFileTime);
struct tyObject_FILETIME_bs4NMleDDVF7xsEK0SGLBw {
NI32 dwLowDateTime;
NI32 dwHighDateTime;
};
typedef N_STDCALL_PTR(NI32, tyProc_9bXer9a4ps9aSGctILcxWReVw) (void);
typedef N_STDCALL_PTR(NI32, tyProc_aO673xGTLLxou7P7GxoCXA) (NI32 dwFlags, void* lpSource, NI32 dwMessageId, NI32 dwLanguageId, void* lpBuffer, NI32 nSize, void* Arguments);
typedef N_STDCALL_PTR(void, tyProc_im9buRnIvptJfzdASYMEbBA) (void* p);
typedef N_STDCALL_PTR(NI16*, tyProc_9cu0cWy2jNXKVhds9cs4T9a9cA) (void);
typedef N_STDCALL_PTR(NI32, tyProc_hayl9b1HhJokJ1Zo9ctoglPg) (NI16* para1);
typedef N_STDCALL_PTR(NI32, tyProc_IwsYs9blTXXmAlfsBWq604w) (NI16* lpName, NI16* lpValue);
typedef N_STDCALL_PTR(NI, tyProc_9aO2cP4IgwjXF8JfUR57CHQ) (int af, int typ, int protocol);
typedef N_STDCALL_PTR(int, tyProc_IQbFr9cLT9bipWCXYfwYwjOw) (NI s);
typedef N_STDCALL_PTR(int, tyProc_T129bsPZ4FvuSF4rGFSBKkg) (NI s, SOCKADDR* name, unsigned int namelen);
typedef N_STDCALL_PTR(int, tyProc_wy9bpl6t1mtPtDWeg0xLpDA) (NI s, int backlog);
typedef N_STDCALL_PTR(int, tyProc_MvjKU9c5nvs0N3IrS4vNgSw) (NCSTRING nodename, NCSTRING servname, tyObject_AddrInfo_C9ahX3gj0cVjII4vjiaSHBQ* hints, tyObject_AddrInfo_C9ahX3gj0cVjII4vjiaSHBQ** res);
typedef N_STDCALL_PTR(void, tyProc_IV3cwg4tBg3JP8ITSKt7oQ) (tyObject_AddrInfo_C9ahX3gj0cVjII4vjiaSHBQ* ai);
typedef N_STDCALL_PTR(tyObject_Servent_uHHxGv5hdkoXDHlVaUxvnA*, tyProc_E0SwAAX9bj9a9aV7n5MiMKzig) (NCSTRING name, NCSTRING proto);
typedef N_STDCALL_PTR(tyObject_Servent_uHHxGv5hdkoXDHlVaUxvnA*, tyProc_M3E1eZF9azJd5WrGSHMqEDA) (int port, NCSTRING proto);
typedef N_STDCALL_PTR(NU32, tyProc_jPIQsVcE09cbsdBUbAUxTCQ) (NCSTRING cp);
typedef N_STDCALL_PTR(tyObject_Hostent_s9ci1ibckZ9c2Zr9bnP2iUq9aw*, tyProc_oU4d9cTB9cxBBS1maSQYgLMA) (IN_ADDR* ip, unsigned int len, int theType);
typedef N_STDCALL_PTR(tyObject_Hostent_s9ci1ibckZ9c2Zr9bnP2iUq9aw*, tyProc_sUmKECsDIMWXpmy9a1Mqegg) (NCSTRING name);
typedef N_STDCALL_PTR(int, tyProc_7gdD6mJWQegUjarRikmB9bg) (NCSTRING hostname, int len);
typedef N_STDCALL_PTR(int, tyProc_VXEvL0NvawmzSZzsbIHW6Q) (NI s, SOCKADDR* name, unsigned int* namelen);
typedef N_STDCALL_PTR(NCSTRING, tyProc_MgrHyJlVVXQLRahsT9c14gQ) (IN_ADDR i);
typedef NI16 tyArray_aflWNipJsvDAqOSXjzoiEw[128];
struct tyObject_OSVERSIONINFO_X9bg9adzg6FCyP9bd4JAMb7QA {
NI32 dwOSVersionInfoSize;
NI32 dwMajorVersion;
NI32 dwMinorVersion;
NI32 dwBuildNumber;
NI32 dwPlatformId;
tyArray_aflWNipJsvDAqOSXjzoiEw szCSDVersion;
};
typedef N_STDCALL_PTR(NI32, tyProc_pj29cW0AFVn7IRyIuHxtp9bw) (tyObject_OSVERSIONINFO_X9bg9adzg6FCyP9bd4JAMb7QA* lpVersionInfo);
typedef NIM_CHAR tyArray_1NlJ8ipZDU6GZ9bDFAyQjfQ[8];
typedef N_STDCALL_PTR(int, tyProc_jT04OBqVwa9aMiCLMGHPMSg) (SOCKADDR* pAddr, NI32 addrSize, void* unused, NCSTRING pBuff, NI32* pBuffSize);
typedef NIM_CHAR tyArray_Wfh9bjgBQ4UqJsyISUuDSuA[16];
typedef N_STDCALL_PTR(void, tyProc_Tjolzh1w2dIIpj3oCDGPFw) (NI32 error);
typedef N_STDCALL_PTR(int, tyProc_smMaEORdTTSo9bCzv0g049aQ) (NI s, int level, int optname, void* optval, unsigned int* optlen);
typedef N_STDCALL_PTR(int, tyProc_K6tJduk9ckQgneh7oD8F4Bg) (NI s, int level, int optname, void* optval, unsigned int optlen);
typedef NI tyArray_SLBTEB08vk46ttuRaTxAYw[64];
struct tyObject_TFdSet_lYo1mv6gU9aT1ZE1etM9ceog {
int fd_count;
tyArray_SLBTEB08vk46ttuRaTxAYw fd_array;
};
typedef N_STDCALL_PTR(NIM_BOOL, tyProc_8Py1tJvU9bm83KdBcpIBjeQ) (NI s, tyObject_TFdSet_lYo1mv6gU9aT1ZE1etM9ceog* set);
typedef N_STDCALL_PTR(int, tyProc_rWrG4X5lbcXQyLNkF9aNWhQ) (int nfds, tyObject_TFdSet_lYo1mv6gU9aT1ZE1etM9ceog* readfds, tyObject_TFdSet_lYo1mv6gU9aT1ZE1etM9ceog* writefds, tyObject_TFdSet_lYo1mv6gU9aT1ZE1etM9ceog* exceptfds, tyObject_Timeval_9boMTr1l3P8e1j9aAjdqsQtA* timeout);
typedef N_STDCALL_PTR(NI, tyProc_v29cxQYDpNcYLQEZV01BR5g) (NI s, SOCKADDR* a, unsigned int* addrlen);
typedef N_STDCALL_PTR(int, tyProc_As5z9bYt859cLKWaorPRgQYA) (NI16 wVersionRequired, WSADATA* WSData);
typedef N_STDCALL_PTR(NI, tyProc_dh38EbgnCgluxaqYvYonAg) (NI FileHandle, NI ExistingCompletionPort, NU CompletionKey, NI32 NumberOfConcurrentThreads);
typedef N_STDCALL_PTR(NI32, tyProc_JIaVmlkaszRmqoQwQevY9aA) (NI CompletionPort, NI32* lpNumberOfBytesTransferred, NU* lpCompletionKey, tyObject_OVERLAPPED_9ayhTq9cybD7eA9aZA09akSNXg** lpOverlapped, NI32 dwMilliseconds);
typedef N_STDCALL_PTR(void, tyProc_X0Q3cs1Ai9bfe54O0LJQ1fQ) (NI32 para1, NI32 para2, tyObject_OVERLAPPED_9ayhTq9cybD7eA9aZA09akSNXg* para3);
typedef N_STDCALL_PTR(int, tyProc_m8OtNuKklv1X2vQjXQkzSA) (NI s, NI32 dwIoControlCode, void* lpvInBuffer, NI32 cbInBuffer, void* lpvOutBuffer, NI32 cbOutBuffer, NI32* lpcbBytesReturned, tyObject_OVERLAPPED_9ayhTq9cybD7eA9aZA09akSNXg* lpOverlapped, tyProc_X0Q3cs1Ai9bfe54O0LJQ1fQ lpCompletionRoutine);
struct tyObject_OVERLAPPED_9ayhTq9cybD7eA9aZA09akSNXg {
NI* internal;
NI* internalHigh;
NI32 offset;
NI32 offsetHigh;
NI hEvent;
};
typedef N_STDCALL_PTR(int, tyProc_EzSr684Zq8WJvaKasuLSqQ) (NI s, WSABUF* buf, NI32 bufCount, NI32* bytesReceived, NI32* flags, tyObject_OVERLAPPED_9ayhTq9cybD7eA9aZA09akSNXg* lpOverlapped, tyProc_X0Q3cs1Ai9bfe54O0LJQ1fQ completionProc);
typedef N_STDCALL_PTR(int, tyProc_kfyUyr89bETC8vA9b9aJWaMyQ) (NI s, WSABUF* buf, NI32 bufCount, NI32* bytesSent, NI32 flags, tyObject_OVERLAPPED_9ayhTq9cybD7eA9aZA09akSNXg* lpOverlapped, tyProc_X0Q3cs1Ai9bfe54O0LJQ1fQ completionProc);
typedef N_STDCALL_PTR(int, tyProc_IaLzHXnYXlJtUwTTdxZCkg) (NI s, WSABUF* buf, NI32 bufCount, NI32* bytesSent, NI32 flags, SOCKADDR* name, int namelen, tyObject_OVERLAPPED_9ayhTq9cybD7eA9aZA09akSNXg* lpOverlapped, tyProc_X0Q3cs1Ai9bfe54O0LJQ1fQ completionProc);
typedef N_STDCALL_PTR(int, tyProc_3O4G0IBJdJZ47y0NhcqSGA) (NI s, WSABUF* buf, NI32 bufCount, NI32* bytesReceived, NI32* flags, SOCKADDR* name, int* namelen, tyObject_OVERLAPPED_9ayhTq9cybD7eA9aZA09akSNXg* lpOverlapped, tyProc_X0Q3cs1Ai9bfe54O0LJQ1fQ completionProc);
typedef N_STDCALL_PTR(NIM_BOOL, tyProc_y9bTZn8f8ZZ0xDJI0xhgy9bA) (NI CompletionPort, NI32 dwNumberOfBytesTransferred, NU dwCompletionKey, void* lpOverlapped);
typedef N_STDCALL_PTR(NI, tyProc_uryidYWkntM7ddjZSyxvyQ) (void);
typedef N_STDCALL_PTR(NI32, tyProc_P13srMBg9b3d3yEV9aW4NCoA) (NI WaitHandle);
typedef N_STDCALL_PTR(NIM_BOOL, tyProc_f8UTDN69a9cIlDrZoYnegfKw) (NI hEvent);
typedef N_STDCALL_PTR(void, tyProc_D7khg7tG9bCwkkr0wsuurcw) (void* para1, NI32 para2);
typedef N_STDCALL_PTR(NIM_BOOL, tyProc_JxCafHu7hLn8yfng3Vh3tw) (NI* phNewWaitObject, NI hObject, tyProc_D7khg7tG9bCwkkr0wsuurcw Callback, void* Context, NI32 dwMilliseconds, NI32 dwFlags);
typedef N_STDCALL_PTR(int, tyProc_gwfiiqaid9a9cPS02MkvDQZw) (NI s, NI hEventObject, long lNetworkEvents);
typedef N_STDCALL_PTR(NI, tyProc_c1mlTHJvlrhsAf26W9cqx8Q) (tyObject_SECURITY_ATTRIBUTES_P4HW9ceaevTBZ5O3kGC8yyw* lpEventAttributes, NI32 bManualReset, NI32 bInitialState, NI16* lpName);
typedef N_STDCALL_PTR(NI, tyProc_OsjIMZiv5zpV9a3Ct7Sk2Uw) (NI32 dwDesiredAccess, NI32 bInheritHandle, NI32 dwProcessId);
struct tyObject_AddrInfo_C9ahX3gj0cVjII4vjiaSHBQ {
int ai_flags;
int ai_family;
int ai_socktype;
int ai_protocol;
size_t ai_addrlen;
NCSTRING ai_canonname;
SOCKADDR* ai_addr;
tyObject_AddrInfo_C9ahX3gj0cVjII4vjiaSHBQ* ai_next;
};
typedef NIM_CHAR tyArray_NSMq3FMCIrS8gSbyinBZ8w[14];
typedef N_STDCALL_PTR(int, tyProc_4YBDaTH9b4xNNXSV9ahdJZ8w) (NI s, void* buf, int len, int flags);
typedef N_STDCALL_PTR(NI, tyProc_RG83qWQtsxfLxD7HYoLyfA) (NI16* lpFileName, tyObject_WIN32_FIND_DATA_aYwmSz9bIz0JHAL9ciwIrnhA* lpFindFileData);
typedef N_STDCALL_PTR(void, tyProc_ofoySXaAAlxxs9bQS9a1etlg) (NI hFindFile);
typedef N_STDCALL_PTR(NI32, tyProc_jwEWAkul5J6p6K0UfXa1tw) (NI hFindFile, tyObject_WIN32_FIND_DATA_aYwmSz9bIz0JHAL9ciwIrnhA* lpFindFileData);
struct tyObject_Servent_uHHxGv5hdkoXDHlVaUxvnA {
NCSTRING s_name;
NCSTRING* s_aliases;
NCSTRING s_proto;
NI16 s_port;
};
struct tyObject_Hostent_s9ci1ibckZ9c2Zr9bnP2iUq9aw {
NCSTRING h_name;
NCSTRING* h_aliases;
NI16 h_addrtype;
NI16 h_length;
NCSTRING* h_addr_list;
};
struct tyObject_Timeval_9boMTr1l3P8e1j9aAjdqsQtA {
NI32 tv_sec;
NI32 tv_usec;
};
typedef NIM_CHAR tyArray_EWK8XzFKXCg2WflN3ijhqA[257];
typedef NIM_CHAR tyArray_4249al09aeC68W9cvqMnjIYOA[129];
struct tyObject_SECURITY_ATTRIBUTES_P4HW9ceaevTBZ5O3kGC8yyw {
NI32 nLength;
void* lpSecurityDescriptor;
NI32 bInheritHandle;
};
typedef NI16 tyArray_EKfNt9b8uxndgFbu2Ky3XAQ[260];
typedef NI16 tyArray_Get9cpRTS5VjGKP6CDsI9bYA[14];
struct tyObject_WIN32_FIND_DATA_aYwmSz9bIz0JHAL9ciwIrnhA {
NI32 dwFileAttributes;
tyObject_FILETIME_bs4NMleDDVF7xsEK0SGLBw ftCreationTime;
tyObject_FILETIME_bs4NMleDDVF7xsEK0SGLBw ftLastAccessTime;
tyObject_FILETIME_bs4NMleDDVF7xsEK0SGLBw ftLastWriteTime;
NI32 nFileSizeHigh;
NI32 nFileSizeLow;
NI32 dwReserved0;
NI32 dwReserved1;
tyArray_EKfNt9b8uxndgFbu2Ky3XAQ cFileName;
tyArray_Get9cpRTS5VjGKP6CDsI9bYA cAlternateFileName;
};
N_NOINLINE(void, chckNil)(void* p);
N_NIMCALL(void, genericReset)(void* dest, TNimType* mt);
N_LIB_PRIVATE N_NIMCALL(void*, loadLib_EFK1MHQsQvQPg5NaJH389bA)(NimStringDesc* path, NIM_BOOL global_symbols);
N_LIB_PRIVATE N_NIMCALL(void*, symAddr_fM7lTRTvv9a9axreJA2Bx7jA_2)(void* lib, NCSTRING name);
N_NIMCALL(void*, nimLoadLibrary)(NimStringDesc* path);
N_NOINLINE(void, nimLoadLibraryError)(NimStringDesc* path);
N_NIMCALL(void*, nimGetProcAddr)(void* lib, NCSTRING name);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
N_LIB_PRIVATE N_NIMCALL(void, quit_y2WuTG82qH44FHhQsKXOCg)(NimStringDesc* errormsg, NI errorcode) __attribute__((noreturn));
N_LIB_PRIVATE N_STDCALL(NCSTRING, inet_ntop_emulated_NHL7Tp5fr9bGcxCKxCTK3RA)(int family, void* paddr, NCSTRING pStringBuffer, NI32 stringBufSize);
N_NOINLINE(void, raiseIndexError)(void);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
tyObject_GUID_J2WQBMgezjwf6Trblkflgg WSAID_CONNECTEX_YmR9c9crObjjK9ckt1ygsPQKg;
TNimType NTI_J2WQBMgezjwf6Trblkflgg_;
extern TNimType NTI_sVg18TP9cLifHyygRe9cro9aA_;
extern TNimType NTI_kDPg4wXyR8DDyA0MeEjIsw_;
extern TNimType NTI_chXunH2dwinSkhpA6JnsXw_;
TNimType NTI_9cWG514ToTTjfTPLhXXV0IQ_;
tyObject_GUID_J2WQBMgezjwf6Trblkflgg WSAID_ACCEPTEX_pwoOiDuyZgHBOLaI2GSBpg;
tyObject_GUID_J2WQBMgezjwf6Trblkflgg WSAID_GETACCEPTEXSOCKADDRS_rSjtFMq7pCHQR2EQvcKbDg;
tyProc_5ctyytqoGFQ0BA1imFGbVw inet_ntop_real_FVXn9aJ5AOo23ScDsZUc9aZw;
void* ws2_hGspZUrVrEMpO9aP9c3dJQPQ;
static void* TM_k6kyf4Co79a84IkK9blFuQVA_6;
tyProc_9bc9cLDdaqTE6n5J78feKRYg Dl_133625_;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
tyProc_9bXer9a4ps9aSGctILcxWReVw Dl_132630_;
tyProc_aO673xGTLLxou7P7GxoCXA Dl_132635_;
tyProc_im9buRnIvptJfzdASYMEbBA Dl_132801_;
tyProc_9cu0cWy2jNXKVhds9cs4T9a9cA Dl_133432_;
tyProc_hayl9b1HhJokJ1Zo9ctoglPg Dl_133434_;
tyProc_IwsYs9blTXXmAlfsBWq604w Dl_132818_;
static void* TM_k6kyf4Co79a84IkK9blFuQVA_24;
tyProc_9aO2cP4IgwjXF8JfUR57CHQ Dl_133999_;
tyProc_IQbFr9cLT9bipWCXYfwYwjOw Dl_134004_;
tyProc_T129bsPZ4FvuSF4rGFSBKkg Dl_134014_;
tyProc_wy9bpl6t1mtPtDWeg0xLpDA Dl_134055_;
tyProc_MvjKU9c5nvs0N3IrS4vNgSw Dl_134151_;
tyProc_IV3cwg4tBg3JP8ITSKt7oQ Dl_134160_;
tyProc_E0SwAAX9bj9a9aV7n5MiMKzig Dl_133974_;
tyProc_M3E1eZF9azJd5WrGSHMqEDA Dl_133979_;
tyProc_jPIQsVcE09cbsdBUbAUxTCQ Dl_134113_;
tyProc_oU4d9cTB9cxBBS1maSQYgLMA Dl_133984_;
tyProc_sUmKECsDIMWXpmy9a1Mqegg Dl_133991_;
tyProc_7gdD6mJWQegUjarRikmB9bg Dl_133995_;
tyProc_VXEvL0NvawmzSZzsbIHW6Q Dl_134026_;
tyProc_MgrHyJlVVXQLRahsT9c14gQ Dl_134164_;
tyProc_pj29cW0AFVn7IRyIuHxtp9bw Dl_132325_;
tyProc_jT04OBqVwa9aMiCLMGHPMSg Dl_134828_;
tyProc_Tjolzh1w2dIIpj3oCDGPFw Dl_132632_;
tyProc_VXEvL0NvawmzSZzsbIHW6Q Dl_134033_;
tyProc_smMaEORdTTSo9bCzv0g049aQ Dl_134040_;
tyProc_K6tJduk9ckQgneh7oD8F4Bg Dl_134048_;
tyProc_8Py1tJvU9bm83KdBcpIBjeQ Dl_134116_;
tyProc_rWrG4X5lbcXQyLNkF9aNWhQ Dl_134075_;
tyProc_v29cxQYDpNcYLQEZV01BR5g Dl_134007_;
tyProc_As5z9bYt859cLKWaorPRgQYA Dl_134146_;
tyProc_dh38EbgnCgluxaqYvYonAg Dl_134666_;
tyProc_JIaVmlkaszRmqoQwQevY9aA Dl_134672_;
tyProc_m8OtNuKklv1X2vQjXQkzSA Dl_134732_;
TNimType NTI_C9agHgxfUtpEDlac6Nu0MCw_;
TNimType NTI_9ayhTq9cybD7eA9aZA09akSNXg_;
extern TNimType NTI_BVbkP29c9aHJK9bePRvpX9bHIQ_;
extern TNimType NTI_rR5Bzr1D5krxoo1NcNyeMA_;
tyProc_EzSr684Zq8WJvaKasuLSqQ Dl_134747_;
tyProc_kfyUyr89bETC8vA9b9aJWaMyQ Dl_134771_;
tyProc_IaLzHXnYXlJtUwTTdxZCkg Dl_134781_;
tyProc_3O4G0IBJdJZ47y0NhcqSGA Dl_134757_;
tyProc_y9bTZn8f8ZZ0xDJI0xhgy9bA Dl_135120_;
static void* TM_k6kyf4Co79a84IkK9blFuQVA_95;
tyProc_uryidYWkntM7ddjZSyxvyQ Dl_135220_;
tyProc_P13srMBg9b3d3yEV9aW4NCoA Dl_135135_;
tyProc_f8UTDN69a9cIlDrZoYnegfKw Dl_135222_;
tyProc_JxCafHu7hLn8yfng3Vh3tw Dl_135126_;
tyProc_gwfiiqaid9a9cPS02MkvDQZw Dl_135215_;
tyProc_c1mlTHJvlrhsAf26W9cqx8Q Dl_135143_;
tyProc_P13srMBg9b3d3yEV9aW4NCoA Dl_132403_;
tyProc_OsjIMZiv5zpV9a3Ct7Sk2Uw Dl_135138_;
tyProc_IQbFr9cLT9bipWCXYfwYwjOw Dl_135201_;
TNimType NTI_C9ahX3gj0cVjII4vjiaSHBQ_;
extern TNimType NTI_nlCscttRCss70IBTyuBqnA_;
extern TNimType NTI_xy421WszHaaock9a15gQDRg_;
extern TNimType NTI_S9agCYBinaYZnGWcjTdxclg_;
TNimType NTI_iPePZVyyc9cQV6V9cwz9ajG9bg_;
TNimType NTI_nBU9bsV5o5Xw80pGpGVR8Bw_;
TNimType NTI_9boVVq0W9aThvt3y6X6MODJQ_;
tyProc_4YBDaTH9b4xNNXSV9ahdJZ8w Dl_134084_;
tyProc_4YBDaTH9b4xNNXSV9ahdJZ8w Dl_134059_;
tyProc_T129bsPZ4FvuSF4rGFSBKkg Dl_134020_;
tyProc_RG83qWQtsxfLxD7HYoLyfA Dl_133238_;
tyProc_ofoySXaAAlxxs9bQS9a1etlg Dl_133401_;
tyProc_jwEWAkul5J6p6K0UfXa1tw Dl_133243_;
tyProc_9cu0cWy2jNXKVhds9cs4T9a9cA Dl_133437_;
NIM_CONST tyArray_9cWG514ToTTjfTPLhXXV0IQ TM_k6kyf4Co79a84IkK9blFuQVA_3 = {((NI8) -114),
((NI8) -23),
((NI8) 118),
((NI8) -27),
((NI8) -116),
((NI8) 116),
((NI8) 6),
((NI8) 62)}
;
NIM_CONST tyArray_9cWG514ToTTjfTPLhXXV0IQ TM_k6kyf4Co79a84IkK9blFuQVA_4 = {((NI8) -107),
((NI8) -54),
((NI8) 0),
((NI8) -128),
((NI8) 95),
((NI8) 72),
((NI8) -95),
((NI8) -110)}
;
STRING_LITERAL(TM_k6kyf4Co79a84IkK9blFuQVA_5, "Ws2_32.dll", 10);
STRING_LITERAL(TM_k6kyf4Co79a84IkK9blFuQVA_8, "kernel32", 8);
STRING_LITERAL(TM_k6kyf4Co79a84IkK9blFuQVA_9, "kernel32", 8);
STRING_LITERAL(TM_k6kyf4Co79a84IkK9blFuQVA_26, "Ws2_32.dll", 10);
STRING_LITERAL(TM_k6kyf4Co79a84IkK9blFuQVA_27, "Ws2_32.dll", 10);
STRING_LITERAL(TM_k6kyf4Co79a84IkK9blFuQVA_58, "Can\'t load inet_ntop proc from Ws2_32.dll", 41);
STRING_LITERAL(TM_k6kyf4Co79a84IkK9blFuQVA_97, "ws2_32.dll", 10);
STRING_LITERAL(TM_k6kyf4Co79a84IkK9blFuQVA_98, "ws2_32.dll", 10);

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

N_LIB_PRIVATE N_NIMCALL(NI64, rdFileTime_8xfVp1z4bc5fRCRgoEFhIQ)(tyObject_FILETIME_bs4NMleDDVF7xsEK0SGLBw f) {
	NI64 result;
	nimfr_("rdFileTime", "winlean.nim");
	result = (NI64)0;
	nimln_(397, "winlean.nim");
	result = (NI64)(((NI64)(NU64)(NU32)(f.dwLowDateTime)) | (NI64)((NU64)(((NI64)(NU64)(NU32)(f.dwHighDateTime))) << (NU64)(((NI) 32))));
	popFrame();
	return result;
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (a <= i);
		if (!(T3_)) goto LA4_;
		T3_ = (i <= b);
		LA4_: ;
		if (!T3_) goto LA5_;
		result = i;
		goto BeforeRet_;
	}
	goto LA1_;
	LA5_: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1_: ;
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_STDCALL(NCSTRING, inet_ntop_emulated_NHL7Tp5fr9bGcxCKxCTK3RA)(int family, void* paddr, NCSTRING pStringBuffer, NI32 stringBufSize) {
	NCSTRING result;
	nimfr_("inet_ntop_emulated", "winlean.nim");
	result = (NCSTRING)0;
	nimln_(892, "winlean.nim");
	switch (family) {
	case ((NI) 2):
	{
		SOCKADDR_IN sa;
		NI32 bs;
		int r;
		memset((void*)(&sa), 0, sizeof(sa));
		nimln_(895, "winlean.nim");
		sa.sin_family = ((NI16) 2);
		nimln_(896, "winlean.nim");
		sa.sin_addr = (*((IN_ADDR*) (paddr)));
		nimln_(897, "winlean.nim");
		bs = stringBufSize;
		nimln_(898, "winlean.nim");
		r = Dl_134828_(((SOCKADDR*) ((&sa))), ((NI32)chckRange(((NI)sizeof(SOCKADDR_IN)), ((NI32) (-2147483647 -1)), ((NI32) 2147483647))), NIM_NIL, pStringBuffer, (&bs));
		nimln_(899, "winlean.nim");
		{
			nimln_(398, "system.nim");
			nimln_(899, "winlean.nim");
			if (!!((r == ((NI32) 0)))) goto LA4_;
			nimln_(900, "winlean.nim");
			result = NIM_NIL;
		}
		goto LA2_;
		LA4_: ;
		{
			nimln_(902, "winlean.nim");
			result = pStringBuffer;
		}
		LA2_: ;
	}
	break;
	case ((NI) 23):
	{
		SOCKADDR_IN6 sa_2;
		NI32 bs_2;
		int r_2;
		memset((void*)(&sa_2), 0, sizeof(sa_2));
		nimln_(905, "winlean.nim");
		sa_2.sin6_family = ((NI16) 23);
		nimln_(906, "winlean.nim");
		sa_2.sin6_addr = (*((IN6_ADDR*) (paddr)));
		nimln_(907, "winlean.nim");
		bs_2 = stringBufSize;
		nimln_(908, "winlean.nim");
		r_2 = Dl_134828_(((SOCKADDR*) ((&sa_2))), ((NI32)chckRange(((NI)sizeof(SOCKADDR_IN6)), ((NI32) (-2147483647 -1)), ((NI32) 2147483647))), NIM_NIL, pStringBuffer, (&bs_2));
		nimln_(909, "winlean.nim");
		{
			nimln_(398, "system.nim");
			nimln_(909, "winlean.nim");
			if (!!((r_2 == ((NI32) 0)))) goto LA10_;
			nimln_(910, "winlean.nim");
			result = NIM_NIL;
		}
		goto LA8_;
		LA10_: ;
		{
			nimln_(912, "winlean.nim");
			result = pStringBuffer;
		}
		LA8_: ;
	}
	break;
	default:
	{
		nimln_(914, "winlean.nim");
		Dl_132632_(((NI32) 165));
		nimln_(915, "winlean.nim");
		result = NIM_NIL;
	}
	break;
	}
	popFrame();
	return result;
}

N_LIB_PRIVATE N_STDCALL(NCSTRING, inet_ntop_LTipcLQ2Q4XlT8sQeiwC8A)(int family, void* paddr, NCSTRING pStringBuffer, NI32 stringBufSize) {
	NCSTRING result;
	tyObject_OSVERSIONINFO_X9bg9adzg6FCyP9bd4JAMb7QA ver;
	NI32 res;
	nimfr_("inet_ntop", "winlean.nim");
	result = (NCSTRING)0;
	memset((void*)(&ver), 0, sizeof(ver));
	nimln_(920, "winlean.nim");
	ver.dwOSVersionInfoSize = ((NI32)chckRange(((NI)sizeof(tyObject_OSVERSIONINFO_X9bg9adzg6FCyP9bd4JAMb7QA)), ((NI32) (-2147483647 -1)), ((NI32) 2147483647)));
	nimln_(921, "winlean.nim");
	res = Dl_132325_((&ver));
	nimln_(922, "winlean.nim");
	{
		if (!(res == ((NI32) 0))) goto LA3_;
		nimln_(923, "winlean.nim");
		result = NIM_NIL;
	}
	goto LA1_;
	LA3_: ;
	{
		nimln_(924, "winlean.nim");
		if (!(((NI32) 6) <= ver.dwMajorVersion)) goto LA6_;
		nimln_(925, "winlean.nim");
		{
			if (!(inet_ntop_real_FVXn9aJ5AOo23ScDsZUc9aZw == NIM_NIL)) goto LA10_;
			nimln_(926, "winlean.nim");
			quit_y2WuTG82qH44FHhQsKXOCg(((NimStringDesc*) &TM_k6kyf4Co79a84IkK9blFuQVA_58), ((NI) 1));
		}
		LA10_: ;
		nimln_(927, "winlean.nim");
		result = inet_ntop_real_FVXn9aJ5AOo23ScDsZUc9aZw(family, paddr, pStringBuffer, stringBufSize);
	}
	goto LA1_;
	LA6_: ;
	{
		nimln_(929, "winlean.nim");
		result = inet_ntop_emulated_NHL7Tp5fr9bGcxCKxCTK3RA(family, paddr, pStringBuffer, stringBufSize);
	}
	LA1_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, FD_ZERO_yeePfMmq9aNgPmxq9aV4wa4A)(tyObject_TFdSet_lYo1mv6gU9aT1ZE1etM9ceog* s) {
	nimfr_("FD_ZERO", "winlean.nim");
	nimln_(628, "winlean.nim");
	(*s).fd_count = ((int) 0);
	popFrame();
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, FD_SET_RyfVGaM8zBlYSZOQ5CvEEQ)(NI socket_0, tyObject_TFdSet_lYo1mv6gU9aT1ZE1etM9ceog* s) {
	nimfr_("FD_SET", "winlean.nim");
	nimln_(623, "winlean.nim");
	{
		NI TM_k6kyf4Co79a84IkK9blFuQVA_69;
		if (!((*s).fd_count < ((NI32) 64))) goto LA3_;
		if ((NU)(((NI) ((*s).fd_count))) > (NU)(63)) raiseIndexError();
		nimln_(624, "winlean.nim");
		(*s).fd_array[(((NI) ((*s).fd_count)))- 0] = socket_0;
		nimln_(625, "winlean.nim");
		TM_k6kyf4Co79a84IkK9blFuQVA_69 = addInt((*s).fd_count, ((NI) 1));
		if (TM_k6kyf4Co79a84IkK9blFuQVA_69 < (-2147483647 -1) || TM_k6kyf4Co79a84IkK9blFuQVA_69 > 2147483647) raiseOverflow();
		(*s).fd_count = (int)(TM_k6kyf4Co79a84IkK9blFuQVA_69);
	}
	LA3_: ;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(int, FD_ISSET_NkjjeLx4p9b4GT29buKQYcxA)(NI socket_0, tyObject_TFdSet_lYo1mv6gU9aT1ZE1etM9ceog* set) {
	int result;
	nimfr_("FD_ISSET", "winlean.nim");
	result = (int)0;
	nimln_(620, "winlean.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = Dl_134116_(socket_0, set);
		if (!T3_) goto LA4_;
		result = ((NI32) 1);
	}
	goto LA1_;
	LA4_: ;
	{
		result = ((NI32) 0);
	}
	LA1_: ;
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_winleanInit000)(void) {
	nimfr_("winlean", "winlean.nim");
	nimln_(829, "winlean.nim");
	chckNil((void*)(&WSAID_CONNECTEX_YmR9c9crObjjK9ckt1ygsPQKg));
	genericReset((void*)(&WSAID_CONNECTEX_YmR9c9crObjjK9ckt1ygsPQKg), (&NTI_J2WQBMgezjwf6Trblkflgg_));
	WSAID_CONNECTEX_YmR9c9crObjjK9ckt1ygsPQKg.D1 = ((NI32) 631375801);
	WSAID_CONNECTEX_YmR9c9crObjjK9ckt1ygsPQKg.D2 = ((NI16) -8717);
	WSAID_CONNECTEX_YmR9c9crObjjK9ckt1ygsPQKg.D3 = ((NI16) 18016);
	memcpy((void*)WSAID_CONNECTEX_YmR9c9crObjjK9ckt1ygsPQKg.D4, (NIM_CONST void*)TM_k6kyf4Co79a84IkK9blFuQVA_3, sizeof(tyArray_9cWG514ToTTjfTPLhXXV0IQ));
	nimln_(831, "winlean.nim");
	chckNil((void*)(&WSAID_ACCEPTEX_pwoOiDuyZgHBOLaI2GSBpg));
	genericReset((void*)(&WSAID_ACCEPTEX_pwoOiDuyZgHBOLaI2GSBpg), (&NTI_J2WQBMgezjwf6Trblkflgg_));
	WSAID_ACCEPTEX_pwoOiDuyZgHBOLaI2GSBpg.D1 = ((NI32) -1254720015);
	WSAID_ACCEPTEX_pwoOiDuyZgHBOLaI2GSBpg.D2 = ((NI16) -13396);
	WSAID_ACCEPTEX_pwoOiDuyZgHBOLaI2GSBpg.D3 = ((NI16) 4559);
	memcpy((void*)WSAID_ACCEPTEX_pwoOiDuyZgHBOLaI2GSBpg.D4, (NIM_CONST void*)TM_k6kyf4Co79a84IkK9blFuQVA_4, sizeof(tyArray_9cWG514ToTTjfTPLhXXV0IQ));
	nimln_(833, "winlean.nim");
	chckNil((void*)(&WSAID_GETACCEPTEXSOCKADDRS_rSjtFMq7pCHQR2EQvcKbDg));
	genericReset((void*)(&WSAID_GETACCEPTEXSOCKADDRS_rSjtFMq7pCHQR2EQvcKbDg), (&NTI_J2WQBMgezjwf6Trblkflgg_));
	WSAID_GETACCEPTEXSOCKADDRS_rSjtFMq7pCHQR2EQvcKbDg.D1 = ((NI32) -1254720014);
	WSAID_GETACCEPTEXSOCKADDRS_rSjtFMq7pCHQR2EQvcKbDg.D2 = ((NI16) -13396);
	WSAID_GETACCEPTEXSOCKADDRS_rSjtFMq7pCHQR2EQvcKbDg.D3 = ((NI16) 4559);
	memcpy((void*)WSAID_GETACCEPTEXSOCKADDRS_rSjtFMq7pCHQR2EQvcKbDg.D4, (NIM_CONST void*)TM_k6kyf4Co79a84IkK9blFuQVA_4, sizeof(tyArray_9cWG514ToTTjfTPLhXXV0IQ));
	nimln_(883, "winlean.nim");
	inet_ntop_real_FVXn9aJ5AOo23ScDsZUc9aZw = NIM_NIL;
	nimln_(885, "winlean.nim");
	ws2_hGspZUrVrEMpO9aP9c3dJQPQ = loadLib_EFK1MHQsQvQPg5NaJH389bA(((NimStringDesc*) &TM_k6kyf4Co79a84IkK9blFuQVA_5), NIM_FALSE);
	nimln_(886, "winlean.nim");
	{
		void* T5_;
		nimln_(398, "system.nim");
		nimln_(886, "winlean.nim");
		if (!!((ws2_hGspZUrVrEMpO9aP9c3dJQPQ == NIM_NIL))) goto LA3_;
		nimln_(887, "winlean.nim");
		T5_ = (void*)0;
		T5_ = symAddr_fM7lTRTvv9a9axreJA2Bx7jA_2(ws2_hGspZUrVrEMpO9aP9c3dJQPQ, "inet_ntop");
		inet_ntop_real_FVXn9aJ5AOo23ScDsZUc9aZw = ((tyProc_5ctyytqoGFQ0BA1imFGbVw) (T5_));
	}
	LA3_: ;
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_winleanDatInit000)(void) {
static TNimNode* TM_k6kyf4Co79a84IkK9blFuQVA_2[4];
static TNimNode* TM_k6kyf4Co79a84IkK9blFuQVA_84[5];
static TNimNode* TM_k6kyf4Co79a84IkK9blFuQVA_117[8];
static TNimNode TM_k6kyf4Co79a84IkK9blFuQVA_0[22];
NTI_J2WQBMgezjwf6Trblkflgg_.size = sizeof(tyObject_GUID_J2WQBMgezjwf6Trblkflgg);
NTI_J2WQBMgezjwf6Trblkflgg_.kind = 18;
NTI_J2WQBMgezjwf6Trblkflgg_.base = 0;
NTI_J2WQBMgezjwf6Trblkflgg_.flags = 3;
TM_k6kyf4Co79a84IkK9blFuQVA_2[0] = &TM_k6kyf4Co79a84IkK9blFuQVA_0[1];
TM_k6kyf4Co79a84IkK9blFuQVA_0[1].kind = 1;
TM_k6kyf4Co79a84IkK9blFuQVA_0[1].offset = offsetof(tyObject_GUID_J2WQBMgezjwf6Trblkflgg, D1);
TM_k6kyf4Co79a84IkK9blFuQVA_0[1].typ = (&NTI_sVg18TP9cLifHyygRe9cro9aA_);
TM_k6kyf4Co79a84IkK9blFuQVA_0[1].name = "D1";
TM_k6kyf4Co79a84IkK9blFuQVA_2[1] = &TM_k6kyf4Co79a84IkK9blFuQVA_0[2];
TM_k6kyf4Co79a84IkK9blFuQVA_0[2].kind = 1;
TM_k6kyf4Co79a84IkK9blFuQVA_0[2].offset = offsetof(tyObject_GUID_J2WQBMgezjwf6Trblkflgg, D2);
TM_k6kyf4Co79a84IkK9blFuQVA_0[2].typ = (&NTI_kDPg4wXyR8DDyA0MeEjIsw_);
TM_k6kyf4Co79a84IkK9blFuQVA_0[2].name = "D2";
TM_k6kyf4Co79a84IkK9blFuQVA_2[2] = &TM_k6kyf4Co79a84IkK9blFuQVA_0[3];
TM_k6kyf4Co79a84IkK9blFuQVA_0[3].kind = 1;
TM_k6kyf4Co79a84IkK9blFuQVA_0[3].offset = offsetof(tyObject_GUID_J2WQBMgezjwf6Trblkflgg, D3);
TM_k6kyf4Co79a84IkK9blFuQVA_0[3].typ = (&NTI_kDPg4wXyR8DDyA0MeEjIsw_);
TM_k6kyf4Co79a84IkK9blFuQVA_0[3].name = "D3";
TM_k6kyf4Co79a84IkK9blFuQVA_2[3] = &TM_k6kyf4Co79a84IkK9blFuQVA_0[4];
NTI_9cWG514ToTTjfTPLhXXV0IQ_.size = sizeof(tyArray_9cWG514ToTTjfTPLhXXV0IQ);
NTI_9cWG514ToTTjfTPLhXXV0IQ_.kind = 16;
NTI_9cWG514ToTTjfTPLhXXV0IQ_.base = (&NTI_chXunH2dwinSkhpA6JnsXw_);
NTI_9cWG514ToTTjfTPLhXXV0IQ_.flags = 3;
TM_k6kyf4Co79a84IkK9blFuQVA_0[4].kind = 1;
TM_k6kyf4Co79a84IkK9blFuQVA_0[4].offset = offsetof(tyObject_GUID_J2WQBMgezjwf6Trblkflgg, D4);
TM_k6kyf4Co79a84IkK9blFuQVA_0[4].typ = (&NTI_9cWG514ToTTjfTPLhXXV0IQ_);
TM_k6kyf4Co79a84IkK9blFuQVA_0[4].name = "D4";
TM_k6kyf4Co79a84IkK9blFuQVA_0[0].len = 4; TM_k6kyf4Co79a84IkK9blFuQVA_0[0].kind = 2; TM_k6kyf4Co79a84IkK9blFuQVA_0[0].sons = &TM_k6kyf4Co79a84IkK9blFuQVA_2[0];
NTI_J2WQBMgezjwf6Trblkflgg_.node = &TM_k6kyf4Co79a84IkK9blFuQVA_0[0];
NTI_C9agHgxfUtpEDlac6Nu0MCw_.size = sizeof(WSABUF);
NTI_C9agHgxfUtpEDlac6Nu0MCw_.kind = 18;
NTI_C9agHgxfUtpEDlac6Nu0MCw_.base = 0;
NTI_C9agHgxfUtpEDlac6Nu0MCw_.flags = 3;
NTI_C9agHgxfUtpEDlac6Nu0MCw_.node = &TM_k6kyf4Co79a84IkK9blFuQVA_0[5];
NTI_9ayhTq9cybD7eA9aZA09akSNXg_.size = sizeof(tyObject_OVERLAPPED_9ayhTq9cybD7eA9aZA09akSNXg);
NTI_9ayhTq9cybD7eA9aZA09akSNXg_.kind = 18;
NTI_9ayhTq9cybD7eA9aZA09akSNXg_.base = 0;
NTI_9ayhTq9cybD7eA9aZA09akSNXg_.flags = 1;
TM_k6kyf4Co79a84IkK9blFuQVA_84[0] = &TM_k6kyf4Co79a84IkK9blFuQVA_0[7];
TM_k6kyf4Co79a84IkK9blFuQVA_0[7].kind = 1;
TM_k6kyf4Co79a84IkK9blFuQVA_0[7].offset = offsetof(tyObject_OVERLAPPED_9ayhTq9cybD7eA9aZA09akSNXg, internal);
TM_k6kyf4Co79a84IkK9blFuQVA_0[7].typ = (&NTI_BVbkP29c9aHJK9bePRvpX9bHIQ_);
TM_k6kyf4Co79a84IkK9blFuQVA_0[7].name = "internal";
TM_k6kyf4Co79a84IkK9blFuQVA_84[1] = &TM_k6kyf4Co79a84IkK9blFuQVA_0[8];
TM_k6kyf4Co79a84IkK9blFuQVA_0[8].kind = 1;
TM_k6kyf4Co79a84IkK9blFuQVA_0[8].offset = offsetof(tyObject_OVERLAPPED_9ayhTq9cybD7eA9aZA09akSNXg, internalHigh);
TM_k6kyf4Co79a84IkK9blFuQVA_0[8].typ = (&NTI_BVbkP29c9aHJK9bePRvpX9bHIQ_);
TM_k6kyf4Co79a84IkK9blFuQVA_0[8].name = "internalHigh";
TM_k6kyf4Co79a84IkK9blFuQVA_84[2] = &TM_k6kyf4Co79a84IkK9blFuQVA_0[9];
TM_k6kyf4Co79a84IkK9blFuQVA_0[9].kind = 1;
TM_k6kyf4Co79a84IkK9blFuQVA_0[9].offset = offsetof(tyObject_OVERLAPPED_9ayhTq9cybD7eA9aZA09akSNXg, offset);
TM_k6kyf4Co79a84IkK9blFuQVA_0[9].typ = (&NTI_sVg18TP9cLifHyygRe9cro9aA_);
TM_k6kyf4Co79a84IkK9blFuQVA_0[9].name = "offset";
TM_k6kyf4Co79a84IkK9blFuQVA_84[3] = &TM_k6kyf4Co79a84IkK9blFuQVA_0[10];
TM_k6kyf4Co79a84IkK9blFuQVA_0[10].kind = 1;
TM_k6kyf4Co79a84IkK9blFuQVA_0[10].offset = offsetof(tyObject_OVERLAPPED_9ayhTq9cybD7eA9aZA09akSNXg, offsetHigh);
TM_k6kyf4Co79a84IkK9blFuQVA_0[10].typ = (&NTI_sVg18TP9cLifHyygRe9cro9aA_);
TM_k6kyf4Co79a84IkK9blFuQVA_0[10].name = "offsetHigh";
TM_k6kyf4Co79a84IkK9blFuQVA_84[4] = &TM_k6kyf4Co79a84IkK9blFuQVA_0[11];
TM_k6kyf4Co79a84IkK9blFuQVA_0[11].kind = 1;
TM_k6kyf4Co79a84IkK9blFuQVA_0[11].offset = offsetof(tyObject_OVERLAPPED_9ayhTq9cybD7eA9aZA09akSNXg, hEvent);
TM_k6kyf4Co79a84IkK9blFuQVA_0[11].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_k6kyf4Co79a84IkK9blFuQVA_0[11].name = "hEvent";
TM_k6kyf4Co79a84IkK9blFuQVA_0[6].len = 5; TM_k6kyf4Co79a84IkK9blFuQVA_0[6].kind = 2; TM_k6kyf4Co79a84IkK9blFuQVA_0[6].sons = &TM_k6kyf4Co79a84IkK9blFuQVA_84[0];
NTI_9ayhTq9cybD7eA9aZA09akSNXg_.node = &TM_k6kyf4Co79a84IkK9blFuQVA_0[6];
NTI_C9ahX3gj0cVjII4vjiaSHBQ_.size = sizeof(tyObject_AddrInfo_C9ahX3gj0cVjII4vjiaSHBQ);
NTI_C9ahX3gj0cVjII4vjiaSHBQ_.kind = 18;
NTI_C9ahX3gj0cVjII4vjiaSHBQ_.base = 0;
NTI_C9ahX3gj0cVjII4vjiaSHBQ_.flags = 3;
TM_k6kyf4Co79a84IkK9blFuQVA_117[0] = &TM_k6kyf4Co79a84IkK9blFuQVA_0[13];
TM_k6kyf4Co79a84IkK9blFuQVA_0[13].kind = 1;
TM_k6kyf4Co79a84IkK9blFuQVA_0[13].offset = offsetof(tyObject_AddrInfo_C9ahX3gj0cVjII4vjiaSHBQ, ai_flags);
TM_k6kyf4Co79a84IkK9blFuQVA_0[13].typ = (&NTI_nlCscttRCss70IBTyuBqnA_);
TM_k6kyf4Co79a84IkK9blFuQVA_0[13].name = "ai_flags";
TM_k6kyf4Co79a84IkK9blFuQVA_117[1] = &TM_k6kyf4Co79a84IkK9blFuQVA_0[14];
TM_k6kyf4Co79a84IkK9blFuQVA_0[14].kind = 1;
TM_k6kyf4Co79a84IkK9blFuQVA_0[14].offset = offsetof(tyObject_AddrInfo_C9ahX3gj0cVjII4vjiaSHBQ, ai_family);
TM_k6kyf4Co79a84IkK9blFuQVA_0[14].typ = (&NTI_nlCscttRCss70IBTyuBqnA_);
TM_k6kyf4Co79a84IkK9blFuQVA_0[14].name = "ai_family";
TM_k6kyf4Co79a84IkK9blFuQVA_117[2] = &TM_k6kyf4Co79a84IkK9blFuQVA_0[15];
TM_k6kyf4Co79a84IkK9blFuQVA_0[15].kind = 1;
TM_k6kyf4Co79a84IkK9blFuQVA_0[15].offset = offsetof(tyObject_AddrInfo_C9ahX3gj0cVjII4vjiaSHBQ, ai_socktype);
TM_k6kyf4Co79a84IkK9blFuQVA_0[15].typ = (&NTI_nlCscttRCss70IBTyuBqnA_);
TM_k6kyf4Co79a84IkK9blFuQVA_0[15].name = "ai_socktype";
TM_k6kyf4Co79a84IkK9blFuQVA_117[3] = &TM_k6kyf4Co79a84IkK9blFuQVA_0[16];
TM_k6kyf4Co79a84IkK9blFuQVA_0[16].kind = 1;
TM_k6kyf4Co79a84IkK9blFuQVA_0[16].offset = offsetof(tyObject_AddrInfo_C9ahX3gj0cVjII4vjiaSHBQ, ai_protocol);
TM_k6kyf4Co79a84IkK9blFuQVA_0[16].typ = (&NTI_nlCscttRCss70IBTyuBqnA_);
TM_k6kyf4Co79a84IkK9blFuQVA_0[16].name = "ai_protocol";
TM_k6kyf4Co79a84IkK9blFuQVA_117[4] = &TM_k6kyf4Co79a84IkK9blFuQVA_0[17];
TM_k6kyf4Co79a84IkK9blFuQVA_0[17].kind = 1;
TM_k6kyf4Co79a84IkK9blFuQVA_0[17].offset = offsetof(tyObject_AddrInfo_C9ahX3gj0cVjII4vjiaSHBQ, ai_addrlen);
TM_k6kyf4Co79a84IkK9blFuQVA_0[17].typ = (&NTI_xy421WszHaaock9a15gQDRg_);
TM_k6kyf4Co79a84IkK9blFuQVA_0[17].name = "ai_addrlen";
TM_k6kyf4Co79a84IkK9blFuQVA_117[5] = &TM_k6kyf4Co79a84IkK9blFuQVA_0[18];
TM_k6kyf4Co79a84IkK9blFuQVA_0[18].kind = 1;
TM_k6kyf4Co79a84IkK9blFuQVA_0[18].offset = offsetof(tyObject_AddrInfo_C9ahX3gj0cVjII4vjiaSHBQ, ai_canonname);
TM_k6kyf4Co79a84IkK9blFuQVA_0[18].typ = (&NTI_S9agCYBinaYZnGWcjTdxclg_);
TM_k6kyf4Co79a84IkK9blFuQVA_0[18].name = "ai_canonname";
TM_k6kyf4Co79a84IkK9blFuQVA_117[6] = &TM_k6kyf4Co79a84IkK9blFuQVA_0[19];
NTI_iPePZVyyc9cQV6V9cwz9ajG9bg_.size = sizeof(SOCKADDR);
NTI_iPePZVyyc9cQV6V9cwz9ajG9bg_.kind = 18;
NTI_iPePZVyyc9cQV6V9cwz9ajG9bg_.base = 0;
NTI_iPePZVyyc9cQV6V9cwz9ajG9bg_.flags = 3;
NTI_iPePZVyyc9cQV6V9cwz9ajG9bg_.node = &TM_k6kyf4Co79a84IkK9blFuQVA_0[20];
NTI_nBU9bsV5o5Xw80pGpGVR8Bw_.size = sizeof(SOCKADDR*);
NTI_nBU9bsV5o5Xw80pGpGVR8Bw_.kind = 21;
NTI_nBU9bsV5o5Xw80pGpGVR8Bw_.base = (&NTI_iPePZVyyc9cQV6V9cwz9ajG9bg_);
NTI_nBU9bsV5o5Xw80pGpGVR8Bw_.flags = 3;
TM_k6kyf4Co79a84IkK9blFuQVA_0[19].kind = 1;
TM_k6kyf4Co79a84IkK9blFuQVA_0[19].offset = offsetof(tyObject_AddrInfo_C9ahX3gj0cVjII4vjiaSHBQ, ai_addr);
TM_k6kyf4Co79a84IkK9blFuQVA_0[19].typ = (&NTI_nBU9bsV5o5Xw80pGpGVR8Bw_);
TM_k6kyf4Co79a84IkK9blFuQVA_0[19].name = "ai_addr";
TM_k6kyf4Co79a84IkK9blFuQVA_117[7] = &TM_k6kyf4Co79a84IkK9blFuQVA_0[21];
TM_k6kyf4Co79a84IkK9blFuQVA_0[21].kind = 1;
TM_k6kyf4Co79a84IkK9blFuQVA_0[21].offset = offsetof(tyObject_AddrInfo_C9ahX3gj0cVjII4vjiaSHBQ, ai_next);
TM_k6kyf4Co79a84IkK9blFuQVA_0[21].typ = (&NTI_9boVVq0W9aThvt3y6X6MODJQ_);
TM_k6kyf4Co79a84IkK9blFuQVA_0[21].name = "ai_next";
TM_k6kyf4Co79a84IkK9blFuQVA_0[12].len = 8; TM_k6kyf4Co79a84IkK9blFuQVA_0[12].kind = 2; TM_k6kyf4Co79a84IkK9blFuQVA_0[12].sons = &TM_k6kyf4Co79a84IkK9blFuQVA_117[0];
NTI_C9ahX3gj0cVjII4vjiaSHBQ_.node = &TM_k6kyf4Co79a84IkK9blFuQVA_0[12];
NTI_9boVVq0W9aThvt3y6X6MODJQ_.size = sizeof(tyObject_AddrInfo_C9ahX3gj0cVjII4vjiaSHBQ*);
NTI_9boVVq0W9aThvt3y6X6MODJQ_.kind = 21;
NTI_9boVVq0W9aThvt3y6X6MODJQ_.base = (&NTI_C9ahX3gj0cVjII4vjiaSHBQ_);
NTI_9boVVq0W9aThvt3y6X6MODJQ_.flags = 3;
if (!((TM_k6kyf4Co79a84IkK9blFuQVA_6 = nimLoadLibrary((NimStringDesc*) &TM_k6kyf4Co79a84IkK9blFuQVA_8))
)) nimLoadLibraryError((NimStringDesc*) &TM_k6kyf4Co79a84IkK9blFuQVA_9);
	Dl_133625_ = (tyProc_9bc9cLDdaqTE6n5J78feKRYg) nimGetProcAddr(TM_k6kyf4Co79a84IkK9blFuQVA_6, "GetSystemTimeAsFileTime");
	Dl_132630_ = (tyProc_9bXer9a4ps9aSGctILcxWReVw) nimGetProcAddr(TM_k6kyf4Co79a84IkK9blFuQVA_6, "GetLastError");
	Dl_132635_ = (tyProc_aO673xGTLLxou7P7GxoCXA) nimGetProcAddr(TM_k6kyf4Co79a84IkK9blFuQVA_6, "FormatMessageW");
	Dl_132801_ = (tyProc_im9buRnIvptJfzdASYMEbBA) nimGetProcAddr(TM_k6kyf4Co79a84IkK9blFuQVA_6, "LocalFree");
	Dl_133432_ = (tyProc_9cu0cWy2jNXKVhds9cs4T9a9cA) nimGetProcAddr(TM_k6kyf4Co79a84IkK9blFuQVA_6, "GetEnvironmentStringsW");
	Dl_133434_ = (tyProc_hayl9b1HhJokJ1Zo9ctoglPg) nimGetProcAddr(TM_k6kyf4Co79a84IkK9blFuQVA_6, "FreeEnvironmentStringsW");
	Dl_132818_ = (tyProc_IwsYs9blTXXmAlfsBWq604w) nimGetProcAddr(TM_k6kyf4Co79a84IkK9blFuQVA_6, "SetEnvironmentVariableW");
if (!((TM_k6kyf4Co79a84IkK9blFuQVA_24 = nimLoadLibrary((NimStringDesc*) &TM_k6kyf4Co79a84IkK9blFuQVA_26))
)) nimLoadLibraryError((NimStringDesc*) &TM_k6kyf4Co79a84IkK9blFuQVA_27);
	Dl_133999_ = (tyProc_9aO2cP4IgwjXF8JfUR57CHQ) nimGetProcAddr(TM_k6kyf4Co79a84IkK9blFuQVA_24, "socket");
	Dl_134004_ = (tyProc_IQbFr9cLT9bipWCXYfwYwjOw) nimGetProcAddr(TM_k6kyf4Co79a84IkK9blFuQVA_24, "closesocket");
	Dl_134014_ = (tyProc_T129bsPZ4FvuSF4rGFSBKkg) nimGetProcAddr(TM_k6kyf4Co79a84IkK9blFuQVA_24, "bind");
	Dl_134055_ = (tyProc_wy9bpl6t1mtPtDWeg0xLpDA) nimGetProcAddr(TM_k6kyf4Co79a84IkK9blFuQVA_24, "listen");
	Dl_134151_ = (tyProc_MvjKU9c5nvs0N3IrS4vNgSw) nimGetProcAddr(TM_k6kyf4Co79a84IkK9blFuQVA_24, "getaddrinfo");
	Dl_134160_ = (tyProc_IV3cwg4tBg3JP8ITSKt7oQ) nimGetProcAddr(TM_k6kyf4Co79a84IkK9blFuQVA_24, "freeaddrinfo");
	Dl_133974_ = (tyProc_E0SwAAX9bj9a9aV7n5MiMKzig) nimGetProcAddr(TM_k6kyf4Co79a84IkK9blFuQVA_24, "getservbyname");
	Dl_133979_ = (tyProc_M3E1eZF9azJd5WrGSHMqEDA) nimGetProcAddr(TM_k6kyf4Co79a84IkK9blFuQVA_24, "getservbyport");
	Dl_134113_ = (tyProc_jPIQsVcE09cbsdBUbAUxTCQ) nimGetProcAddr(TM_k6kyf4Co79a84IkK9blFuQVA_24, "inet_addr");
	Dl_133984_ = (tyProc_oU4d9cTB9cxBBS1maSQYgLMA) nimGetProcAddr(TM_k6kyf4Co79a84IkK9blFuQVA_24, "gethostbyaddr");
	Dl_133991_ = (tyProc_sUmKECsDIMWXpmy9a1Mqegg) nimGetProcAddr(TM_k6kyf4Co79a84IkK9blFuQVA_24, "gethostbyname");
	Dl_133995_ = (tyProc_7gdD6mJWQegUjarRikmB9bg) nimGetProcAddr(TM_k6kyf4Co79a84IkK9blFuQVA_24, "gethostname");
	Dl_134026_ = (tyProc_VXEvL0NvawmzSZzsbIHW6Q) nimGetProcAddr(TM_k6kyf4Co79a84IkK9blFuQVA_24, "getsockname");
	Dl_134164_ = (tyProc_MgrHyJlVVXQLRahsT9c14gQ) nimGetProcAddr(TM_k6kyf4Co79a84IkK9blFuQVA_24, "inet_ntoa");
	Dl_132325_ = (tyProc_pj29cW0AFVn7IRyIuHxtp9bw) nimGetProcAddr(TM_k6kyf4Co79a84IkK9blFuQVA_6, "GetVersionExW");
	Dl_134828_ = (tyProc_jT04OBqVwa9aMiCLMGHPMSg) nimGetProcAddr(TM_k6kyf4Co79a84IkK9blFuQVA_24, "WSAAddressToStringA");
	Dl_132632_ = (tyProc_Tjolzh1w2dIIpj3oCDGPFw) nimGetProcAddr(TM_k6kyf4Co79a84IkK9blFuQVA_6, "SetLastError");
	Dl_134033_ = (tyProc_VXEvL0NvawmzSZzsbIHW6Q) nimGetProcAddr(TM_k6kyf4Co79a84IkK9blFuQVA_24, "getpeername");
	Dl_134040_ = (tyProc_smMaEORdTTSo9bCzv0g049aQ) nimGetProcAddr(TM_k6kyf4Co79a84IkK9blFuQVA_24, "getsockopt");
	Dl_134048_ = (tyProc_K6tJduk9ckQgneh7oD8F4Bg) nimGetProcAddr(TM_k6kyf4Co79a84IkK9blFuQVA_24, "setsockopt");
	Dl_134116_ = (tyProc_8Py1tJvU9bm83KdBcpIBjeQ) nimGetProcAddr(TM_k6kyf4Co79a84IkK9blFuQVA_24, "__WSAFDIsSet");
	Dl_134075_ = (tyProc_rWrG4X5lbcXQyLNkF9aNWhQ) nimGetProcAddr(TM_k6kyf4Co79a84IkK9blFuQVA_24, "select");
	Dl_134007_ = (tyProc_v29cxQYDpNcYLQEZV01BR5g) nimGetProcAddr(TM_k6kyf4Co79a84IkK9blFuQVA_24, "accept");
	Dl_134146_ = (tyProc_As5z9bYt859cLKWaorPRgQYA) nimGetProcAddr(TM_k6kyf4Co79a84IkK9blFuQVA_24, "WSAStartup");
	Dl_134666_ = (tyProc_dh38EbgnCgluxaqYvYonAg) nimGetProcAddr(TM_k6kyf4Co79a84IkK9blFuQVA_6, "CreateIoCompletionPort");
	Dl_134672_ = (tyProc_JIaVmlkaszRmqoQwQevY9aA) nimGetProcAddr(TM_k6kyf4Co79a84IkK9blFuQVA_6, "GetQueuedCompletionStatus");
	Dl_134732_ = (tyProc_m8OtNuKklv1X2vQjXQkzSA) nimGetProcAddr(TM_k6kyf4Co79a84IkK9blFuQVA_24, "WSAIoctl");
	Dl_134747_ = (tyProc_EzSr684Zq8WJvaKasuLSqQ) nimGetProcAddr(TM_k6kyf4Co79a84IkK9blFuQVA_24, "WSARecv");
	Dl_134771_ = (tyProc_kfyUyr89bETC8vA9b9aJWaMyQ) nimGetProcAddr(TM_k6kyf4Co79a84IkK9blFuQVA_24, "WSASend");
	Dl_134781_ = (tyProc_IaLzHXnYXlJtUwTTdxZCkg) nimGetProcAddr(TM_k6kyf4Co79a84IkK9blFuQVA_24, "WSASendTo");
	Dl_134757_ = (tyProc_3O4G0IBJdJZ47y0NhcqSGA) nimGetProcAddr(TM_k6kyf4Co79a84IkK9blFuQVA_24, "WSARecvFrom");
	Dl_135120_ = (tyProc_y9bTZn8f8ZZ0xDJI0xhgy9bA) nimGetProcAddr(TM_k6kyf4Co79a84IkK9blFuQVA_6, "PostQueuedCompletionStatus");
if (!((TM_k6kyf4Co79a84IkK9blFuQVA_95 = nimLoadLibrary((NimStringDesc*) &TM_k6kyf4Co79a84IkK9blFuQVA_97))
)) nimLoadLibraryError((NimStringDesc*) &TM_k6kyf4Co79a84IkK9blFuQVA_98);
	Dl_135220_ = (tyProc_uryidYWkntM7ddjZSyxvyQ) nimGetProcAddr(TM_k6kyf4Co79a84IkK9blFuQVA_95, "WSACreateEvent");
	Dl_135135_ = (tyProc_P13srMBg9b3d3yEV9aW4NCoA) nimGetProcAddr(TM_k6kyf4Co79a84IkK9blFuQVA_6, "UnregisterWait");
	Dl_135222_ = (tyProc_f8UTDN69a9cIlDrZoYnegfKw) nimGetProcAddr(TM_k6kyf4Co79a84IkK9blFuQVA_95, "WSACloseEvent");
	Dl_135126_ = (tyProc_JxCafHu7hLn8yfng3Vh3tw) nimGetProcAddr(TM_k6kyf4Co79a84IkK9blFuQVA_6, "RegisterWaitForSingleObject");
	Dl_135215_ = (tyProc_gwfiiqaid9a9cPS02MkvDQZw) nimGetProcAddr(TM_k6kyf4Co79a84IkK9blFuQVA_95, "WSAEventSelect");
	Dl_135143_ = (tyProc_c1mlTHJvlrhsAf26W9cqx8Q) nimGetProcAddr(TM_k6kyf4Co79a84IkK9blFuQVA_6, "CreateEventW");
	Dl_132403_ = (tyProc_P13srMBg9b3d3yEV9aW4NCoA) nimGetProcAddr(TM_k6kyf4Co79a84IkK9blFuQVA_6, "CloseHandle");
	Dl_135138_ = (tyProc_OsjIMZiv5zpV9a3Ct7Sk2Uw) nimGetProcAddr(TM_k6kyf4Co79a84IkK9blFuQVA_6, "OpenProcess");
	Dl_135201_ = (tyProc_IQbFr9cLT9bipWCXYfwYwjOw) nimGetProcAddr(TM_k6kyf4Co79a84IkK9blFuQVA_6, "SetEvent");
	Dl_134084_ = (tyProc_4YBDaTH9b4xNNXSV9ahdJZ8w) nimGetProcAddr(TM_k6kyf4Co79a84IkK9blFuQVA_24, "send");
	Dl_134059_ = (tyProc_4YBDaTH9b4xNNXSV9ahdJZ8w) nimGetProcAddr(TM_k6kyf4Co79a84IkK9blFuQVA_24, "recv");
	Dl_134020_ = (tyProc_T129bsPZ4FvuSF4rGFSBKkg) nimGetProcAddr(TM_k6kyf4Co79a84IkK9blFuQVA_24, "connect");
	Dl_133238_ = (tyProc_RG83qWQtsxfLxD7HYoLyfA) nimGetProcAddr(TM_k6kyf4Co79a84IkK9blFuQVA_6, "FindFirstFileW");
	Dl_133401_ = (tyProc_ofoySXaAAlxxs9bQS9a1etlg) nimGetProcAddr(TM_k6kyf4Co79a84IkK9blFuQVA_6, "FindClose");
	Dl_133243_ = (tyProc_jwEWAkul5J6p6K0UfXa1tw) nimGetProcAddr(TM_k6kyf4Co79a84IkK9blFuQVA_6, "FindNextFileW");
	Dl_133437_ = (tyProc_9cu0cWy2jNXKVhds9cs4T9a9cA) nimGetProcAddr(TM_k6kyf4Co79a84IkK9blFuQVA_6, "GetCommandLineW");
}

