/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -O3 -fno-strict-aliasing  -I/root/.choosenim/toolchains/nim-0.18.0/lib -o /mnt/d/Development/bitbucket/java/NetScoutMerger/script/lsrreport/nimcache/stdlib_strtabs.o /mnt/d/Development/bitbucket/java/NetScoutMerger/script/lsrreport/nimcache/stdlib_strtabs.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tyObject_StringTableObj_DKRIdH9c9cKI7YpQb9c0wKlEw tyObject_StringTableObj_DKRIdH9c9cKI7YpQb9c0wKlEw;
typedef struct RootObj RootObj;
typedef struct tySequence_4eQHGndY6XBYpFOH09apV8Q tySequence_4eQHGndY6XBYpFOH09apV8Q;
typedef struct tyTuple_UV3llMMYFckfui8YMBuUZA tyTuple_UV3llMMYFckfui8YMBuUZA;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack_7fytPA5bBsob6See21YMRA tyObject_GcStack_7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyTuple_ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg;
typedef struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w;
typedef struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ;
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct RootObj {
TNimType* m_type;
};
typedef NU8 tyEnum_StringTableMode_G9c4wVDFIzf0xHmQvxso9a9cQ;
struct tyObject_StringTableObj_DKRIdH9c9cKI7YpQb9c0wKlEw {
  RootObj Sup;
NI counter;
tySequence_4eQHGndY6XBYpFOH09apV8Q* data;
tyEnum_StringTableMode_G9c4wVDFIzf0xHmQvxso9a9cQ mode;
};
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct tyTuple_UV3llMMYFckfui8YMBuUZA {
NimStringDesc* Field0;
NimStringDesc* Field1;
};
struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack_7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* tyArray_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef NU32 tyArray_BHbOSqU1t9b3Gt7K2c6fQig[24];
typedef tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* tyArray_N1u1nqOgmuJN9cSZrnMHgOQ[32];
typedef tyArray_N1u1nqOgmuJN9cSZrnMHgOQ tyArray_B6durA4ZCi1xjJvRtyYxMg[24];
typedef tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* tyArray_lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA {
tyArray_lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* tyArray_0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw {
tyArray_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyArray_LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray_LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray_SiRwrEKZdLgxqz9a9aoVBglg freeSmallChunks;
NU32 flBitmap;
tyArray_BHbOSqU1t9b3Gt7K2c6fQig slBitmap;
tyArray_B6durA4ZCi1xjJvRtyYxMg matrix;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI occ;
NI lastSize;
tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack_7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w additionalRoots;
NI gcThreadId;
};
struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w {
NI prevSize;
NI size;
};
struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* next;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* prev;
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* freeList;
NI free;
NI acc;
NF data;
};
struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* next;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* prev;
NF data;
};
struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw {
NI size;
NI acc;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* next;
};
typedef NI tyArray_9a8QARi5WsUggNU9bom7kzTQ[8];
struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw {
tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg {
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ {
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* next;
NI zeroField;
};
struct tySequence_4eQHGndY6XBYpFOH09apV8Q {
  TGenericSeq Sup;
  tyTuple_UV3llMMYFckfui8YMBuUZA data[SEQ_DECL_SIZE];
};
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, Marker_tySequence_4eQHGndY6XBYpFOH09apV8Q)(void* p, NI op);
static N_NIMCALL(void, Marker_tyRef_pkhT5bYRU9ayIZ9cBuuCx4Xw)(void* p, NI op);
N_LIB_PRIVATE N_NIMCALL(tyObject_StringTableObj_DKRIdH9c9cKI7YpQb9c0wKlEw*, nstnewStringTable)(tyEnum_StringTableMode_G9c4wVDFIzf0xHmQvxso9a9cQ mode);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr);
static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NOINLINE(void, addZCT_fCDI7oO1NNVXXURtxSzsRw)(tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_NIMCALL(void*, newSeqRC1)(TNimType* typ, NI len);
N_LIB_PRIVATE N_NIMCALL(void, nstPut)(tyObject_StringTableObj_DKRIdH9c9cKI7YpQb9c0wKlEw* t, NimStringDesc* key, NimStringDesc* val);
N_LIB_PRIVATE N_NIMCALL(NI, rawGet_g4UMXDeIi4hi42WuIY9cM4A)(tyObject_StringTableObj_DKRIdH9c9cKI7YpQb9c0wKlEw* t, NimStringDesc* key);
N_LIB_PRIVATE N_NIMCALL(NI, myhash_g4UMXDeIi4hi42WuIY9cM4A_2)(tyObject_StringTableObj_DKRIdH9c9cKI7YpQb9c0wKlEw* t, NimStringDesc* key);
N_LIB_PRIVATE N_NIMCALL(NI, hash_uBstFm5SYVQeOL3j9c9bc58A)(NimStringDesc* x);
N_LIB_PRIVATE N_NIMCALL(NI, hashIgnoreCase_uBstFm5SYVQeOL3j9c9bc58A_2)(NimStringDesc* x);
N_LIB_PRIVATE N_NIMCALL(NI, hashIgnoreStyle_uBstFm5SYVQeOL3j9c9bc58A_3)(NimStringDesc* x);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, myCmp_6dqTqYQ9cC63hkWdN9br54EA)(tyObject_StringTableObj_DKRIdH9c9cKI7YpQb9c0wKlEw* t, NimStringDesc* a, NimStringDesc* b);
N_LIB_PRIVATE N_NIMCALL(NI, cmp_xEnKsp9cfvO7Do9cTYXo8eJw)(NimStringDesc* x, NimStringDesc* y);
N_LIB_PRIVATE N_NIMCALL(NI, nsuCmpIgnoreCase)(NimStringDesc* a, NimStringDesc* b);
N_LIB_PRIVATE N_NIMCALL(NI, nsuCmpIgnoreStyle)(NimStringDesc* a, NimStringDesc* b);
static N_INLINE(NI, nextTry_4tI2vxIqcy1tNTBufKNbkgstrtabs)(NI h, NI maxHash);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, mustRehash_K02IbeDTRFZ9b4m0M4Kahlg)(NI length, NI counter);
N_LIB_PRIVATE N_NIMCALL(void, enlarge_1rn449bBULy9cLwCWr7ISAqg)(tyObject_StringTableObj_DKRIdH9c9cKI7YpQb9c0wKlEw* t);
N_NIMCALL(void*, newSeq)(TNimType* typ, NI len);
N_LIB_PRIVATE N_NIMCALL(void, rawInsert_YkqIveHDR3SuLUhxpyZbuQ)(tyObject_StringTableObj_DKRIdH9c9cKI7YpQb9c0wKlEw* t, tySequence_4eQHGndY6XBYpFOH09apV8Q** data, NimStringDesc* key, NimStringDesc* val);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
extern TNimType NTI_13RNkKqUOX1TtorOUlKtqA_;
TNimType NTI_DKRIdH9c9cKI7YpQb9c0wKlEw_;
extern TNimType NTI_rR5Bzr1D5krxoo1NcNyeMA_;
TNimType NTI_UV3llMMYFckfui8YMBuUZA_;
extern TNimType NTI_77mFvmsOLKik79ci2hXkHEg_;
TNimType NTI_4eQHGndY6XBYpFOH09apV8Q_;
TNimType NTI_G9c4wVDFIzf0xHmQvxso9a9cQ_;
TNimType NTI_pkhT5bYRU9ayIZ9cBuuCx4Xw_;
extern tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
static N_NIMCALL(void, Marker_tySequence_4eQHGndY6XBYpFOH09apV8Q)(void* p, NI op) {
	tySequence_4eQHGndY6XBYpFOH09apV8Q* a;
	NI T1_;
	a = (tySequence_4eQHGndY6XBYpFOH09apV8Q*)p;
	T1_ = (NI)0;
	for (T1_ = 0; T1_ < a->Sup.len; T1_++) {
	nimGCvisit((void*)a->data[T1_].Field0, op);
	nimGCvisit((void*)a->data[T1_].Field1, op);
	}
}
static N_NIMCALL(void, Marker_tyRef_pkhT5bYRU9ayIZ9cBuuCx4Xw)(void* p, NI op) {
	tyObject_StringTableObj_DKRIdH9c9cKI7YpQb9c0wKlEw* a;
	a = (tyObject_StringTableObj_DKRIdH9c9cKI7YpQb9c0wKlEw*)p;
	nimGCvisit((void*)(*a).data, op);
}

static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* result;
	result = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	result = ((tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*) ((NI)((NU64)(((NI) (ptrdiff_t) (usr))) - (NU64)(((NI)sizeof(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g))))));
	return result;
}

static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	addZCT_fCDI7oO1NNVXXURtxSzsRw((&gch_IcYaEuuWivYAS86vFMTS3Q.zct), c);
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
	c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(p);
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_StringTableObj_DKRIdH9c9cKI7YpQb9c0wKlEw*, nstnewStringTable)(tyEnum_StringTableMode_G9c4wVDFIzf0xHmQvxso9a9cQ mode) {
	tyObject_StringTableObj_DKRIdH9c9cKI7YpQb9c0wKlEw* result;
	result = (tyObject_StringTableObj_DKRIdH9c9cKI7YpQb9c0wKlEw*)0;
	result = (tyObject_StringTableObj_DKRIdH9c9cKI7YpQb9c0wKlEw*) newObj((&NTI_pkhT5bYRU9ayIZ9cBuuCx4Xw_), sizeof(tyObject_StringTableObj_DKRIdH9c9cKI7YpQb9c0wKlEw));
	(*result).Sup.m_type = (&NTI_DKRIdH9c9cKI7YpQb9c0wKlEw_);
	(*result).mode = mode;
	(*result).counter = ((NI) 0);
	if ((*result).data) { nimGCunrefNoCycle((*result).data); (*result).data = NIM_NIL; }
	(*result).data = (tySequence_4eQHGndY6XBYpFOH09apV8Q*) newSeqRC1((&NTI_4eQHGndY6XBYpFOH09apV8Q_), ((NI) 64));
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NI, myhash_g4UMXDeIi4hi42WuIY9cM4A_2)(tyObject_StringTableObj_DKRIdH9c9cKI7YpQb9c0wKlEw* t, NimStringDesc* key) {
	NI result;
	result = (NI)0;
	switch ((*t).mode) {
	case ((tyEnum_StringTableMode_G9c4wVDFIzf0xHmQvxso9a9cQ) 0):
	{
		result = hash_uBstFm5SYVQeOL3j9c9bc58A(key);
	}
	break;
	case ((tyEnum_StringTableMode_G9c4wVDFIzf0xHmQvxso9a9cQ) 1):
	{
		result = hashIgnoreCase_uBstFm5SYVQeOL3j9c9bc58A_2(key);
	}
	break;
	case ((tyEnum_StringTableMode_G9c4wVDFIzf0xHmQvxso9a9cQ) 2):
	{
		result = hashIgnoreStyle_uBstFm5SYVQeOL3j9c9bc58A_3(key);
	}
	break;
	}
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, myCmp_6dqTqYQ9cC63hkWdN9br54EA)(tyObject_StringTableObj_DKRIdH9c9cKI7YpQb9c0wKlEw* t, NimStringDesc* a, NimStringDesc* b) {
	NIM_BOOL result;
	result = (NIM_BOOL)0;
	switch ((*t).mode) {
	case ((tyEnum_StringTableMode_G9c4wVDFIzf0xHmQvxso9a9cQ) 0):
	{
		NI T2_;
		T2_ = (NI)0;
		T2_ = cmp_xEnKsp9cfvO7Do9cTYXo8eJw(a, b);
		result = (T2_ == ((NI) 0));
	}
	break;
	case ((tyEnum_StringTableMode_G9c4wVDFIzf0xHmQvxso9a9cQ) 1):
	{
		NI T4_;
		T4_ = (NI)0;
		T4_ = nsuCmpIgnoreCase(a, b);
		result = (T4_ == ((NI) 0));
	}
	break;
	case ((tyEnum_StringTableMode_G9c4wVDFIzf0xHmQvxso9a9cQ) 2):
	{
		NI T6_;
		T6_ = (NI)0;
		T6_ = nsuCmpIgnoreStyle(a, b);
		result = (T6_ == ((NI) 0));
	}
	break;
	}
	return result;
}

static N_INLINE(NI, nextTry_4tI2vxIqcy1tNTBufKNbkgstrtabs)(NI h, NI maxHash) {
	NI result;
	result = (NI)0;
	result = (NI)((NI)((NI)(((NI) 5) * h) + ((NI) 1)) & maxHash);
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NI, rawGet_g4UMXDeIi4hi42WuIY9cM4A)(tyObject_StringTableObj_DKRIdH9c9cKI7YpQb9c0wKlEw* t, NimStringDesc* key) {
	NI result;
	NI h;
	NI T1_;
	NI T2_;
{	result = (NI)0;
	T1_ = (NI)0;
	T1_ = myhash_g4UMXDeIi4hi42WuIY9cM4A_2(t, key);
	T2_ = ((*t).data ? ((*t).data->Sup.len-1) : -1);
	h = (NI)(T1_ & T2_);
	{
		while (1) {
			NI T10_;
			if (!!(((*t).data->data[h].Field0 == 0))) goto LA4;
			{
				NIM_BOOL T7_;
				T7_ = (NIM_BOOL)0;
				T7_ = myCmp_6dqTqYQ9cC63hkWdN9br54EA(t, (*t).data->data[h].Field0, key);
				if (!T7_) goto LA8_;
				result = h;
				goto BeforeRet_;
			}
			LA8_: ;
			T10_ = ((*t).data ? ((*t).data->Sup.len-1) : -1);
			h = nextTry_4tI2vxIqcy1tNTBufKNbkgstrtabs(h, T10_);
		} LA4: ;
	}
	result = ((NI) -1);
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, mustRehash_K02IbeDTRFZ9b4m0M4Kahlg)(NI length, NI counter) {
	NIM_BOOL result;
	NIM_BOOL T1_;
	result = (NIM_BOOL)0;
	T1_ = (NIM_BOOL)0;
	T1_ = ((NI)(length * ((NI) 2)) < (NI)(counter * ((NI) 3)));
	if (T1_) goto LA2_;
	T1_ = ((NI)(length - counter) < ((NI) 4));
	LA2_: ;
	result = T1_;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, rawInsert_YkqIveHDR3SuLUhxpyZbuQ)(tyObject_StringTableObj_DKRIdH9c9cKI7YpQb9c0wKlEw* t, tySequence_4eQHGndY6XBYpFOH09apV8Q** data, NimStringDesc* key, NimStringDesc* val) {
	NI h;
	NI T1_;
	NI T2_;
	NimStringDesc* T6_;
	NimStringDesc* T7_;
	T1_ = (NI)0;
	T1_ = myhash_g4UMXDeIi4hi42WuIY9cM4A_2(t, key);
	T2_ = ((*data) ? ((*data)->Sup.len-1) : -1);
	h = (NI)(T1_ & T2_);
	{
		while (1) {
			NI T5_;
			if (!!(((*data)->data[h].Field0 == 0))) goto LA4;
			T5_ = ((*data) ? ((*data)->Sup.len-1) : -1);
			h = nextTry_4tI2vxIqcy1tNTBufKNbkgstrtabs(h, T5_);
		} LA4: ;
	}
	T6_ = (NimStringDesc*)0;
	T6_ = (*data)->data[h].Field0; (*data)->data[h].Field0 = copyStringRC1(key);
	if (T6_) nimGCunrefNoCycle(T6_);
	T7_ = (NimStringDesc*)0;
	T7_ = (*data)->data[h].Field1; (*data)->data[h].Field1 = copyStringRC1(val);
	if (T7_) nimGCunrefNoCycle(T7_);
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
		if (!!((src == NIM_NIL))) goto LA3_;
		c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		(*c).refcount += ((NI) 8);
	}
	LA3_: ;
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c_2;
		if (!!(((*dest) == NIM_NIL))) goto LA7_;
		c_2 = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		{
			(*c_2).refcount -= ((NI) 8);
			if (!((NU64)((*c_2).refcount) < (NU64)(((NI) 8)))) goto LA11_;
			rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c_2);
		}
		LA11_: ;
	}
	LA7_: ;
	(*dest) = src;
}

N_LIB_PRIVATE N_NIMCALL(void, enlarge_1rn449bBULy9cLwCWr7ISAqg)(tyObject_StringTableObj_DKRIdH9c9cKI7YpQb9c0wKlEw* t) {
	tySequence_4eQHGndY6XBYpFOH09apV8Q* n;
	NI T1_;
	tySequence_4eQHGndY6XBYpFOH09apV8Q* T10_;
	n = (tySequence_4eQHGndY6XBYpFOH09apV8Q*)0;
	T1_ = ((*t).data ? (*t).data->Sup.len : 0);
	n = (tySequence_4eQHGndY6XBYpFOH09apV8Q*) newSeq((&NTI_4eQHGndY6XBYpFOH09apV8Q_), ((NI) ((NI)(T1_ * ((NI) 2)))));
	{
		NI i;
		NI colontmp_;
		NI T3_;
		NI res;
		i = (NI)0;
		colontmp_ = (NI)0;
		T3_ = ((*t).data ? ((*t).data->Sup.len-1) : -1);
		colontmp_ = T3_;
		res = ((NI) 0);
		{
			while (1) {
				if (!(res <= colontmp_)) goto LA5;
				i = res;
				{
					if (!!(((*t).data->data[i].Field0 == 0))) goto LA8_;
					rawInsert_YkqIveHDR3SuLUhxpyZbuQ(t, (&n), (*t).data->data[i].Field0, (*t).data->data[i].Field1);
				}
				LA8_: ;
				res += ((NI) 1);
			} LA5: ;
		}
	}
	T10_ = (tySequence_4eQHGndY6XBYpFOH09apV8Q*)0;
	T10_ = (*t).data;
	asgnRefNoCycle((void**) (&(*t).data), n);
	n = T10_;
}

N_LIB_PRIVATE N_NIMCALL(void, nstPut)(tyObject_StringTableObj_DKRIdH9c9cKI7YpQb9c0wKlEw* t, NimStringDesc* key, NimStringDesc* val) {
	NI index;
	index = rawGet_g4UMXDeIi4hi42WuIY9cM4A(t, key);
	{
		NimStringDesc* T5_;
		if (!(((NI) 0) <= index)) goto LA3_;
		T5_ = (NimStringDesc*)0;
		T5_ = (*t).data->data[index].Field1; (*t).data->data[index].Field1 = copyStringRC1(val);
		if (T5_) nimGCunrefNoCycle(T5_);
	}
	goto LA1_;
	LA3_: ;
	{
		{
			NI T9_;
			NIM_BOOL T10_;
			T9_ = ((*t).data ? (*t).data->Sup.len : 0);
			T10_ = (NIM_BOOL)0;
			T10_ = mustRehash_K02IbeDTRFZ9b4m0M4Kahlg(T9_, (*t).counter);
			if (!T10_) goto LA11_;
			enlarge_1rn449bBULy9cLwCWr7ISAqg(t);
		}
		LA11_: ;
		rawInsert_YkqIveHDR3SuLUhxpyZbuQ(t, (&(*t).data), key, val);
		(*t).counter += ((NI) 1);
	}
	LA1_: ;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_StringTableObj_DKRIdH9c9cKI7YpQb9c0wKlEw*, nstnewStringTableWithTableConstr)(tyTuple_UV3llMMYFckfui8YMBuUZA* keyValuePairs, NI keyValuePairsLen_0, tyEnum_StringTableMode_G9c4wVDFIzf0xHmQvxso9a9cQ mode) {
	tyObject_StringTableObj_DKRIdH9c9cKI7YpQb9c0wKlEw* result;
	result = (tyObject_StringTableObj_DKRIdH9c9cKI7YpQb9c0wKlEw*)0;
	result = nstnewStringTable(mode);
	{
		NimStringDesc* key;
		NimStringDesc* val;
		NI i;
		key = (NimStringDesc*)0;
		val = (NimStringDesc*)0;
		i = ((NI) 0);
		{
			while (1) {
				if (!(i < keyValuePairsLen_0)) goto LA3;
				key = keyValuePairs[i].Field0;
				val = keyValuePairs[i].Field1;
				nstPut(result, key, val);
				i += ((NI) 1);
			} LA3: ;
		}
	}
	return result;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_strtabsInit000)(void) {
}

NIM_EXTERNC N_NOINLINE(void, stdlib_strtabsDatInit000)(void) {
static TNimNode* TM_ZT9crccxweoChVXn9cHcxIXQ_2[3];
static TNimNode* TM_ZT9crccxweoChVXn9cHcxIXQ_3[2];
static TNimNode* TM_ZT9crccxweoChVXn9cHcxIXQ_4[3];
NI TM_ZT9crccxweoChVXn9cHcxIXQ_6;
static char* NIM_CONST TM_ZT9crccxweoChVXn9cHcxIXQ_5[3] = {
"modeCaseSensitive", 
"modeCaseInsensitive", 
"modeStyleInsensitive"};
static TNimNode TM_ZT9crccxweoChVXn9cHcxIXQ_0[11];
NTI_DKRIdH9c9cKI7YpQb9c0wKlEw_.size = sizeof(tyObject_StringTableObj_DKRIdH9c9cKI7YpQb9c0wKlEw);
NTI_DKRIdH9c9cKI7YpQb9c0wKlEw_.kind = 17;
NTI_DKRIdH9c9cKI7YpQb9c0wKlEw_.base = (&NTI_13RNkKqUOX1TtorOUlKtqA_);
TM_ZT9crccxweoChVXn9cHcxIXQ_2[0] = &TM_ZT9crccxweoChVXn9cHcxIXQ_0[1];
TM_ZT9crccxweoChVXn9cHcxIXQ_0[1].kind = 1;
TM_ZT9crccxweoChVXn9cHcxIXQ_0[1].offset = offsetof(tyObject_StringTableObj_DKRIdH9c9cKI7YpQb9c0wKlEw, counter);
TM_ZT9crccxweoChVXn9cHcxIXQ_0[1].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_ZT9crccxweoChVXn9cHcxIXQ_0[1].name = "counter";
TM_ZT9crccxweoChVXn9cHcxIXQ_2[1] = &TM_ZT9crccxweoChVXn9cHcxIXQ_0[2];
NTI_UV3llMMYFckfui8YMBuUZA_.size = sizeof(tyTuple_UV3llMMYFckfui8YMBuUZA);
NTI_UV3llMMYFckfui8YMBuUZA_.kind = 18;
NTI_UV3llMMYFckfui8YMBuUZA_.base = 0;
NTI_UV3llMMYFckfui8YMBuUZA_.flags = 2;
TM_ZT9crccxweoChVXn9cHcxIXQ_3[0] = &TM_ZT9crccxweoChVXn9cHcxIXQ_0[4];
TM_ZT9crccxweoChVXn9cHcxIXQ_0[4].kind = 1;
TM_ZT9crccxweoChVXn9cHcxIXQ_0[4].offset = offsetof(tyTuple_UV3llMMYFckfui8YMBuUZA, Field0);
TM_ZT9crccxweoChVXn9cHcxIXQ_0[4].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_ZT9crccxweoChVXn9cHcxIXQ_0[4].name = "Field0";
TM_ZT9crccxweoChVXn9cHcxIXQ_3[1] = &TM_ZT9crccxweoChVXn9cHcxIXQ_0[5];
TM_ZT9crccxweoChVXn9cHcxIXQ_0[5].kind = 1;
TM_ZT9crccxweoChVXn9cHcxIXQ_0[5].offset = offsetof(tyTuple_UV3llMMYFckfui8YMBuUZA, Field1);
TM_ZT9crccxweoChVXn9cHcxIXQ_0[5].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_ZT9crccxweoChVXn9cHcxIXQ_0[5].name = "Field1";
TM_ZT9crccxweoChVXn9cHcxIXQ_0[3].len = 2; TM_ZT9crccxweoChVXn9cHcxIXQ_0[3].kind = 2; TM_ZT9crccxweoChVXn9cHcxIXQ_0[3].sons = &TM_ZT9crccxweoChVXn9cHcxIXQ_3[0];
NTI_UV3llMMYFckfui8YMBuUZA_.node = &TM_ZT9crccxweoChVXn9cHcxIXQ_0[3];
NTI_4eQHGndY6XBYpFOH09apV8Q_.size = sizeof(tySequence_4eQHGndY6XBYpFOH09apV8Q*);
NTI_4eQHGndY6XBYpFOH09apV8Q_.kind = 24;
NTI_4eQHGndY6XBYpFOH09apV8Q_.base = (&NTI_UV3llMMYFckfui8YMBuUZA_);
NTI_4eQHGndY6XBYpFOH09apV8Q_.flags = 2;
NTI_4eQHGndY6XBYpFOH09apV8Q_.marker = Marker_tySequence_4eQHGndY6XBYpFOH09apV8Q;
TM_ZT9crccxweoChVXn9cHcxIXQ_0[2].kind = 1;
TM_ZT9crccxweoChVXn9cHcxIXQ_0[2].offset = offsetof(tyObject_StringTableObj_DKRIdH9c9cKI7YpQb9c0wKlEw, data);
TM_ZT9crccxweoChVXn9cHcxIXQ_0[2].typ = (&NTI_4eQHGndY6XBYpFOH09apV8Q_);
TM_ZT9crccxweoChVXn9cHcxIXQ_0[2].name = "data";
TM_ZT9crccxweoChVXn9cHcxIXQ_2[2] = &TM_ZT9crccxweoChVXn9cHcxIXQ_0[6];
NTI_G9c4wVDFIzf0xHmQvxso9a9cQ_.size = sizeof(tyEnum_StringTableMode_G9c4wVDFIzf0xHmQvxso9a9cQ);
NTI_G9c4wVDFIzf0xHmQvxso9a9cQ_.kind = 14;
NTI_G9c4wVDFIzf0xHmQvxso9a9cQ_.base = 0;
NTI_G9c4wVDFIzf0xHmQvxso9a9cQ_.flags = 3;
for (TM_ZT9crccxweoChVXn9cHcxIXQ_6 = 0; TM_ZT9crccxweoChVXn9cHcxIXQ_6 < 3; TM_ZT9crccxweoChVXn9cHcxIXQ_6++) {
TM_ZT9crccxweoChVXn9cHcxIXQ_0[TM_ZT9crccxweoChVXn9cHcxIXQ_6+7].kind = 1;
TM_ZT9crccxweoChVXn9cHcxIXQ_0[TM_ZT9crccxweoChVXn9cHcxIXQ_6+7].offset = TM_ZT9crccxweoChVXn9cHcxIXQ_6;
TM_ZT9crccxweoChVXn9cHcxIXQ_0[TM_ZT9crccxweoChVXn9cHcxIXQ_6+7].name = TM_ZT9crccxweoChVXn9cHcxIXQ_5[TM_ZT9crccxweoChVXn9cHcxIXQ_6];
TM_ZT9crccxweoChVXn9cHcxIXQ_4[TM_ZT9crccxweoChVXn9cHcxIXQ_6] = &TM_ZT9crccxweoChVXn9cHcxIXQ_0[TM_ZT9crccxweoChVXn9cHcxIXQ_6+7];
}
TM_ZT9crccxweoChVXn9cHcxIXQ_0[10].len = 3; TM_ZT9crccxweoChVXn9cHcxIXQ_0[10].kind = 2; TM_ZT9crccxweoChVXn9cHcxIXQ_0[10].sons = &TM_ZT9crccxweoChVXn9cHcxIXQ_4[0];
NTI_G9c4wVDFIzf0xHmQvxso9a9cQ_.node = &TM_ZT9crccxweoChVXn9cHcxIXQ_0[10];
TM_ZT9crccxweoChVXn9cHcxIXQ_0[6].kind = 1;
TM_ZT9crccxweoChVXn9cHcxIXQ_0[6].offset = offsetof(tyObject_StringTableObj_DKRIdH9c9cKI7YpQb9c0wKlEw, mode);
TM_ZT9crccxweoChVXn9cHcxIXQ_0[6].typ = (&NTI_G9c4wVDFIzf0xHmQvxso9a9cQ_);
TM_ZT9crccxweoChVXn9cHcxIXQ_0[6].name = "mode";
TM_ZT9crccxweoChVXn9cHcxIXQ_0[0].len = 3; TM_ZT9crccxweoChVXn9cHcxIXQ_0[0].kind = 2; TM_ZT9crccxweoChVXn9cHcxIXQ_0[0].sons = &TM_ZT9crccxweoChVXn9cHcxIXQ_2[0];
NTI_DKRIdH9c9cKI7YpQb9c0wKlEw_.node = &TM_ZT9crccxweoChVXn9cHcxIXQ_0[0];
NTI_pkhT5bYRU9ayIZ9cBuuCx4Xw_.size = sizeof(tyObject_StringTableObj_DKRIdH9c9cKI7YpQb9c0wKlEw*);
NTI_pkhT5bYRU9ayIZ9cBuuCx4Xw_.kind = 22;
NTI_pkhT5bYRU9ayIZ9cBuuCx4Xw_.base = (&NTI_DKRIdH9c9cKI7YpQb9c0wKlEw_);
NTI_pkhT5bYRU9ayIZ9cBuuCx4Xw_.marker = Marker_tyRef_pkhT5bYRU9ayIZ9cBuuCx4Xw;
}

