/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -O3 -fno-strict-aliasing  -I/root/.choosenim/toolchains/nim-0.18.0/lib -o /mnt/d/Development/bitbucket/java/NetScoutMerger/script/lsrreport/nimcache/stdlib_net.o /mnt/d/Development/bitbucket/java/NetScoutMerger/script/lsrreport/nimcache/stdlib_net.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <sys/socket.h>
#include <netdb.h>
#include <string.h>
#include <setjmp.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tyObject_SocketImpl_aIhANOOoETolVz9cccNO9cRQ tyObject_SocketImpl_aIhANOOoETolVz9cccNO9cRQ;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tyObject_TimeoutError_FsA9cqNuEA9c2lfCA9bcCRasw tyObject_TimeoutError_FsA9cqNuEA9c2lfCA9bcCRasw;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct tySequence_uB9b75OUPRENsBAu4AnoePA tySequence_uB9b75OUPRENsBAu4AnoePA;
typedef struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack_7fytPA5bBsob6See21YMRA tyObject_GcStack_7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyTuple_ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg;
typedef struct tySequence_9apztJSmgERYU8fZOjI4pOg tySequence_9apztJSmgERYU8fZOjI4pOg;
typedef struct TSafePoint TSafePoint;
typedef struct tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA;
typedef struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w;
typedef struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ;
typedef NIM_CHAR tyArray_QQGLPNVVwLhYjkngqAxXQQ[4001];
typedef NU8 tyEnum_Domain_Q79bEtFARvq0ekDNtvj3Vqg;
typedef NU8 tyEnum_SockType_NQT1bItGG2X9byGdrWX7ujw;
typedef NU8 tyEnum_Protocol_dqJ1OqRGclxIMMdSLRzzXg;
struct tyObject_SocketImpl_aIhANOOoETolVz9cccNO9cRQ {
int fd;
NIM_BOOL isBuffered;
union{
struct {tyArray_QQGLPNVVwLhYjkngqAxXQQ buffer;
NI currPos;
NI bufLen;
} S1;
} isBufferedU;
NI32 lastError;
tyEnum_Domain_Q79bEtFARvq0ekDNtvj3Vqg domain;
tyEnum_SockType_NQT1bItGG2X9byGdrWX7ujw sockType;
tyEnum_Protocol_dqJ1OqRGclxIMMdSLRzzXg protocol;
};
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NU8 tySet_tyEnum_SocketFlag_4xio0cAXR7XG4pF9bVcpxEg;
struct RootObj {
TNimType* m_type;
};
struct Exception {
  RootObj Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
tySequence_uB9b75OUPRENsBAu4AnoePA* trace;
Exception* up;
};
struct tyObject_TimeoutError_FsA9cqNuEA9c2lfCA9bcCRasw {
  Exception Sup;
};
struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack_7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* tyArray_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef NU32 tyArray_BHbOSqU1t9b3Gt7K2c6fQig[24];
typedef tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* tyArray_N1u1nqOgmuJN9cSZrnMHgOQ[32];
typedef tyArray_N1u1nqOgmuJN9cSZrnMHgOQ tyArray_B6durA4ZCi1xjJvRtyYxMg[24];
typedef tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* tyArray_lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA {
tyArray_lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* tyArray_0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw {
tyArray_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyArray_LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray_LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray_SiRwrEKZdLgxqz9a9aoVBglg freeSmallChunks;
NU32 flBitmap;
tyArray_BHbOSqU1t9b3Gt7K2c6fQig slBitmap;
tyArray_B6durA4ZCi1xjJvRtyYxMg matrix;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI occ;
NI lastSize;
tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack_7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w additionalRoots;
NI gcThreadId;
};
typedef NU8 tyEnum_SocketFlag_4xio0cAXR7XG4pF9bVcpxEg;
typedef long tyArray_TcvIiMAJvcwzNLsZkfnFnQ[25];
typedef struct {
N_NIMCALL_PTR(NIM_BOOL, ClP_0) (Exception* e, void* ClE_0);
void* ClE_0;
} tyProc_KeeAOYBd84Ofsw6Y7LizaQ;
struct TSafePoint {
TSafePoint* prev;
NI status;
jmp_buf context;
NIM_BOOL hasRaiseAction;
tyProc_KeeAOYBd84Ofsw6Y7LizaQ raiseAction;
};
typedef NIM_CHAR tyArray_NSMq3FMCIrS8gSbyinBZ8w[14];
struct tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA {
NCSTRING procname;
NI line;
NCSTRING filename;
};
struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w {
NI prevSize;
NI size;
};
struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* next;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* prev;
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* freeList;
NI free;
NI acc;
NF data;
};
struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* next;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* prev;
NF data;
};
struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw {
NI size;
NI acc;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* next;
};
typedef NI tyArray_9a8QARi5WsUggNU9bom7kzTQ[8];
struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw {
tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg {
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ {
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* next;
NI zeroField;
};
struct tySequence_9apztJSmgERYU8fZOjI4pOg {
  TGenericSeq Sup;
  int data[SEQ_DECL_SIZE];
};
struct tySequence_uB9b75OUPRENsBAu4AnoePA {
  TGenericSeq Sup;
  tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA data[SEQ_DECL_SIZE];
};
static N_NIMCALL(void, Marker_tyRef_MkGXUPMSENeRDS7EppfLgA)(void* p, NI op);
N_LIB_PRIVATE N_NIMCALL(int, createNativeSocket_BcG9aGQhTam9ajUKte8LeMdQ)(tyEnum_Domain_Q79bEtFARvq0ekDNtvj3Vqg domain, tyEnum_SockType_NQT1bItGG2X9byGdrWX7ujw sockType, tyEnum_Protocol_dqJ1OqRGclxIMMdSLRzzXg protocol);
N_LIB_PRIVATE N_NOINLINE(void, raiseOSError_bEwAamo1N7TKcaU9akpiyIg)(NI32 errorCode, NimStringDesc* additionalInfo);
N_LIB_PRIVATE N_NIMCALL(NI32, osLastError_tNPXXFl9cb3BG0pJKzUn9bew)(void);
N_LIB_PRIVATE N_NIMCALL(tyObject_SocketImpl_aIhANOOoETolVz9cccNO9cRQ*, newSocket_TTP7PU2VgdrTckZ4D68YXQ)(int fd, tyEnum_Domain_Q79bEtFARvq0ekDNtvj3Vqg domain, tyEnum_SockType_NQT1bItGG2X9byGdrWX7ujw sockType, tyEnum_Protocol_dqJ1OqRGclxIMMdSLRzzXg protocol, NIM_BOOL buffered);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_LIB_PRIVATE N_NIMCALL(struct addrinfo*, getAddrInfo_fNPnGAYqSzdc2OjHEcTTAw)(NimStringDesc* address, NU16 port, tyEnum_Domain_Q79bEtFARvq0ekDNtvj3Vqg domain, tyEnum_SockType_NQT1bItGG2X9byGdrWX7ujw sockType, tyEnum_Protocol_dqJ1OqRGclxIMMdSLRzzXg protocol);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_LIB_PRIVATE N_NIMCALL(void, readLine_l59cCpx09aQpLQbXCndaaGew)(tyObject_SocketImpl_aIhANOOoETolVz9cccNO9cRQ* socket, NimStringDesc** line, NI timeout, tySet_tyEnum_SocketFlag_4xio0cAXR7XG4pF9bVcpxEg flags, NI maxLength);
N_NIMCALL(NimStringDesc*, setLengthStr)(NimStringDesc* s, NI newLen);
N_LIB_PRIVATE N_NIMCALL(NI, waitFor_DLrn8tBaenNwTOV5QMiQhw)(tyObject_SocketImpl_aIhANOOoETolVz9cccNO9cRQ* socket, NF* waited, NI timeout, NI size, NimStringDesc* funcName);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, Marker_tyRef_bU6ho49aX9aZ5qCG1X0EzmCw)(void* p, NI op);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr);
static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NOINLINE(void, addZCT_fCDI7oO1NNVXXURtxSzsRw)(tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_NIMCALL(void, raiseException)(Exception* e, NCSTRING ename);
N_LIB_PRIVATE N_NIMCALL(NF, ntepochTime)(void);
N_LIB_PRIVATE N_NIMCALL(NI, select_EWIewKQK7bC2BMs0GJHLsA)(tyObject_SocketImpl_aIhANOOoETolVz9cccNO9cRQ* readfd, NI timeout);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, hasDataBuffered_D9aXQ6Vx48ilhfQ09coEZXAw)(tyObject_SocketImpl_aIhANOOoETolVz9cccNO9cRQ* s);
N_NIMCALL(void*, newSeq)(TNimType* typ, NI len);
N_LIB_PRIVATE N_NIMCALL(NI, select_f1UV2yno269c9cyjR0CwiQwg)(tySequence_9apztJSmgERYU8fZOjI4pOg** readfds, NI timeout);
static N_INLINE(void, pluseq__7kHiltrvRlcg6wSYR3CxAwnet)(NF* x, NF y);
N_LIB_PRIVATE N_NIMCALL(NI, recv_6eWgn0t3M3qFYl9c4RYk4FA)(tyObject_SocketImpl_aIhANOOoETolVz9cccNO9cRQ* socket, void* data, NI size);
N_LIB_PRIVATE N_NIMCALL(NI, readIntoBuf_a8hnRfVzCAJazP8VYSHoxQ)(tyObject_SocketImpl_aIhANOOoETolVz9cccNO9cRQ* socket, NI32 flags);
N_LIB_PRIVATE N_NIMCALL(NI, uniRecv_Hx48EkOmgqTBPhLgNQeFrw)(tyObject_SocketImpl_aIhANOOoETolVz9cccNO9cRQ* socket, void* buffer, int size, int flags);
N_LIB_PRIVATE N_NIMCALL(NI32, getSocketError_I9cOwGw5109aYFtR4C9bKiSIw)(tyObject_SocketImpl_aIhANOOoETolVz9cccNO9cRQ* socket);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, isDisconnectionError_40p9aaw5rEmIprdUBGKsyYQ)(tySet_tyEnum_SocketFlag_4xio0cAXR7XG4pF9bVcpxEg flags, NI32 lastError);
N_LIB_PRIVATE N_NIMCALL(void, socketError_xXD9cJW6hYk6e0AZZkJqrpg)(tyObject_SocketImpl_aIhANOOoETolVz9cccNO9cRQ* socket, NI err, NIM_BOOL async, NI32 lastError);
N_LIB_PRIVATE N_NIMCALL(NI, peekChar_v3zsvCMMzaf8SsqM3bcKOw)(tyObject_SocketImpl_aIhANOOoETolVz9cccNO9cRQ* socket, NIM_CHAR* c);
N_NIMCALL(NimStringDesc*, resizeString)(NimStringDesc* dest, NI addlen);
N_NIMCALL(NimStringDesc*, addChar)(NimStringDesc* s, NIM_CHAR c);
N_LIB_PRIVATE N_NIMCALL(NI, send_dq9a0j6Kas9cDXuWFRyz74Pw)(tyObject_SocketImpl_aIhANOOoETolVz9cccNO9cRQ* socket, void* data, NI size);
static N_INLINE(void, pushSafePoint)(TSafePoint* s);
static N_INLINE(void, popSafePoint)(void);
N_LIB_PRIVATE N_NIMCALL(void, close_ODRNWwddsp7NVetdw9cXCVg)(int socket);
N_NIMCALL(void, reraiseException)(void);
TNimType NTI_aIhANOOoETolVz9cccNO9cRQ_;
extern TNimType NTI_nlCscttRCss70IBTyuBqnA_;
extern TNimType NTI_VaVACK0bpYmqIQ0mKcHfQQ_;
extern TNimType NTI_nmiMWKVIe46vacnhAFrQvw_;
TNimType NTI_QQGLPNVVwLhYjkngqAxXQQ_;
extern TNimType NTI_rR5Bzr1D5krxoo1NcNyeMA_;
extern TNimType NTI_sVg18TP9cLifHyygRe9cro9aA_;
extern TNimType NTI_Q79bEtFARvq0ekDNtvj3Vqg_;
extern TNimType NTI_NQT1bItGG2X9byGdrWX7ujw_;
extern TNimType NTI_dqJ1OqRGclxIMMdSLRzzXg_;
TNimType NTI_MkGXUPMSENeRDS7EppfLgA_;
extern int osInvalidSocket_voz9aUXu8jtRbvGZZJHNE8w;
extern TNimType NTI_bAvOj2UcojKN87yAQLs0aw_;
TNimType NTI_FsA9cqNuEA9c2lfCA9bcCRasw_;
TNimType NTI_bU6ho49aX9aZ5qCG1X0EzmCw_;
extern tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
extern TNimType NTI_9apztJSmgERYU8fZOjI4pOg_;
extern TSafePoint* excHandler_rqLlY5bs9atDw2OXYqJEn5g;
TNimNode* NimDT__aIhANOOoETolVz9cccNO9cRQ_isBuffered[3];
STRING_LITERAL(TM_XqsrSBxhOTPgLQ9cX4MmV4A_4, "", 0);
STRING_LITERAL(TM_XqsrSBxhOTPgLQ9cX4MmV4A_5, "Call to \'", 9);
STRING_LITERAL(TM_XqsrSBxhOTPgLQ9cX4MmV4A_6, "\' timed out.", 12);
STRING_LITERAL(TM_XqsrSBxhOTPgLQ9cX4MmV4A_7, "readLine", 8);
STRING_LITERAL(TM_XqsrSBxhOTPgLQ9cX4MmV4A_8, "No valid socket error code available", 36);
STRING_LITERAL(TM_XqsrSBxhOTPgLQ9cX4MmV4A_9, "\015\012", 2);
STRING_LITERAL(TM_XqsrSBxhOTPgLQ9cX4MmV4A_10, "Could not send all data.", 24);
static N_NIMCALL(void, Marker_tyRef_MkGXUPMSENeRDS7EppfLgA)(void* p, NI op) {
	tyObject_SocketImpl_aIhANOOoETolVz9cccNO9cRQ* a;
	NI T1_;
	a = (tyObject_SocketImpl_aIhANOOoETolVz9cccNO9cRQ*)p;
	switch ((*a).isBuffered) {
	case NIM_TRUE:
	T1_ = (NI)0;
	break;
	case NIM_FALSE:
	break;
	} 
}

N_LIB_PRIVATE N_NIMCALL(tyObject_SocketImpl_aIhANOOoETolVz9cccNO9cRQ*, newSocket_TTP7PU2VgdrTckZ4D68YXQ)(int fd, tyEnum_Domain_Q79bEtFARvq0ekDNtvj3Vqg domain, tyEnum_SockType_NQT1bItGG2X9byGdrWX7ujw sockType, tyEnum_Protocol_dqJ1OqRGclxIMMdSLRzzXg protocol, NIM_BOOL buffered) {
	tyObject_SocketImpl_aIhANOOoETolVz9cccNO9cRQ* result;
	tyObject_SocketImpl_aIhANOOoETolVz9cccNO9cRQ* T1_;
	result = (tyObject_SocketImpl_aIhANOOoETolVz9cccNO9cRQ*)0;
	T1_ = (tyObject_SocketImpl_aIhANOOoETolVz9cccNO9cRQ*)0;
	T1_ = (tyObject_SocketImpl_aIhANOOoETolVz9cccNO9cRQ*) newObj((&NTI_MkGXUPMSENeRDS7EppfLgA_), sizeof(tyObject_SocketImpl_aIhANOOoETolVz9cccNO9cRQ));
	(*T1_).fd = fd;
	(*T1_).isBuffered = buffered;
	(*T1_).domain = domain;
	(*T1_).sockType = sockType;
	(*T1_).protocol = protocol;
	result = T1_;
	{
		if (!buffered) goto LA4_;
		(*result).isBufferedU.S1.currPos = ((NI) 0);
	}
	LA4_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_SocketImpl_aIhANOOoETolVz9cccNO9cRQ*, newSocket_8Lrat9ciQTaGiwISp8ak13A)(tyEnum_Domain_Q79bEtFARvq0ekDNtvj3Vqg domain, tyEnum_SockType_NQT1bItGG2X9byGdrWX7ujw sockType, tyEnum_Protocol_dqJ1OqRGclxIMMdSLRzzXg protocol, NIM_BOOL buffered) {
	tyObject_SocketImpl_aIhANOOoETolVz9cccNO9cRQ* result;
	int fd;
	result = (tyObject_SocketImpl_aIhANOOoETolVz9cccNO9cRQ*)0;
	fd = createNativeSocket_BcG9aGQhTam9ajUKte8LeMdQ(domain, sockType, protocol);
	{
		NI32 T5_;
		if (!(fd == osInvalidSocket_voz9aUXu8jtRbvGZZJHNE8w)) goto LA3_;
		T5_ = (NI32)0;
		T5_ = osLastError_tNPXXFl9cb3BG0pJKzUn9bew();
		raiseOSError_bEwAamo1N7TKcaU9akpiyIg(T5_, ((NimStringDesc*) &TM_XqsrSBxhOTPgLQ9cX4MmV4A_4));
	}
	LA3_: ;
	result = newSocket_TTP7PU2VgdrTckZ4D68YXQ(fd, domain, sockType, protocol, buffered);
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, connect_v3he1j4BPHctgBidfSUq7g)(tyObject_SocketImpl_aIhANOOoETolVz9cccNO9cRQ* socket, NimStringDesc* address, NU16 port) {
	struct addrinfo* aiList;
	NIM_BOOL success;
	NI32 lastError;
	struct addrinfo* it;
	aiList = getAddrInfo_fNPnGAYqSzdc2OjHEcTTAw(address, port, (*socket).domain, ((tyEnum_SockType_NQT1bItGG2X9byGdrWX7ujw) 1), ((tyEnum_Protocol_dqJ1OqRGclxIMMdSLRzzXg) 6));
	success = NIM_FALSE;
	lastError = (NI32)0;
	it = aiList;
	{
		while (1) {
			if (!!((it == NIM_NIL))) goto LA2;
			{
				int T5_;
				T5_ = (int)0;
				T5_ = connect((*socket).fd, (*it).ai_addr, (*it).ai_addrlen);
				if (!(T5_ == ((NI32) 0))) goto LA6_;
				success = NIM_TRUE;
				goto LA1;
			}
			goto LA3_;
			LA6_: ;
			{
				lastError = osLastError_tNPXXFl9cb3BG0pJKzUn9bew();
			}
			LA3_: ;
			it = (*it).ai_next;
		} LA2: ;
	} LA1: ;
	freeaddrinfo(aiList);
	{
		if (!!(success)) goto LA11_;
		raiseOSError_bEwAamo1N7TKcaU9akpiyIg(lastError, ((NimStringDesc*) &TM_XqsrSBxhOTPgLQ9cX4MmV4A_4));
	}
	LA11_: ;
}
static N_NIMCALL(void, Marker_tyRef_bU6ho49aX9aZ5qCG1X0EzmCw)(void* p, NI op) {
	tyObject_TimeoutError_FsA9cqNuEA9c2lfCA9bcCRasw* a;
	a = (tyObject_TimeoutError_FsA9cqNuEA9c2lfCA9bcCRasw*)p;
	nimGCvisit((void*)(*a).Sup.parent, op);
	nimGCvisit((void*)(*a).Sup.message, op);
	nimGCvisit((void*)(*a).Sup.trace, op);
	nimGCvisit((void*)(*a).Sup.up, op);
}

static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	copyMem_E1xtACub5WcDa3vbrIXbwgsystem(((void*) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((void*) ((*src).data)), ((NI) ((NI)((*src).Sup.len + ((NI) 1)))));
	(*dest).Sup.len += (*src).Sup.len;
}

static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* result;
	result = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	result = ((tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*) ((NI)((NU64)(((NI) (ptrdiff_t) (usr))) - (NU64)(((NI)sizeof(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g))))));
	return result;
}

static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	addZCT_fCDI7oO1NNVXXURtxSzsRw((&gch_IcYaEuuWivYAS86vFMTS3Q.zct), c);
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
		if (!!((src == NIM_NIL))) goto LA3_;
		c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		(*c).refcount += ((NI) 8);
	}
	LA3_: ;
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c_2;
		if (!!(((*dest) == NIM_NIL))) goto LA7_;
		c_2 = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		{
			(*c_2).refcount -= ((NI) 8);
			if (!((NU64)((*c_2).refcount) < (NU64)(((NI) 8)))) goto LA11_;
			rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c_2);
		}
		LA11_: ;
	}
	LA7_: ;
	(*dest) = src;
}

static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	(*c).refcount = (NI)((NU64)((*c).refcount) + (NU64)(((NI) 8)));
}

static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
}

static N_INLINE(void, asgnRef)(void** dest, void* src) {
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T5_;
		if (!!((src == NIM_NIL))) goto LA3_;
		T5_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T5_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		incRef_9cAA5YuQAAC3MVbnGeV86swsystem(T5_);
	}
	LA3_: ;
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T10_;
		if (!!(((*dest) == NIM_NIL))) goto LA8_;
		T10_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T10_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		decRef_MV4BBk6J1qu70IbBxwEn4wsystem(T10_);
	}
	LA8_: ;
	(*dest) = src;
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, hasDataBuffered_D9aXQ6Vx48ilhfQ09coEZXAw)(tyObject_SocketImpl_aIhANOOoETolVz9cccNO9cRQ* s) {
	NIM_BOOL result;
	result = (NIM_BOOL)0;
	result = NIM_FALSE;
	{
		NIM_BOOL T5_;
		if (!(*s).isBuffered) goto LA3_;
		T5_ = (NIM_BOOL)0;
		T5_ = (((NI) 0) < (*s).isBufferedU.S1.bufLen);
		if (!(T5_)) goto LA6_;
		T5_ = !(((*s).isBufferedU.S1.currPos == (*s).isBufferedU.S1.bufLen));
		LA6_: ;
		result = T5_;
	}
	LA3_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NI, select_EWIewKQK7bC2BMs0GJHLsA)(tyObject_SocketImpl_aIhANOOoETolVz9cccNO9cRQ* readfd, NI timeout) {
	NI result;
	tySequence_9apztJSmgERYU8fZOjI4pOg* fds;
{	result = (NI)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = hasDataBuffered_D9aXQ6Vx48ilhfQ09coEZXAw(readfd);
		if (!T3_) goto LA4_;
		result = ((NI) 1);
		goto BeforeRet_;
	}
	LA4_: ;
	fds = (tySequence_9apztJSmgERYU8fZOjI4pOg*) newSeq((&NTI_9apztJSmgERYU8fZOjI4pOg_), 1);
	fds->data[0] = (*readfd).fd;
	result = select_f1UV2yno269c9cyjR0CwiQwg((&fds), timeout);
	}BeforeRet_: ;
	return result;
}

static N_INLINE(void, pluseq__7kHiltrvRlcg6wSYR3CxAwnet)(NF* x, NF y) {
	(*x) = ((NF)((*x)) + (NF)(y));
}

N_LIB_PRIVATE N_NIMCALL(NI, waitFor_DLrn8tBaenNwTOV5QMiQhw)(tyObject_SocketImpl_aIhANOOoETolVz9cccNO9cRQ* socket, NF* waited, NI timeout, NI size, NimStringDesc* funcName) {
	NI result;
{	result = (NI)0;
	result = ((NI) 1);
	{
		if (!(size <= ((NI) 0))) goto LA3_;
	}
	LA3_: ;
	{
		if (!(timeout == ((NI) -1))) goto LA7_;
		result = size;
		goto BeforeRet_;
	}
	LA7_: ;
	{
		NIM_BOOL T11_;
		NIM_BOOL T12_;
		T11_ = (NIM_BOOL)0;
		T12_ = (NIM_BOOL)0;
		T12_ = (*socket).isBuffered;
		if (!(T12_)) goto LA13_;
		T12_ = !(((*socket).isBufferedU.S1.bufLen == ((NI) 0)));
		LA13_: ;
		T11_ = T12_;
		if (!(T11_)) goto LA14_;
		T11_ = !(((*socket).isBufferedU.S1.bufLen == (*socket).isBufferedU.S1.currPos));
		LA14_: ;
		if (!T11_) goto LA15_;
		result = (NI)((*socket).isBufferedU.S1.bufLen - (*socket).isBufferedU.S1.currPos);
		result = ((result <= size) ? result : size);
	}
	goto LA9_;
	LA15_: ;
	{
		NF startTime;
		NI selRet;
		NF T33_;
		{
			tyObject_TimeoutError_FsA9cqNuEA9c2lfCA9bcCRasw* e;
			NimStringDesc* T22_;
			if (!((NI)(timeout - ((NI) (((NF)((*waited)) * (NF)(1.0000000000000000e+03))))) < ((NI) 1))) goto LA20_;
			e = (tyObject_TimeoutError_FsA9cqNuEA9c2lfCA9bcCRasw*)0;
			e = (tyObject_TimeoutError_FsA9cqNuEA9c2lfCA9bcCRasw*) newObj((&NTI_bU6ho49aX9aZ5qCG1X0EzmCw_), sizeof(tyObject_TimeoutError_FsA9cqNuEA9c2lfCA9bcCRasw));
			(*e).Sup.Sup.m_type = (&NTI_FsA9cqNuEA9c2lfCA9bcCRasw_);
			T22_ = (NimStringDesc*)0;
			T22_ = rawNewString(funcName->Sup.len + 21);
appendString(T22_, ((NimStringDesc*) &TM_XqsrSBxhOTPgLQ9cX4MmV4A_5));
appendString(T22_, funcName);
appendString(T22_, ((NimStringDesc*) &TM_XqsrSBxhOTPgLQ9cX4MmV4A_6));
			asgnRefNoCycle((void**) (&(*e).Sup.message), T22_);
			asgnRef((void**) (&(*e).Sup.parent), NIM_NIL);
			raiseException((Exception*)e, "TimeoutError");
		}
		LA20_: ;
		startTime = ntepochTime();
		selRet = select_EWIewKQK7bC2BMs0GJHLsA(socket, (NI)(timeout - ((NI) (((NF)((*waited)) * (NF)(1.0000000000000000e+03))))));
		{
			NI32 T27_;
			if (!(selRet < ((NI) 0))) goto LA25_;
			T27_ = (NI32)0;
			T27_ = osLastError_tNPXXFl9cb3BG0pJKzUn9bew();
			raiseOSError_bEwAamo1N7TKcaU9akpiyIg(T27_, ((NimStringDesc*) &TM_XqsrSBxhOTPgLQ9cX4MmV4A_4));
		}
		LA25_: ;
		{
			tyObject_TimeoutError_FsA9cqNuEA9c2lfCA9bcCRasw* e_2;
			NimStringDesc* T32_;
			if (!!((selRet == ((NI) 1)))) goto LA30_;
			e_2 = (tyObject_TimeoutError_FsA9cqNuEA9c2lfCA9bcCRasw*)0;
			e_2 = (tyObject_TimeoutError_FsA9cqNuEA9c2lfCA9bcCRasw*) newObj((&NTI_bU6ho49aX9aZ5qCG1X0EzmCw_), sizeof(tyObject_TimeoutError_FsA9cqNuEA9c2lfCA9bcCRasw));
			(*e_2).Sup.Sup.m_type = (&NTI_FsA9cqNuEA9c2lfCA9bcCRasw_);
			T32_ = (NimStringDesc*)0;
			T32_ = rawNewString(funcName->Sup.len + 21);
appendString(T32_, ((NimStringDesc*) &TM_XqsrSBxhOTPgLQ9cX4MmV4A_5));
appendString(T32_, funcName);
appendString(T32_, ((NimStringDesc*) &TM_XqsrSBxhOTPgLQ9cX4MmV4A_6));
			asgnRefNoCycle((void**) (&(*e_2).Sup.message), T32_);
			asgnRef((void**) (&(*e_2).Sup.parent), NIM_NIL);
			raiseException((Exception*)e_2, "TimeoutError");
		}
		LA30_: ;
		T33_ = (NF)0;
		T33_ = ntepochTime();
		pluseq__7kHiltrvRlcg6wSYR3CxAwnet(waited, ((NF)(T33_) - (NF)(startTime)));
	}
	LA9_: ;
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NI, uniRecv_Hx48EkOmgqTBPhLgNQeFrw)(tyObject_SocketImpl_aIhANOOoETolVz9cccNO9cRQ* socket, void* buffer, int size, int flags) {
	NI result;
{	result = (NI)0;
	result = ((NI) 0);
	result = recv((*socket).fd, buffer, ((NI) (size)), flags);
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NI, readIntoBuf_a8hnRfVzCAJazP8VYSHoxQ)(tyObject_SocketImpl_aIhANOOoETolVz9cccNO9cRQ* socket, NI32 flags) {
	NI result;
{	result = (NI)0;
	result = ((NI) 0);
	result = uniRecv_Hx48EkOmgqTBPhLgNQeFrw(socket, ((void*) ((*socket).isBufferedU.S1.buffer)), ((int) 4000), flags);
	{
		if (!(result < ((NI) 0))) goto LA3_;
		(*socket).lastError = osLastError_tNPXXFl9cb3BG0pJKzUn9bew();
	}
	LA3_: ;
	{
		if (!(result <= ((NI) 0))) goto LA7_;
		(*socket).isBufferedU.S1.bufLen = ((NI) 0);
		(*socket).isBufferedU.S1.currPos = ((NI) 0);
		goto BeforeRet_;
	}
	LA7_: ;
	(*socket).isBufferedU.S1.bufLen = result;
	(*socket).isBufferedU.S1.currPos = ((NI) 0);
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NI, recv_6eWgn0t3M3qFYl9c4RYk4FA)(tyObject_SocketImpl_aIhANOOoETolVz9cccNO9cRQ* socket, void* data, NI size) {
	NI result;
{	result = (NI)0;
	{
		if (!(size == ((NI) 0))) goto LA3_;
		goto BeforeRet_;
	}
	LA3_: ;
	{
		NI read;
		if (!(*socket).isBuffered) goto LA7_;
		{
			NI res;
			if (!((*socket).isBufferedU.S1.bufLen == ((NI) 0))) goto LA11_;
			res = readIntoBuf_a8hnRfVzCAJazP8VYSHoxQ(socket, ((NI32) 0));
			{
				if (!(res <= ((NI) 0))) goto LA15_;
				{
					if (!NIM_FALSE) goto LA19_;
					result = ((NI) 0);
					goto BeforeRet_;
				}
				goto LA17_;
				LA19_: ;
				{
					result = res;
					goto BeforeRet_;
				}
				LA17_: ;
			}
			LA15_: ;
		}
		LA11_: ;
		read = ((NI) 0);
		{
			while (1) {
				NI chunk;
				NCSTRING d;
				if (!(read < size)) goto LA23;
				{
					NI res_2;
					if (!((*socket).isBufferedU.S1.bufLen <= (*socket).isBufferedU.S1.currPos)) goto LA26_;
					res_2 = readIntoBuf_a8hnRfVzCAJazP8VYSHoxQ(socket, ((NI32) 0));
					{
						if (!(res_2 <= ((NI) 0))) goto LA30_;
						{
							if (!(((NI) 0) < read)) goto LA34_;
							result = read;
							goto BeforeRet_;
						}
						goto LA32_;
						LA34_: ;
						{
							result = res_2;
							goto BeforeRet_;
						}
						LA32_: ;
					}
					LA30_: ;
				}
				LA26_: ;
				chunk = (((NI)((*socket).isBufferedU.S1.bufLen - (*socket).isBufferedU.S1.currPos) <= (NI)(size - read)) ? (NI)((*socket).isBufferedU.S1.bufLen - (*socket).isBufferedU.S1.currPos) : (NI)(size - read));
				d = ((NCSTRING) (data));
				copyMem_E1xtACub5WcDa3vbrIXbwgsystem(((void*) ((&d[read]))), ((void*) ((&(*socket).isBufferedU.S1.buffer[((*socket).isBufferedU.S1.currPos)- 0]))), ((NI) (chunk)));
				read += chunk;
				(*socket).isBufferedU.S1.currPos += chunk;
			} LA23: ;
		}
		result = read;
	}
	goto LA5_;
	LA7_: ;
	{
		result = recv((*socket).fd, data, ((NI) (((int) (size)))), ((NI32) 0));
		{
			if (!(result < ((NI) 0))) goto LA40_;
			(*socket).lastError = osLastError_tNPXXFl9cb3BG0pJKzUn9bew();
		}
		LA40_: ;
	}
	LA5_: ;
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NI32, getSocketError_I9cOwGw5109aYFtR4C9bKiSIw)(tyObject_SocketImpl_aIhANOOoETolVz9cccNO9cRQ* socket) {
	NI32 result;
	result = (NI32)0;
	result = osLastError_tNPXXFl9cb3BG0pJKzUn9bew();
	{
		if (!(result == ((NI32) 0))) goto LA3_;
		result = (*socket).lastError;
	}
	LA3_: ;
	{
		if (!(result == ((NI32) 0))) goto LA7_;
		raiseOSError_bEwAamo1N7TKcaU9akpiyIg(result, ((NimStringDesc*) &TM_XqsrSBxhOTPgLQ9cX4MmV4A_8));
	}
	LA7_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, isDisconnectionError_40p9aaw5rEmIprdUBGKsyYQ)(tySet_tyEnum_SocketFlag_4xio0cAXR7XG4pF9bVcpxEg flags, NI32 lastError) {
	NIM_BOOL result;
	NIM_BOOL T1_;
	result = (NIM_BOOL)0;
	T1_ = (NIM_BOOL)0;
	T1_ = ((flags &(1U<<((NU)(((tyEnum_SocketFlag_4xio0cAXR7XG4pF9bVcpxEg) 1))&7U)))!=0);
	if (!(T1_)) goto LA2_;
	T1_ = (lastError == ((NI) 104) || lastError == ((NI) 32) || lastError == ((NI) 102));
	LA2_: ;
	result = T1_;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, socketError_xXD9cJW6hYk6e0AZZkJqrpg)(tyObject_SocketImpl_aIhANOOoETolVz9cccNO9cRQ* socket, NI err, NIM_BOOL async, NI32 lastError) {
{	{
		NIM_BOOL T3_;
		NI32 lastE;
		T3_ = (NIM_BOOL)0;
		T3_ = (err == ((NI) -1));
		if (!(T3_)) goto LA4_;
		T3_ = NIM_TRUE;
		LA4_: ;
		if (!T3_) goto LA5_;
		{
			if (!(((NI) (lastError)) == ((NI) -1))) goto LA9_;
			lastE = getSocketError_I9cOwGw5109aYFtR4C9bKiSIw(socket);
		}
		goto LA7_;
		LA9_: ;
		{
			lastE = lastError;
		}
		LA7_: ;
		{
			if (!async) goto LA14_;
			{
				NIM_BOOL T18_;
				T18_ = (NIM_BOOL)0;
				T18_ = (lastE == ((int) 11));
				if (T18_) goto LA19_;
				T18_ = (lastE == ((int) 11));
				LA19_: ;
				if (!T18_) goto LA20_;
				goto BeforeRet_;
			}
			goto LA16_;
			LA20_: ;
			{
				raiseOSError_bEwAamo1N7TKcaU9akpiyIg(lastE, ((NimStringDesc*) &TM_XqsrSBxhOTPgLQ9cX4MmV4A_4));
			}
			LA16_: ;
		}
		goto LA12_;
		LA14_: ;
		{
			raiseOSError_bEwAamo1N7TKcaU9akpiyIg(lastE, ((NimStringDesc*) &TM_XqsrSBxhOTPgLQ9cX4MmV4A_4));
		}
		LA12_: ;
	}
	LA5_: ;
	}BeforeRet_: ;
}

N_LIB_PRIVATE N_NIMCALL(NI, peekChar_v3zsvCMMzaf8SsqM3bcKOw)(tyObject_SocketImpl_aIhANOOoETolVz9cccNO9cRQ* socket, NIM_CHAR* c) {
	NI result;
	result = (NI)0;
	{
		if (!(*socket).isBuffered) goto LA3_;
		result = ((NI) 1);
		{
			NIM_BOOL T7_;
			NI res;
			T7_ = (NIM_BOOL)0;
			T7_ = ((*socket).isBufferedU.S1.bufLen == ((NI) 0));
			if (T7_) goto LA8_;
			T7_ = ((NI)((*socket).isBufferedU.S1.bufLen - ((NI) 1)) < (*socket).isBufferedU.S1.currPos);
			LA8_: ;
			if (!T7_) goto LA9_;
			res = readIntoBuf_a8hnRfVzCAJazP8VYSHoxQ(socket, ((NI32) 0));
			{
				if (!(res <= ((NI) 0))) goto LA13_;
				result = res;
			}
			LA13_: ;
		}
		LA9_: ;
		(*c) = (*socket).isBufferedU.S1.buffer[((*socket).isBufferedU.S1.currPos)- 0];
	}
	goto LA1_;
	LA3_: ;
	{
		result = recv((*socket).fd, ((void*) (c)), ((NI) 1), ((int) 2));
	}
	LA1_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, readLine_l59cCpx09aQpLQbXCndaaGew)(tyObject_SocketImpl_aIhANOOoETolVz9cccNO9cRQ* socket, NimStringDesc** line, NI timeout, tySet_tyEnum_SocketFlag_4xio0cAXR7XG4pF9bVcpxEg flags, NI maxLength) {
	NF waited;
{	waited = 0.0;
	(*line) = setLengthStr((*line), ((NI) 0));
	{
		while (1) {
			NIM_CHAR c;
			NI T3_;
			NI n;
			c = (NIM_CHAR)0;
			T3_ = (NI)0;
			T3_ = waitFor_DLrn8tBaenNwTOV5QMiQhw(socket, (&waited), timeout, ((NI) 1), ((NimStringDesc*) &TM_XqsrSBxhOTPgLQ9cX4MmV4A_7));
			T3_;
			n = recv_6eWgn0t3M3qFYl9c4RYk4FA(socket, ((void*) ((&c))), ((NI) 1));
			{
				NI32 lastError;
				if (!(n < ((NI) 0))) goto LA6_;
				lastError = getSocketError_I9cOwGw5109aYFtR4C9bKiSIw(socket);
				{
					NIM_BOOL T10_;
					T10_ = (NIM_BOOL)0;
					T10_ = isDisconnectionError_40p9aaw5rEmIprdUBGKsyYQ(flags, lastError);
					if (!T10_) goto LA11_;
					(*line) = setLengthStr((*line), ((NI) 0));
					goto BeforeRet_;
				}
				LA11_: ;
				socketError_xXD9cJW6hYk6e0AZZkJqrpg(socket, n, NIM_FALSE, lastError);
			}
			goto LA4_;
			LA6_: ;
			{
				if (!(n == ((NI) 0))) goto LA14_;
				(*line) = setLengthStr((*line), ((NI) 0));
				goto BeforeRet_;
			}
			goto LA4_;
			LA14_: ;
			LA4_: ;
			{
				NI T20_;
				if (!((NU8)(c) == (NU8)(13))) goto LA18_;
				T20_ = (NI)0;
				T20_ = waitFor_DLrn8tBaenNwTOV5QMiQhw(socket, (&waited), timeout, ((NI) 1), ((NimStringDesc*) &TM_XqsrSBxhOTPgLQ9cX4MmV4A_7));
				T20_;
				n = peekChar_v3zsvCMMzaf8SsqM3bcKOw(socket, (&c));
				{
					NIM_BOOL T23_;
					NI T27_;
					T23_ = (NIM_BOOL)0;
					T23_ = (((NI) 0) < n);
					if (!(T23_)) goto LA24_;
					T23_ = ((NU8)(c) == (NU8)(10));
					LA24_: ;
					if (!T23_) goto LA25_;
					T27_ = (NI)0;
					T27_ = recv_6eWgn0t3M3qFYl9c4RYk4FA(socket, ((void*) ((&c))), ((NI) 1));
					T27_;
				}
				goto LA21_;
				LA25_: ;
				{
					NI32 lastError_2;
					if (!(n <= ((NI) 0))) goto LA29_;
					lastError_2 = getSocketError_I9cOwGw5109aYFtR4C9bKiSIw(socket);
					{
						NIM_BOOL T33_;
						T33_ = (NIM_BOOL)0;
						T33_ = isDisconnectionError_40p9aaw5rEmIprdUBGKsyYQ(flags, lastError_2);
						if (!T33_) goto LA34_;
						(*line) = setLengthStr((*line), ((NI) 0));
						goto BeforeRet_;
					}
					LA34_: ;
					socketError_xXD9cJW6hYk6e0AZZkJqrpg(socket, n, NIM_FALSE, lastError_2);
				}
				goto LA21_;
				LA29_: ;
				LA21_: ;
				{
					if (!(((*line) ? (*line)->Sup.len : 0) == ((NI) 0))) goto LA38_;
					(*line) = resizeString((*line), 2);
appendString((*line), ((NimStringDesc*) &TM_XqsrSBxhOTPgLQ9cX4MmV4A_9));
				}
				LA38_: ;
				goto BeforeRet_;
			}
			goto LA16_;
			LA18_: ;
			{
				if (!((NU8)(c) == (NU8)(10))) goto LA41_;
				{
					if (!(((*line) ? (*line)->Sup.len : 0) == ((NI) 0))) goto LA45_;
					(*line) = resizeString((*line), 2);
appendString((*line), ((NimStringDesc*) &TM_XqsrSBxhOTPgLQ9cX4MmV4A_9));
				}
				LA45_: ;
				goto BeforeRet_;
			}
			goto LA16_;
			LA41_: ;
			LA16_: ;
			(*line) = addChar((*line), c);
			{
				if (!(maxLength < ((*line) ? (*line)->Sup.len : 0))) goto LA49_;
				goto LA1;
			}
			LA49_: ;
		}
	} LA1: ;
	}BeforeRet_: ;
}

N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, recvLine_xZGQ2vK49cDdWvtLMB8phHQ)(tyObject_SocketImpl_aIhANOOoETolVz9cccNO9cRQ* socket, NI timeout, tySet_tyEnum_SocketFlag_4xio0cAXR7XG4pF9bVcpxEg flags, NI maxLength) {
	NimStringDesc* result;
	result = (NimStringDesc*)0;
	result = copyString(((NimStringDesc*) &TM_XqsrSBxhOTPgLQ9cX4MmV4A_4));
	readLine_l59cCpx09aQpLQbXCndaaGew(socket, (&result), timeout, flags, maxLength);
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NI, send_dq9a0j6Kas9cDXuWFRyz74Pw)(tyObject_SocketImpl_aIhANOOoETolVz9cccNO9cRQ* socket, void* data, NI size) {
	NI result;
	result = (NI)0;
	result = send((*socket).fd, data, size, ((NI32) 16384));
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, send_pLXZNcF79c032efCu7EgyDg)(tyObject_SocketImpl_aIhANOOoETolVz9cccNO9cRQ* socket, NimStringDesc* data, tySet_tyEnum_SocketFlag_4xio0cAXR7XG4pF9bVcpxEg flags) {
	NI sent;
{	sent = send_dq9a0j6Kas9cDXuWFRyz74Pw(socket, ((void*) (data->data)), (data ? data->Sup.len : 0));
	{
		NI32 lastError;
		if (!(sent < ((NI) 0))) goto LA3_;
		lastError = osLastError_tNPXXFl9cb3BG0pJKzUn9bew();
		{
			NIM_BOOL T7_;
			T7_ = (NIM_BOOL)0;
			T7_ = isDisconnectionError_40p9aaw5rEmIprdUBGKsyYQ(flags, lastError);
			if (!T7_) goto LA8_;
			goto BeforeRet_;
		}
		LA8_: ;
		socketError_xXD9cJW6hYk6e0AZZkJqrpg(socket, ((NI) -1), NIM_FALSE, lastError);
	}
	LA3_: ;
	{
		NI32 T14_;
		if (!!((sent == (data ? data->Sup.len : 0)))) goto LA12_;
		T14_ = (NI32)0;
		T14_ = osLastError_tNPXXFl9cb3BG0pJKzUn9bew();
		raiseOSError_bEwAamo1N7TKcaU9akpiyIg(T14_, ((NimStringDesc*) &TM_XqsrSBxhOTPgLQ9cX4MmV4A_10));
	}
	LA12_: ;
	}BeforeRet_: ;
}

static N_INLINE(void, pushSafePoint)(TSafePoint* s) {
	(*s).hasRaiseAction = NIM_FALSE;
	(*s).prev = excHandler_rqLlY5bs9atDw2OXYqJEn5g;
	excHandler_rqLlY5bs9atDw2OXYqJEn5g = s;
}

static N_INLINE(void, popSafePoint)(void) {
	excHandler_rqLlY5bs9atDw2OXYqJEn5g = (*excHandler_rqLlY5bs9atDw2OXYqJEn5g).prev;
}

N_LIB_PRIVATE N_NIMCALL(void, close_VEqnJXVWVBs5DtNQcd59aJw)(tyObject_SocketImpl_aIhANOOoETolVz9cccNO9cRQ* socket) {
	TSafePoint TM_XqsrSBxhOTPgLQ9cX4MmV4A_11;
	pushSafePoint(&TM_XqsrSBxhOTPgLQ9cX4MmV4A_11);
	TM_XqsrSBxhOTPgLQ9cX4MmV4A_11.status = setjmp(TM_XqsrSBxhOTPgLQ9cX4MmV4A_11.context);
	if (TM_XqsrSBxhOTPgLQ9cX4MmV4A_11.status == 0) {
		popSafePoint();
	}
	else {
		popSafePoint();
	}
	{
		close_ODRNWwddsp7NVetdw9cXCVg((*socket).fd);
		(*socket).fd = osInvalidSocket_voz9aUXu8jtRbvGZZJHNE8w;
	}
	if (TM_XqsrSBxhOTPgLQ9cX4MmV4A_11.status != 0) reraiseException();
}
NIM_EXTERNC N_NOINLINE(void, stdlib_netInit000)(void) {
}

NIM_EXTERNC N_NOINLINE(void, stdlib_netDatInit000)(void) {
static TNimNode* TM_XqsrSBxhOTPgLQ9cX4MmV4A_2[6];
static TNimNode* TM_XqsrSBxhOTPgLQ9cX4MmV4A_3[3];
static TNimNode TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[13];
NTI_aIhANOOoETolVz9cccNO9cRQ_.size = sizeof(tyObject_SocketImpl_aIhANOOoETolVz9cccNO9cRQ);
NTI_aIhANOOoETolVz9cccNO9cRQ_.kind = 18;
NTI_aIhANOOoETolVz9cccNO9cRQ_.base = 0;
NTI_aIhANOOoETolVz9cccNO9cRQ_.flags = 3;
TM_XqsrSBxhOTPgLQ9cX4MmV4A_2[0] = &TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[1];
TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[1].kind = 1;
TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[1].offset = offsetof(tyObject_SocketImpl_aIhANOOoETolVz9cccNO9cRQ, fd);
TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[1].typ = (&NTI_nlCscttRCss70IBTyuBqnA_);
TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[1].name = "fd";
TM_XqsrSBxhOTPgLQ9cX4MmV4A_2[1] = &TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[2];
TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[2].kind = 3;
TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[2].offset = offsetof(tyObject_SocketImpl_aIhANOOoETolVz9cccNO9cRQ, isBuffered);
TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[2].typ = (&NTI_VaVACK0bpYmqIQ0mKcHfQQ_);
TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[2].name = "isBuffered";
TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[2].sons = &NimDT__aIhANOOoETolVz9cccNO9cRQ_isBuffered[0];
TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[2].len = 2;
TM_XqsrSBxhOTPgLQ9cX4MmV4A_3[0] = &TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[4];
NTI_QQGLPNVVwLhYjkngqAxXQQ_.size = sizeof(tyArray_QQGLPNVVwLhYjkngqAxXQQ);
NTI_QQGLPNVVwLhYjkngqAxXQQ_.kind = 16;
NTI_QQGLPNVVwLhYjkngqAxXQQ_.base = (&NTI_nmiMWKVIe46vacnhAFrQvw_);
NTI_QQGLPNVVwLhYjkngqAxXQQ_.flags = 3;
TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[4].kind = 1;
TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[4].offset = offsetof(tyObject_SocketImpl_aIhANOOoETolVz9cccNO9cRQ, isBufferedU.S1.buffer);
TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[4].typ = (&NTI_QQGLPNVVwLhYjkngqAxXQQ_);
TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[4].name = "buffer";
TM_XqsrSBxhOTPgLQ9cX4MmV4A_3[1] = &TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[5];
TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[5].kind = 1;
TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[5].offset = offsetof(tyObject_SocketImpl_aIhANOOoETolVz9cccNO9cRQ, isBufferedU.S1.currPos);
TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[5].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[5].name = "currPos";
TM_XqsrSBxhOTPgLQ9cX4MmV4A_3[2] = &TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[6];
TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[6].kind = 1;
TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[6].offset = offsetof(tyObject_SocketImpl_aIhANOOoETolVz9cccNO9cRQ, isBufferedU.S1.bufLen);
TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[6].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[6].name = "bufLen";
TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[3].len = 3; TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[3].kind = 2; TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[3].sons = &TM_XqsrSBxhOTPgLQ9cX4MmV4A_3[0];
NimDT__aIhANOOoETolVz9cccNO9cRQ_isBuffered[1] = &TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[3];
TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[7].len = 0; TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[7].kind = 2;
NimDT__aIhANOOoETolVz9cccNO9cRQ_isBuffered[0] = &TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[7];
TM_XqsrSBxhOTPgLQ9cX4MmV4A_2[2] = &TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[8];
TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[8].kind = 1;
TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[8].offset = offsetof(tyObject_SocketImpl_aIhANOOoETolVz9cccNO9cRQ, lastError);
TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[8].typ = (&NTI_sVg18TP9cLifHyygRe9cro9aA_);
TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[8].name = "lastError";
TM_XqsrSBxhOTPgLQ9cX4MmV4A_2[3] = &TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[9];
TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[9].kind = 1;
TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[9].offset = offsetof(tyObject_SocketImpl_aIhANOOoETolVz9cccNO9cRQ, domain);
TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[9].typ = (&NTI_Q79bEtFARvq0ekDNtvj3Vqg_);
TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[9].name = "domain";
TM_XqsrSBxhOTPgLQ9cX4MmV4A_2[4] = &TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[10];
TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[10].kind = 1;
TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[10].offset = offsetof(tyObject_SocketImpl_aIhANOOoETolVz9cccNO9cRQ, sockType);
TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[10].typ = (&NTI_NQT1bItGG2X9byGdrWX7ujw_);
TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[10].name = "sockType";
TM_XqsrSBxhOTPgLQ9cX4MmV4A_2[5] = &TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[11];
TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[11].kind = 1;
TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[11].offset = offsetof(tyObject_SocketImpl_aIhANOOoETolVz9cccNO9cRQ, protocol);
TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[11].typ = (&NTI_dqJ1OqRGclxIMMdSLRzzXg_);
TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[11].name = "protocol";
TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[0].len = 6; TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[0].kind = 2; TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[0].sons = &TM_XqsrSBxhOTPgLQ9cX4MmV4A_2[0];
NTI_aIhANOOoETolVz9cccNO9cRQ_.node = &TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[0];
NTI_MkGXUPMSENeRDS7EppfLgA_.size = sizeof(tyObject_SocketImpl_aIhANOOoETolVz9cccNO9cRQ*);
NTI_MkGXUPMSENeRDS7EppfLgA_.kind = 22;
NTI_MkGXUPMSENeRDS7EppfLgA_.base = (&NTI_aIhANOOoETolVz9cccNO9cRQ_);
NTI_MkGXUPMSENeRDS7EppfLgA_.flags = 2;
NTI_MkGXUPMSENeRDS7EppfLgA_.marker = Marker_tyRef_MkGXUPMSENeRDS7EppfLgA;
NTI_FsA9cqNuEA9c2lfCA9bcCRasw_.size = sizeof(tyObject_TimeoutError_FsA9cqNuEA9c2lfCA9bcCRasw);
NTI_FsA9cqNuEA9c2lfCA9bcCRasw_.kind = 17;
NTI_FsA9cqNuEA9c2lfCA9bcCRasw_.base = (&NTI_bAvOj2UcojKN87yAQLs0aw_);
TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[12].len = 0; TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[12].kind = 2;
NTI_FsA9cqNuEA9c2lfCA9bcCRasw_.node = &TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[12];
NTI_bU6ho49aX9aZ5qCG1X0EzmCw_.size = sizeof(tyObject_TimeoutError_FsA9cqNuEA9c2lfCA9bcCRasw*);
NTI_bU6ho49aX9aZ5qCG1X0EzmCw_.kind = 22;
NTI_bU6ho49aX9aZ5qCG1X0EzmCw_.base = (&NTI_FsA9cqNuEA9c2lfCA9bcCRasw_);
NTI_bU6ho49aX9aZ5qCG1X0EzmCw_.marker = Marker_tyRef_bU6ho49aX9aZ5qCG1X0EzmCw;
}

