/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -O3 -fno-strict-aliasing  -I/root/.choosenim/toolchains/nim-0.18.0/lib -o /mnt/d/Development/bitbucket/java/NetScoutMerger/script/lsrreport/nimcache/stdlib_asyncdispatch.o /mnt/d/Development/bitbucket/java/NetScoutMerger/script/lsrreport/nimcache/stdlib_asyncdispatch.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tyObject_PDispatchercolonObjectType__pnVRciItPqJkU9bkmY2UaWQ tyObject_PDispatchercolonObjectType__pnVRciItPqJkU9bkmY2UaWQ;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tyObject_PDispatcherBasecolonObjectType__E9c1MI1V1IJorH9cqPQ36Hqg tyObject_PDispatcherBasecolonObjectType__E9c1MI1V1IJorH9cqPQ36Hqg;
typedef struct RootObj RootObj;
typedef struct tySequence_tCXsCfAd03XtyGJVg3kHhg tySequence_tCXsCfAd03XtyGJVg3kHhg;
typedef struct tyObject_Deque_lXZKLUMbpAcAUzeVrG09bNg tyObject_Deque_lXZKLUMbpAcAUzeVrG09bNg;
typedef struct tySequence_WF89a8QyKeDCh4DYWTmSiBg tySequence_WF89a8QyKeDCh4DYWTmSiBg;
typedef struct tyTuple_h8SeyS9aRwdD6lpWqt9anV3A tyTuple_h8SeyS9aRwdD6lpWqt9anV3A;
typedef struct tyObject_FuturecolonObjectType__SmxCgsot45ayPNDBegkWAg tyObject_FuturecolonObjectType__SmxCgsot45ayPNDBegkWAg;
typedef struct tyObject_SelectorImpl_VF2QWbk9cEn13YFg9btPwWLA tyObject_SelectorImpl_VF2QWbk9cEn13YFg9btPwWLA;
typedef struct tyObject_AsyncData_hOYUN4IOpj9adMwn6W7S2VA tyObject_AsyncData_hOYUN4IOpj9adMwn6W7S2VA;
typedef struct tySequence_lBAKjtL5n9bzoWNSpC1Vu3A tySequence_lBAKjtL5n9bzoWNSpC1Vu3A;
typedef struct tyTuple_2uzTbg8jwom7zHhmM2RgHg tyTuple_2uzTbg8jwom7zHhmM2RgHg;
typedef struct tyObject_Env_libslashpureslashasyncdispatchdotnim__sO5O0Qy9bzKs0atwA6HUBAw tyObject_Env_libslashpureslashasyncdispatchdotnim__sO5O0Qy9bzKs0atwA6HUBAw;
typedef struct TGenericSeq TGenericSeq;
typedef struct NimStringDesc NimStringDesc;
typedef struct tyObject_FutureBasecolonObjectType__cnXnCCtV9cjKaEq9alHheOFg tyObject_FutureBasecolonObjectType__cnXnCCtV9cjKaEq9alHheOFg;
typedef struct tyObject_CallbackList_tKSBWiaJMWD3JZxwqg7UFQ tyObject_CallbackList_tKSBWiaJMWD3JZxwqg7UFQ;
typedef struct Exception Exception;
typedef struct tySequence_lKsVWjYqlRD7eN7MeIt2PQ tySequence_lKsVWjYqlRD7eN7MeIt2PQ;
typedef struct tySequence_uB9b75OUPRENsBAu4AnoePA tySequence_uB9b75OUPRENsBAu4AnoePA;
typedef struct tyObject_SelectorKey_6oh6PoZxxmRrkez9bmwfPdQ tyObject_SelectorKey_6oh6PoZxxmRrkez9bmwfPdQ;
typedef struct tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA;
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct RootObj {
TNimType* m_type;
};
struct tyObject_Deque_lXZKLUMbpAcAUzeVrG09bNg {
tySequence_WF89a8QyKeDCh4DYWTmSiBg* data;
NI head;
NI tail;
NI count;
NI mask;
};
struct tyObject_PDispatcherBasecolonObjectType__E9c1MI1V1IJorH9cqPQ36Hqg {
  RootObj Sup;
tySequence_tCXsCfAd03XtyGJVg3kHhg* timers;
tyObject_Deque_lXZKLUMbpAcAUzeVrG09bNg callbacks;
};
struct tyTuple_h8SeyS9aRwdD6lpWqt9anV3A {
NF Field0;
tyObject_FuturecolonObjectType__SmxCgsot45ayPNDBegkWAg* Field1;
};
struct tyObject_PDispatchercolonObjectType__pnVRciItPqJkU9bkmY2UaWQ {
  tyObject_PDispatcherBasecolonObjectType__E9c1MI1V1IJorH9cqPQ36Hqg Sup;
tyObject_SelectorImpl_VF2QWbk9cEn13YFg9btPwWLA* selector;
};
struct tyObject_AsyncData_hOYUN4IOpj9adMwn6W7S2VA {
tySequence_lBAKjtL5n9bzoWNSpC1Vu3A* readList;
tySequence_lBAKjtL5n9bzoWNSpC1Vu3A* writeList;
};
struct tyTuple_2uzTbg8jwom7zHhmM2RgHg {
void* Field0;
tyObject_Env_libslashpureslashasyncdispatchdotnim__sO5O0Qy9bzKs0atwA6HUBAw* Field1;
};
typedef struct {
N_NIMCALL_PTR(NIM_BOOL, ClP_0) (int fd, void* ClE_0);
void* ClE_0;
} tyProc_9cnjNsE9aOh8FkRG9ccBKTpWg;
struct TGenericSeq {
NI len;
NI reserved;
};
typedef N_NIMCALL_PTR(void, tyProc_T4eqaYlFJYZUv9aG9b1TV0bQ) (void);
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef struct {
N_NIMCALL_PTR(void, ClP_0) (void* ClE_0);
void* ClE_0;
} tyProc_IIomJ6ptE6vfJ5zRbATgkQ;
struct tyObject_CallbackList_tKSBWiaJMWD3JZxwqg7UFQ {
tyProc_IIomJ6ptE6vfJ5zRbATgkQ function;
tyObject_CallbackList_tKSBWiaJMWD3JZxwqg7UFQ* next;
};
struct tyObject_FutureBasecolonObjectType__cnXnCCtV9cjKaEq9alHheOFg {
  RootObj Sup;
tyObject_CallbackList_tKSBWiaJMWD3JZxwqg7UFQ callbacks;
NIM_BOOL finished;
Exception* error;
NimStringDesc* errorStackTrace;
};
struct tyObject_FuturecolonObjectType__SmxCgsot45ayPNDBegkWAg {
  tyObject_FutureBasecolonObjectType__cnXnCCtV9cjKaEq9alHheOFg Sup;
};
struct tyObject_SelectorImpl_VF2QWbk9cEn13YFg9btPwWLA {
int epollFD;
NI maxFD;
tySequence_lKsVWjYqlRD7eN7MeIt2PQ* fds;
NI count;
};
struct tyObject_Env_libslashpureslashasyncdispatchdotnim__sO5O0Qy9bzKs0atwA6HUBAw {
  RootObj Sup;
};
struct Exception {
  RootObj Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
tySequence_uB9b75OUPRENsBAu4AnoePA* trace;
Exception* up;
};
typedef NU32 tySet_tyEnum_Event_nI40bZzTyYVrl763dZ9aHDg;
struct tyObject_SelectorKey_6oh6PoZxxmRrkez9bmwfPdQ {
NI ident;
tySet_tyEnum_Event_nI40bZzTyYVrl763dZ9aHDg events;
NI param;
tyObject_AsyncData_hOYUN4IOpj9adMwn6W7S2VA data;
};
struct tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA {
NCSTRING procname;
NI line;
NCSTRING filename;
};
struct tySequence_lBAKjtL5n9bzoWNSpC1Vu3A {
  TGenericSeq Sup;
  tyProc_9cnjNsE9aOh8FkRG9ccBKTpWg data[SEQ_DECL_SIZE];
};
struct tySequence_tCXsCfAd03XtyGJVg3kHhg {
  TGenericSeq Sup;
  tyTuple_h8SeyS9aRwdD6lpWqt9anV3A data[SEQ_DECL_SIZE];
};
struct tySequence_WF89a8QyKeDCh4DYWTmSiBg {
  TGenericSeq Sup;
  tyProc_IIomJ6ptE6vfJ5zRbATgkQ data[SEQ_DECL_SIZE];
};
struct tySequence_lKsVWjYqlRD7eN7MeIt2PQ {
  TGenericSeq Sup;
  tyObject_SelectorKey_6oh6PoZxxmRrkez9bmwfPdQ data[SEQ_DECL_SIZE];
};
struct tySequence_uB9b75OUPRENsBAu4AnoePA {
  TGenericSeq Sup;
  tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA data[SEQ_DECL_SIZE];
};
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, Marker_tySequence_lBAKjtL5n9bzoWNSpC1Vu3A)(void* p, NI op);
static N_NIMCALL(void, Marker_tyRef_LEZ1ZCj9cVMqh7s39cnMX6rw)(void* p, NI op);
static N_NIMCALL(void, TM_gfe9a52b5gJr8GSrnr883iA_6)(void);
N_NIMCALL(void, nimRegisterThreadLocalMarker)(tyProc_T4eqaYlFJYZUv9aG9b1TV0bQ markerProc);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
tyObject_PDispatchercolonObjectType__pnVRciItPqJkU9bkmY2UaWQ* gDisp_yIbBArLUsg2pBJkilx4yvg;
extern TNimType NTI_13RNkKqUOX1TtorOUlKtqA_;
TNimType NTI_E9c1MI1V1IJorH9cqPQ36Hqg_;
TNimType NTI_h8SeyS9aRwdD6lpWqt9anV3A_;
extern TNimType NTI_w9bl9a1ul9ctRJWiMl9cNnIMvg_;
extern TNimType NTI_zXD0JrbeCNyAaW4E6fB9aqg_;
extern TNimType NTI_tCXsCfAd03XtyGJVg3kHhg_;
extern TNimType NTI_lXZKLUMbpAcAUzeVrG09bNg_;
TNimType NTI_pnVRciItPqJkU9bkmY2UaWQ_;
TNimType NTI_hOYUN4IOpj9adMwn6W7S2VA_;
TNimType NTI_9cnjNsE9aOh8FkRG9ccBKTpWg_;
extern TNimType NTI_vr5DoT1jILTGdRlYv1OYpw_;
extern TNimType NTI_58EFneeS9at7cA541QCoGAw_;
TNimType NTI_lBAKjtL5n9bzoWNSpC1Vu3A_;
extern TNimType NTI_eV1HoGAGYVaJgQ5BCEf67g_;
TNimType NTI_LEZ1ZCj9cVMqh7s39cnMX6rw_;
static N_NIMCALL(void, Marker_tySequence_lBAKjtL5n9bzoWNSpC1Vu3A)(void* p, NI op) {
	tySequence_lBAKjtL5n9bzoWNSpC1Vu3A* a;
	NI T1_;
	a = (tySequence_lBAKjtL5n9bzoWNSpC1Vu3A*)p;
	T1_ = (NI)0;
	for (T1_ = 0; T1_ < a->Sup.len; T1_++) {
	nimGCvisit((void*)a->data[T1_].ClE_0, op);
	}
}
static N_NIMCALL(void, Marker_tyRef_LEZ1ZCj9cVMqh7s39cnMX6rw)(void* p, NI op) {
	tyObject_PDispatchercolonObjectType__pnVRciItPqJkU9bkmY2UaWQ* a;
	a = (tyObject_PDispatchercolonObjectType__pnVRciItPqJkU9bkmY2UaWQ*)p;
	nimGCvisit((void*)(*a).Sup.timers, op);
	nimGCvisit((void*)(*a).Sup.callbacks.data, op);
	nimGCvisit((void*)(*a).selector, op);
}
static N_NIMCALL(void, TM_gfe9a52b5gJr8GSrnr883iA_6)(void) {
	nimGCvisit((void*)gDisp_yIbBArLUsg2pBJkilx4yvg, 0);
}

N_LIB_PRIVATE N_NIMCALL(void, emptyNoop_q9cSFCJLo26XZQjXW3c2FvA)(void) {
}

N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, emptyNoop_Wku8LwQ9b9c4GuOk9cJPXhKLg)(NimStringDesc* x) {
	NimStringDesc* result;
{	result = (NimStringDesc*)0;
	result = copyString(x);
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_asyncdispatchInit000)(void) {
nimRegisterThreadLocalMarker(TM_gfe9a52b5gJr8GSrnr883iA_6);
}

NIM_EXTERNC N_NOINLINE(void, stdlib_asyncdispatchDatInit000)(void) {
static TNimNode* TM_gfe9a52b5gJr8GSrnr883iA_2[2];
static TNimNode* TM_gfe9a52b5gJr8GSrnr883iA_3[2];
static TNimNode* TM_gfe9a52b5gJr8GSrnr883iA_4[2];
static TNimNode* TM_gfe9a52b5gJr8GSrnr883iA_5[2];
static TNimNode TM_gfe9a52b5gJr8GSrnr883iA_0[13];
NTI_E9c1MI1V1IJorH9cqPQ36Hqg_.size = sizeof(tyObject_PDispatcherBasecolonObjectType__E9c1MI1V1IJorH9cqPQ36Hqg);
NTI_E9c1MI1V1IJorH9cqPQ36Hqg_.kind = 17;
NTI_E9c1MI1V1IJorH9cqPQ36Hqg_.base = (&NTI_13RNkKqUOX1TtorOUlKtqA_);
TM_gfe9a52b5gJr8GSrnr883iA_2[0] = &TM_gfe9a52b5gJr8GSrnr883iA_0[1];
NTI_h8SeyS9aRwdD6lpWqt9anV3A_.size = sizeof(tyTuple_h8SeyS9aRwdD6lpWqt9anV3A);
NTI_h8SeyS9aRwdD6lpWqt9anV3A_.kind = 18;
NTI_h8SeyS9aRwdD6lpWqt9anV3A_.base = 0;
TM_gfe9a52b5gJr8GSrnr883iA_3[0] = &TM_gfe9a52b5gJr8GSrnr883iA_0[3];
TM_gfe9a52b5gJr8GSrnr883iA_0[3].kind = 1;
TM_gfe9a52b5gJr8GSrnr883iA_0[3].offset = offsetof(tyTuple_h8SeyS9aRwdD6lpWqt9anV3A, Field0);
TM_gfe9a52b5gJr8GSrnr883iA_0[3].typ = (&NTI_w9bl9a1ul9ctRJWiMl9cNnIMvg_);
TM_gfe9a52b5gJr8GSrnr883iA_0[3].name = "Field0";
TM_gfe9a52b5gJr8GSrnr883iA_3[1] = &TM_gfe9a52b5gJr8GSrnr883iA_0[4];
TM_gfe9a52b5gJr8GSrnr883iA_0[4].kind = 1;
TM_gfe9a52b5gJr8GSrnr883iA_0[4].offset = offsetof(tyTuple_h8SeyS9aRwdD6lpWqt9anV3A, Field1);
TM_gfe9a52b5gJr8GSrnr883iA_0[4].typ = (&NTI_zXD0JrbeCNyAaW4E6fB9aqg_);
TM_gfe9a52b5gJr8GSrnr883iA_0[4].name = "Field1";
TM_gfe9a52b5gJr8GSrnr883iA_0[2].len = 2; TM_gfe9a52b5gJr8GSrnr883iA_0[2].kind = 2; TM_gfe9a52b5gJr8GSrnr883iA_0[2].sons = &TM_gfe9a52b5gJr8GSrnr883iA_3[0];
NTI_h8SeyS9aRwdD6lpWqt9anV3A_.node = &TM_gfe9a52b5gJr8GSrnr883iA_0[2];
TM_gfe9a52b5gJr8GSrnr883iA_0[1].kind = 1;
TM_gfe9a52b5gJr8GSrnr883iA_0[1].offset = offsetof(tyObject_PDispatcherBasecolonObjectType__E9c1MI1V1IJorH9cqPQ36Hqg, timers);
TM_gfe9a52b5gJr8GSrnr883iA_0[1].typ = (&NTI_tCXsCfAd03XtyGJVg3kHhg_);
TM_gfe9a52b5gJr8GSrnr883iA_0[1].name = "timers";
TM_gfe9a52b5gJr8GSrnr883iA_2[1] = &TM_gfe9a52b5gJr8GSrnr883iA_0[5];
TM_gfe9a52b5gJr8GSrnr883iA_0[5].kind = 1;
TM_gfe9a52b5gJr8GSrnr883iA_0[5].offset = offsetof(tyObject_PDispatcherBasecolonObjectType__E9c1MI1V1IJorH9cqPQ36Hqg, callbacks);
TM_gfe9a52b5gJr8GSrnr883iA_0[5].typ = (&NTI_lXZKLUMbpAcAUzeVrG09bNg_);
TM_gfe9a52b5gJr8GSrnr883iA_0[5].name = "callbacks";
TM_gfe9a52b5gJr8GSrnr883iA_0[0].len = 2; TM_gfe9a52b5gJr8GSrnr883iA_0[0].kind = 2; TM_gfe9a52b5gJr8GSrnr883iA_0[0].sons = &TM_gfe9a52b5gJr8GSrnr883iA_2[0];
NTI_E9c1MI1V1IJorH9cqPQ36Hqg_.node = &TM_gfe9a52b5gJr8GSrnr883iA_0[0];
NTI_pnVRciItPqJkU9bkmY2UaWQ_.size = sizeof(tyObject_PDispatchercolonObjectType__pnVRciItPqJkU9bkmY2UaWQ);
NTI_pnVRciItPqJkU9bkmY2UaWQ_.kind = 17;
NTI_pnVRciItPqJkU9bkmY2UaWQ_.base = (&NTI_E9c1MI1V1IJorH9cqPQ36Hqg_);
NTI_hOYUN4IOpj9adMwn6W7S2VA_.size = sizeof(tyObject_AsyncData_hOYUN4IOpj9adMwn6W7S2VA);
NTI_hOYUN4IOpj9adMwn6W7S2VA_.kind = 18;
NTI_hOYUN4IOpj9adMwn6W7S2VA_.base = 0;
TM_gfe9a52b5gJr8GSrnr883iA_4[0] = &TM_gfe9a52b5gJr8GSrnr883iA_0[8];
NTI_9cnjNsE9aOh8FkRG9ccBKTpWg_.size = sizeof(tyTuple_2uzTbg8jwom7zHhmM2RgHg);
NTI_9cnjNsE9aOh8FkRG9ccBKTpWg_.kind = 18;
NTI_9cnjNsE9aOh8FkRG9ccBKTpWg_.base = 0;
TM_gfe9a52b5gJr8GSrnr883iA_5[0] = &TM_gfe9a52b5gJr8GSrnr883iA_0[10];
TM_gfe9a52b5gJr8GSrnr883iA_0[10].kind = 1;
TM_gfe9a52b5gJr8GSrnr883iA_0[10].offset = offsetof(tyTuple_2uzTbg8jwom7zHhmM2RgHg, Field0);
TM_gfe9a52b5gJr8GSrnr883iA_0[10].typ = (&NTI_vr5DoT1jILTGdRlYv1OYpw_);
TM_gfe9a52b5gJr8GSrnr883iA_0[10].name = "Field0";
TM_gfe9a52b5gJr8GSrnr883iA_5[1] = &TM_gfe9a52b5gJr8GSrnr883iA_0[11];
TM_gfe9a52b5gJr8GSrnr883iA_0[11].kind = 1;
TM_gfe9a52b5gJr8GSrnr883iA_0[11].offset = offsetof(tyTuple_2uzTbg8jwom7zHhmM2RgHg, Field1);
TM_gfe9a52b5gJr8GSrnr883iA_0[11].typ = (&NTI_58EFneeS9at7cA541QCoGAw_);
TM_gfe9a52b5gJr8GSrnr883iA_0[11].name = "Field1";
TM_gfe9a52b5gJr8GSrnr883iA_0[9].len = 2; TM_gfe9a52b5gJr8GSrnr883iA_0[9].kind = 2; TM_gfe9a52b5gJr8GSrnr883iA_0[9].sons = &TM_gfe9a52b5gJr8GSrnr883iA_5[0];
NTI_9cnjNsE9aOh8FkRG9ccBKTpWg_.node = &TM_gfe9a52b5gJr8GSrnr883iA_0[9];
NTI_lBAKjtL5n9bzoWNSpC1Vu3A_.size = sizeof(tySequence_lBAKjtL5n9bzoWNSpC1Vu3A*);
NTI_lBAKjtL5n9bzoWNSpC1Vu3A_.kind = 24;
NTI_lBAKjtL5n9bzoWNSpC1Vu3A_.base = (&NTI_9cnjNsE9aOh8FkRG9ccBKTpWg_);
NTI_lBAKjtL5n9bzoWNSpC1Vu3A_.marker = Marker_tySequence_lBAKjtL5n9bzoWNSpC1Vu3A;
TM_gfe9a52b5gJr8GSrnr883iA_0[8].kind = 1;
TM_gfe9a52b5gJr8GSrnr883iA_0[8].offset = offsetof(tyObject_AsyncData_hOYUN4IOpj9adMwn6W7S2VA, readList);
TM_gfe9a52b5gJr8GSrnr883iA_0[8].typ = (&NTI_lBAKjtL5n9bzoWNSpC1Vu3A_);
TM_gfe9a52b5gJr8GSrnr883iA_0[8].name = "readList";
TM_gfe9a52b5gJr8GSrnr883iA_4[1] = &TM_gfe9a52b5gJr8GSrnr883iA_0[12];
TM_gfe9a52b5gJr8GSrnr883iA_0[12].kind = 1;
TM_gfe9a52b5gJr8GSrnr883iA_0[12].offset = offsetof(tyObject_AsyncData_hOYUN4IOpj9adMwn6W7S2VA, writeList);
TM_gfe9a52b5gJr8GSrnr883iA_0[12].typ = (&NTI_lBAKjtL5n9bzoWNSpC1Vu3A_);
TM_gfe9a52b5gJr8GSrnr883iA_0[12].name = "writeList";
TM_gfe9a52b5gJr8GSrnr883iA_0[7].len = 2; TM_gfe9a52b5gJr8GSrnr883iA_0[7].kind = 2; TM_gfe9a52b5gJr8GSrnr883iA_0[7].sons = &TM_gfe9a52b5gJr8GSrnr883iA_4[0];
NTI_hOYUN4IOpj9adMwn6W7S2VA_.node = &TM_gfe9a52b5gJr8GSrnr883iA_0[7];
TM_gfe9a52b5gJr8GSrnr883iA_0[6].kind = 1;
TM_gfe9a52b5gJr8GSrnr883iA_0[6].offset = offsetof(tyObject_PDispatchercolonObjectType__pnVRciItPqJkU9bkmY2UaWQ, selector);
TM_gfe9a52b5gJr8GSrnr883iA_0[6].typ = (&NTI_eV1HoGAGYVaJgQ5BCEf67g_);
TM_gfe9a52b5gJr8GSrnr883iA_0[6].name = "selector";
NTI_pnVRciItPqJkU9bkmY2UaWQ_.node = &TM_gfe9a52b5gJr8GSrnr883iA_0[6];
NTI_LEZ1ZCj9cVMqh7s39cnMX6rw_.size = sizeof(tyObject_PDispatchercolonObjectType__pnVRciItPqJkU9bkmY2UaWQ*);
NTI_LEZ1ZCj9cVMqh7s39cnMX6rw_.kind = 22;
NTI_LEZ1ZCj9cVMqh7s39cnMX6rw_.base = (&NTI_pnVRciItPqJkU9bkmY2UaWQ_);
NTI_LEZ1ZCj9cVMqh7s39cnMX6rw_.marker = Marker_tyRef_LEZ1ZCj9cVMqh7s39cnMX6rw;
}

