/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -O3 -fno-strict-aliasing  -I/root/.choosenim/toolchains/nim-0.18.0/lib -o /mnt/d/Development/bitbucket/java/NetScoutMerger/script/lsrreport/nimcache/stdlib_deques.o /mnt/d/Development/bitbucket/java/NetScoutMerger/script/lsrreport/nimcache/stdlib_deques.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tyObject_Deque_lXZKLUMbpAcAUzeVrG09bNg tyObject_Deque_lXZKLUMbpAcAUzeVrG09bNg;
typedef struct tySequence_WF89a8QyKeDCh4DYWTmSiBg tySequence_WF89a8QyKeDCh4DYWTmSiBg;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct TGenericSeq TGenericSeq;
struct tyObject_Deque_lXZKLUMbpAcAUzeVrG09bNg {
tySequence_WF89a8QyKeDCh4DYWTmSiBg* data;
NI head;
NI tail;
NI count;
NI mask;
};
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef struct {
N_NIMCALL_PTR(void, ClP_0) (void* ClE_0);
void* ClE_0;
} tyProc_IIomJ6ptE6vfJ5zRbATgkQ;
struct TGenericSeq {
NI len;
NI reserved;
};
struct tySequence_WF89a8QyKeDCh4DYWTmSiBg {
  TGenericSeq Sup;
  tyProc_IIomJ6ptE6vfJ5zRbATgkQ data[SEQ_DECL_SIZE];
};
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, Marker_tySequence_WF89a8QyKeDCh4DYWTmSiBg)(void* p, NI op);
TNimType NTI_lXZKLUMbpAcAUzeVrG09bNg_;
extern TNimType NTI_IIomJ6ptE6vfJ5zRbATgkQ_;
TNimType NTI_WF89a8QyKeDCh4DYWTmSiBg_;
extern TNimType NTI_rR5Bzr1D5krxoo1NcNyeMA_;
static N_NIMCALL(void, Marker_tySequence_WF89a8QyKeDCh4DYWTmSiBg)(void* p, NI op) {
	tySequence_WF89a8QyKeDCh4DYWTmSiBg* a;
	NI T1_;
	a = (tySequence_WF89a8QyKeDCh4DYWTmSiBg*)p;
	T1_ = (NI)0;
	for (T1_ = 0; T1_ < a->Sup.len; T1_++) {
	nimGCvisit((void*)a->data[T1_].ClE_0, op);
	}
}
NIM_EXTERNC N_NOINLINE(void, stdlib_dequesInit000)(void) {
}

NIM_EXTERNC N_NOINLINE(void, stdlib_dequesDatInit000)(void) {
static TNimNode* TM_NdgYN5HU2ty0qMI5oazWyg_2[5];
static TNimNode TM_NdgYN5HU2ty0qMI5oazWyg_0[6];
NTI_lXZKLUMbpAcAUzeVrG09bNg_.size = sizeof(tyObject_Deque_lXZKLUMbpAcAUzeVrG09bNg);
NTI_lXZKLUMbpAcAUzeVrG09bNg_.kind = 18;
NTI_lXZKLUMbpAcAUzeVrG09bNg_.base = 0;
TM_NdgYN5HU2ty0qMI5oazWyg_2[0] = &TM_NdgYN5HU2ty0qMI5oazWyg_0[1];
NTI_WF89a8QyKeDCh4DYWTmSiBg_.size = sizeof(tySequence_WF89a8QyKeDCh4DYWTmSiBg*);
NTI_WF89a8QyKeDCh4DYWTmSiBg_.kind = 24;
NTI_WF89a8QyKeDCh4DYWTmSiBg_.base = (&NTI_IIomJ6ptE6vfJ5zRbATgkQ_);
NTI_WF89a8QyKeDCh4DYWTmSiBg_.marker = Marker_tySequence_WF89a8QyKeDCh4DYWTmSiBg;
TM_NdgYN5HU2ty0qMI5oazWyg_0[1].kind = 1;
TM_NdgYN5HU2ty0qMI5oazWyg_0[1].offset = offsetof(tyObject_Deque_lXZKLUMbpAcAUzeVrG09bNg, data);
TM_NdgYN5HU2ty0qMI5oazWyg_0[1].typ = (&NTI_WF89a8QyKeDCh4DYWTmSiBg_);
TM_NdgYN5HU2ty0qMI5oazWyg_0[1].name = "data";
TM_NdgYN5HU2ty0qMI5oazWyg_2[1] = &TM_NdgYN5HU2ty0qMI5oazWyg_0[2];
TM_NdgYN5HU2ty0qMI5oazWyg_0[2].kind = 1;
TM_NdgYN5HU2ty0qMI5oazWyg_0[2].offset = offsetof(tyObject_Deque_lXZKLUMbpAcAUzeVrG09bNg, head);
TM_NdgYN5HU2ty0qMI5oazWyg_0[2].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_NdgYN5HU2ty0qMI5oazWyg_0[2].name = "head";
TM_NdgYN5HU2ty0qMI5oazWyg_2[2] = &TM_NdgYN5HU2ty0qMI5oazWyg_0[3];
TM_NdgYN5HU2ty0qMI5oazWyg_0[3].kind = 1;
TM_NdgYN5HU2ty0qMI5oazWyg_0[3].offset = offsetof(tyObject_Deque_lXZKLUMbpAcAUzeVrG09bNg, tail);
TM_NdgYN5HU2ty0qMI5oazWyg_0[3].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_NdgYN5HU2ty0qMI5oazWyg_0[3].name = "tail";
TM_NdgYN5HU2ty0qMI5oazWyg_2[3] = &TM_NdgYN5HU2ty0qMI5oazWyg_0[4];
TM_NdgYN5HU2ty0qMI5oazWyg_0[4].kind = 1;
TM_NdgYN5HU2ty0qMI5oazWyg_0[4].offset = offsetof(tyObject_Deque_lXZKLUMbpAcAUzeVrG09bNg, count);
TM_NdgYN5HU2ty0qMI5oazWyg_0[4].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_NdgYN5HU2ty0qMI5oazWyg_0[4].name = "count";
TM_NdgYN5HU2ty0qMI5oazWyg_2[4] = &TM_NdgYN5HU2ty0qMI5oazWyg_0[5];
TM_NdgYN5HU2ty0qMI5oazWyg_0[5].kind = 1;
TM_NdgYN5HU2ty0qMI5oazWyg_0[5].offset = offsetof(tyObject_Deque_lXZKLUMbpAcAUzeVrG09bNg, mask);
TM_NdgYN5HU2ty0qMI5oazWyg_0[5].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_NdgYN5HU2ty0qMI5oazWyg_0[5].name = "mask";
TM_NdgYN5HU2ty0qMI5oazWyg_0[0].len = 5; TM_NdgYN5HU2ty0qMI5oazWyg_0[0].kind = 2; TM_NdgYN5HU2ty0qMI5oazWyg_0[0].sons = &TM_NdgYN5HU2ty0qMI5oazWyg_2[0];
NTI_lXZKLUMbpAcAUzeVrG09bNg_.node = &TM_NdgYN5HU2ty0qMI5oazWyg_0[0];
}

