/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -O3 -fno-strict-aliasing  -I/root/.choosenim/toolchains/nim-0.18.0/lib -o /mnt/d/Development/bitbucket/java/NetScoutMerger/script/lsrreport/nimcache/stdlib_selectors.o /mnt/d/Development/bitbucket/java/NetScoutMerger/script/lsrreport/nimcache/stdlib_selectors.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tyObject_SelectorImpl_VF2QWbk9cEn13YFg9btPwWLA tyObject_SelectorImpl_VF2QWbk9cEn13YFg9btPwWLA;
typedef struct tySequence_lKsVWjYqlRD7eN7MeIt2PQ tySequence_lKsVWjYqlRD7eN7MeIt2PQ;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tyObject_SelectorKey_6oh6PoZxxmRrkez9bmwfPdQ tyObject_SelectorKey_6oh6PoZxxmRrkez9bmwfPdQ;
typedef struct tyObject_AsyncData_hOYUN4IOpj9adMwn6W7S2VA tyObject_AsyncData_hOYUN4IOpj9adMwn6W7S2VA;
typedef struct tySequence_lBAKjtL5n9bzoWNSpC1Vu3A tySequence_lBAKjtL5n9bzoWNSpC1Vu3A;
typedef struct TGenericSeq TGenericSeq;
struct tyObject_SelectorImpl_VF2QWbk9cEn13YFg9btPwWLA {
int epollFD;
NI maxFD;
tySequence_lKsVWjYqlRD7eN7MeIt2PQ* fds;
NI count;
};
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef NU32 tySet_tyEnum_Event_nI40bZzTyYVrl763dZ9aHDg;
struct tyObject_AsyncData_hOYUN4IOpj9adMwn6W7S2VA {
tySequence_lBAKjtL5n9bzoWNSpC1Vu3A* readList;
tySequence_lBAKjtL5n9bzoWNSpC1Vu3A* writeList;
};
struct tyObject_SelectorKey_6oh6PoZxxmRrkez9bmwfPdQ {
NI ident;
tySet_tyEnum_Event_nI40bZzTyYVrl763dZ9aHDg events;
NI param;
tyObject_AsyncData_hOYUN4IOpj9adMwn6W7S2VA data;
};
typedef NU8 tyEnum_Event_nI40bZzTyYVrl763dZ9aHDg;
struct TGenericSeq {
NI len;
NI reserved;
};
typedef struct {
N_NIMCALL_PTR(NIM_BOOL, ClP_0) (int fd, void* ClE_0);
void* ClE_0;
} tyProc_9cnjNsE9aOh8FkRG9ccBKTpWg;
struct tySequence_lKsVWjYqlRD7eN7MeIt2PQ {
  TGenericSeq Sup;
  tyObject_SelectorKey_6oh6PoZxxmRrkez9bmwfPdQ data[SEQ_DECL_SIZE];
};
struct tySequence_lBAKjtL5n9bzoWNSpC1Vu3A {
  TGenericSeq Sup;
  tyProc_9cnjNsE9aOh8FkRG9ccBKTpWg data[SEQ_DECL_SIZE];
};
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, Marker_tySequence_lKsVWjYqlRD7eN7MeIt2PQ)(void* p, NI op);
static N_NIMCALL(void, Marker_tyRef_eV1HoGAGYVaJgQ5BCEf67g)(void* p, NI op);
TNimType NTI_VF2QWbk9cEn13YFg9btPwWLA_;
extern TNimType NTI_nlCscttRCss70IBTyuBqnA_;
extern TNimType NTI_rR5Bzr1D5krxoo1NcNyeMA_;
TNimType NTI_6oh6PoZxxmRrkez9bmwfPdQ_;
TNimType NTI_nI40bZzTyYVrl763dZ9aHDg_;
TNimType NTI_YIRsZrDT89buh37M5yeUgng_;
extern TNimType NTI_hOYUN4IOpj9adMwn6W7S2VA_;
TNimType NTI_lKsVWjYqlRD7eN7MeIt2PQ_;
TNimType NTI_eV1HoGAGYVaJgQ5BCEf67g_;
static N_NIMCALL(void, Marker_tySequence_lKsVWjYqlRD7eN7MeIt2PQ)(void* p, NI op) {
	tySequence_lKsVWjYqlRD7eN7MeIt2PQ* a;
	NI T1_;
	a = (tySequence_lKsVWjYqlRD7eN7MeIt2PQ*)p;
	T1_ = (NI)0;
	for (T1_ = 0; T1_ < a->Sup.len; T1_++) {
	nimGCvisit((void*)a->data[T1_].data.readList, op);
	nimGCvisit((void*)a->data[T1_].data.writeList, op);
	}
}
static N_NIMCALL(void, Marker_tyRef_eV1HoGAGYVaJgQ5BCEf67g)(void* p, NI op) {
	tyObject_SelectorImpl_VF2QWbk9cEn13YFg9btPwWLA* a;
	a = (tyObject_SelectorImpl_VF2QWbk9cEn13YFg9btPwWLA*)p;
	nimGCvisit((void*)(*a).fds, op);
}
NIM_EXTERNC N_NOINLINE(void, stdlib_selectorsInit000)(void) {
}

NIM_EXTERNC N_NOINLINE(void, stdlib_selectorsDatInit000)(void) {
static TNimNode* TM_ln5vuDpFyDrAqQbYD2g52Q_2[4];
static TNimNode* TM_ln5vuDpFyDrAqQbYD2g52Q_3[4];
static TNimNode* TM_ln5vuDpFyDrAqQbYD2g52Q_4[17];
NI TM_ln5vuDpFyDrAqQbYD2g52Q_6;
static char* NIM_CONST TM_ln5vuDpFyDrAqQbYD2g52Q_5[17] = {
"Read", 
"Write", 
"Timer", 
"Signal", 
"Process", 
"Vnode", 
"User", 
"Error", 
"Oneshot", 
"Finished", 
"VnodeWrite", 
"VnodeDelete", 
"VnodeExtend", 
"VnodeAttrib", 
"VnodeLink", 
"VnodeRename", 
"VnodeRevoke"};
static TNimNode TM_ln5vuDpFyDrAqQbYD2g52Q_0[29];
NTI_VF2QWbk9cEn13YFg9btPwWLA_.size = sizeof(tyObject_SelectorImpl_VF2QWbk9cEn13YFg9btPwWLA);
NTI_VF2QWbk9cEn13YFg9btPwWLA_.kind = 18;
NTI_VF2QWbk9cEn13YFg9btPwWLA_.base = 0;
TM_ln5vuDpFyDrAqQbYD2g52Q_2[0] = &TM_ln5vuDpFyDrAqQbYD2g52Q_0[1];
TM_ln5vuDpFyDrAqQbYD2g52Q_0[1].kind = 1;
TM_ln5vuDpFyDrAqQbYD2g52Q_0[1].offset = offsetof(tyObject_SelectorImpl_VF2QWbk9cEn13YFg9btPwWLA, epollFD);
TM_ln5vuDpFyDrAqQbYD2g52Q_0[1].typ = (&NTI_nlCscttRCss70IBTyuBqnA_);
TM_ln5vuDpFyDrAqQbYD2g52Q_0[1].name = "epollFD";
TM_ln5vuDpFyDrAqQbYD2g52Q_2[1] = &TM_ln5vuDpFyDrAqQbYD2g52Q_0[2];
TM_ln5vuDpFyDrAqQbYD2g52Q_0[2].kind = 1;
TM_ln5vuDpFyDrAqQbYD2g52Q_0[2].offset = offsetof(tyObject_SelectorImpl_VF2QWbk9cEn13YFg9btPwWLA, maxFD);
TM_ln5vuDpFyDrAqQbYD2g52Q_0[2].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_ln5vuDpFyDrAqQbYD2g52Q_0[2].name = "maxFD";
TM_ln5vuDpFyDrAqQbYD2g52Q_2[2] = &TM_ln5vuDpFyDrAqQbYD2g52Q_0[3];
NTI_6oh6PoZxxmRrkez9bmwfPdQ_.size = sizeof(tyObject_SelectorKey_6oh6PoZxxmRrkez9bmwfPdQ);
NTI_6oh6PoZxxmRrkez9bmwfPdQ_.kind = 18;
NTI_6oh6PoZxxmRrkez9bmwfPdQ_.base = 0;
TM_ln5vuDpFyDrAqQbYD2g52Q_3[0] = &TM_ln5vuDpFyDrAqQbYD2g52Q_0[5];
TM_ln5vuDpFyDrAqQbYD2g52Q_0[5].kind = 1;
TM_ln5vuDpFyDrAqQbYD2g52Q_0[5].offset = offsetof(tyObject_SelectorKey_6oh6PoZxxmRrkez9bmwfPdQ, ident);
TM_ln5vuDpFyDrAqQbYD2g52Q_0[5].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_ln5vuDpFyDrAqQbYD2g52Q_0[5].name = "ident";
TM_ln5vuDpFyDrAqQbYD2g52Q_3[1] = &TM_ln5vuDpFyDrAqQbYD2g52Q_0[6];
NTI_nI40bZzTyYVrl763dZ9aHDg_.size = sizeof(tyEnum_Event_nI40bZzTyYVrl763dZ9aHDg);
NTI_nI40bZzTyYVrl763dZ9aHDg_.kind = 14;
NTI_nI40bZzTyYVrl763dZ9aHDg_.base = 0;
NTI_nI40bZzTyYVrl763dZ9aHDg_.flags = 3;
for (TM_ln5vuDpFyDrAqQbYD2g52Q_6 = 0; TM_ln5vuDpFyDrAqQbYD2g52Q_6 < 17; TM_ln5vuDpFyDrAqQbYD2g52Q_6++) {
TM_ln5vuDpFyDrAqQbYD2g52Q_0[TM_ln5vuDpFyDrAqQbYD2g52Q_6+7].kind = 1;
TM_ln5vuDpFyDrAqQbYD2g52Q_0[TM_ln5vuDpFyDrAqQbYD2g52Q_6+7].offset = TM_ln5vuDpFyDrAqQbYD2g52Q_6;
TM_ln5vuDpFyDrAqQbYD2g52Q_0[TM_ln5vuDpFyDrAqQbYD2g52Q_6+7].name = TM_ln5vuDpFyDrAqQbYD2g52Q_5[TM_ln5vuDpFyDrAqQbYD2g52Q_6];
TM_ln5vuDpFyDrAqQbYD2g52Q_4[TM_ln5vuDpFyDrAqQbYD2g52Q_6] = &TM_ln5vuDpFyDrAqQbYD2g52Q_0[TM_ln5vuDpFyDrAqQbYD2g52Q_6+7];
}
TM_ln5vuDpFyDrAqQbYD2g52Q_0[24].len = 17; TM_ln5vuDpFyDrAqQbYD2g52Q_0[24].kind = 2; TM_ln5vuDpFyDrAqQbYD2g52Q_0[24].sons = &TM_ln5vuDpFyDrAqQbYD2g52Q_4[0];
NTI_nI40bZzTyYVrl763dZ9aHDg_.node = &TM_ln5vuDpFyDrAqQbYD2g52Q_0[24];
NTI_YIRsZrDT89buh37M5yeUgng_.size = sizeof(tySet_tyEnum_Event_nI40bZzTyYVrl763dZ9aHDg);
NTI_YIRsZrDT89buh37M5yeUgng_.kind = 19;
NTI_YIRsZrDT89buh37M5yeUgng_.base = (&NTI_nI40bZzTyYVrl763dZ9aHDg_);
NTI_YIRsZrDT89buh37M5yeUgng_.flags = 3;
TM_ln5vuDpFyDrAqQbYD2g52Q_0[25].len = 0; TM_ln5vuDpFyDrAqQbYD2g52Q_0[25].kind = 0;
NTI_YIRsZrDT89buh37M5yeUgng_.node = &TM_ln5vuDpFyDrAqQbYD2g52Q_0[25];
TM_ln5vuDpFyDrAqQbYD2g52Q_0[6].kind = 1;
TM_ln5vuDpFyDrAqQbYD2g52Q_0[6].offset = offsetof(tyObject_SelectorKey_6oh6PoZxxmRrkez9bmwfPdQ, events);
TM_ln5vuDpFyDrAqQbYD2g52Q_0[6].typ = (&NTI_YIRsZrDT89buh37M5yeUgng_);
TM_ln5vuDpFyDrAqQbYD2g52Q_0[6].name = "events";
TM_ln5vuDpFyDrAqQbYD2g52Q_3[2] = &TM_ln5vuDpFyDrAqQbYD2g52Q_0[26];
TM_ln5vuDpFyDrAqQbYD2g52Q_0[26].kind = 1;
TM_ln5vuDpFyDrAqQbYD2g52Q_0[26].offset = offsetof(tyObject_SelectorKey_6oh6PoZxxmRrkez9bmwfPdQ, param);
TM_ln5vuDpFyDrAqQbYD2g52Q_0[26].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_ln5vuDpFyDrAqQbYD2g52Q_0[26].name = "param";
TM_ln5vuDpFyDrAqQbYD2g52Q_3[3] = &TM_ln5vuDpFyDrAqQbYD2g52Q_0[27];
TM_ln5vuDpFyDrAqQbYD2g52Q_0[27].kind = 1;
TM_ln5vuDpFyDrAqQbYD2g52Q_0[27].offset = offsetof(tyObject_SelectorKey_6oh6PoZxxmRrkez9bmwfPdQ, data);
TM_ln5vuDpFyDrAqQbYD2g52Q_0[27].typ = (&NTI_hOYUN4IOpj9adMwn6W7S2VA_);
TM_ln5vuDpFyDrAqQbYD2g52Q_0[27].name = "data";
TM_ln5vuDpFyDrAqQbYD2g52Q_0[4].len = 4; TM_ln5vuDpFyDrAqQbYD2g52Q_0[4].kind = 2; TM_ln5vuDpFyDrAqQbYD2g52Q_0[4].sons = &TM_ln5vuDpFyDrAqQbYD2g52Q_3[0];
NTI_6oh6PoZxxmRrkez9bmwfPdQ_.node = &TM_ln5vuDpFyDrAqQbYD2g52Q_0[4];
NTI_lKsVWjYqlRD7eN7MeIt2PQ_.size = sizeof(tySequence_lKsVWjYqlRD7eN7MeIt2PQ*);
NTI_lKsVWjYqlRD7eN7MeIt2PQ_.kind = 24;
NTI_lKsVWjYqlRD7eN7MeIt2PQ_.base = (&NTI_6oh6PoZxxmRrkez9bmwfPdQ_);
NTI_lKsVWjYqlRD7eN7MeIt2PQ_.marker = Marker_tySequence_lKsVWjYqlRD7eN7MeIt2PQ;
TM_ln5vuDpFyDrAqQbYD2g52Q_0[3].kind = 1;
TM_ln5vuDpFyDrAqQbYD2g52Q_0[3].offset = offsetof(tyObject_SelectorImpl_VF2QWbk9cEn13YFg9btPwWLA, fds);
TM_ln5vuDpFyDrAqQbYD2g52Q_0[3].typ = (&NTI_lKsVWjYqlRD7eN7MeIt2PQ_);
TM_ln5vuDpFyDrAqQbYD2g52Q_0[3].name = "fds";
TM_ln5vuDpFyDrAqQbYD2g52Q_2[3] = &TM_ln5vuDpFyDrAqQbYD2g52Q_0[28];
TM_ln5vuDpFyDrAqQbYD2g52Q_0[28].kind = 1;
TM_ln5vuDpFyDrAqQbYD2g52Q_0[28].offset = offsetof(tyObject_SelectorImpl_VF2QWbk9cEn13YFg9btPwWLA, count);
TM_ln5vuDpFyDrAqQbYD2g52Q_0[28].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_ln5vuDpFyDrAqQbYD2g52Q_0[28].name = "count";
TM_ln5vuDpFyDrAqQbYD2g52Q_0[0].len = 4; TM_ln5vuDpFyDrAqQbYD2g52Q_0[0].kind = 2; TM_ln5vuDpFyDrAqQbYD2g52Q_0[0].sons = &TM_ln5vuDpFyDrAqQbYD2g52Q_2[0];
NTI_VF2QWbk9cEn13YFg9btPwWLA_.node = &TM_ln5vuDpFyDrAqQbYD2g52Q_0[0];
NTI_eV1HoGAGYVaJgQ5BCEf67g_.size = sizeof(tyObject_SelectorImpl_VF2QWbk9cEn13YFg9btPwWLA*);
NTI_eV1HoGAGYVaJgQ5BCEf67g_.kind = 22;
NTI_eV1HoGAGYVaJgQ5BCEf67g_.base = (&NTI_VF2QWbk9cEn13YFg9btPwWLA_);
NTI_eV1HoGAGYVaJgQ5BCEf67g_.marker = Marker_tyRef_eV1HoGAGYVaJgQ5BCEf67g;
}

