/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -O3 -fno-strict-aliasing  -I/root/.choosenim/toolchains/nim-0.18.0/lib -o /mnt/d/Development/bitbucket/java/NetScoutMerger/script/lsrreport/nimcache/stdlib_smtp.o /mnt/d/Development/bitbucket/java/NetScoutMerger/script/lsrreport/nimcache/stdlib_smtp.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tyObject_PSSLContextcolonObjectType__2kCLMA7OHPpiY4mJ42cb7A tyObject_PSSLContextcolonObjectType__2kCLMA7OHPpiY4mJ42cb7A;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack_7fytPA5bBsob6See21YMRA tyObject_GcStack_7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyTuple_ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg;
typedef struct tyObject_SmtpBasecolonObjectType__VksVmFFn8e3v70S4inPcCw tyObject_SmtpBasecolonObjectType__VksVmFFn8e3v70S4inPcCw;
typedef struct tyObject_SocketImpl_aIhANOOoETolVz9cccNO9cRQ tyObject_SocketImpl_aIhANOOoETolVz9cccNO9cRQ;
typedef struct tyObject_SystemError_Fjf9b9b2IlzRO2tspHxG3tgg tyObject_SystemError_Fjf9b9b2IlzRO2tspHxG3tgg;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tySequence_uB9b75OUPRENsBAu4AnoePA tySequence_uB9b75OUPRENsBAu4AnoePA;
typedef struct tyObject_ReplyError_oMR49cgmw709ba6FEJzeKcRQ tyObject_ReplyError_oMR49cgmw709ba6FEJzeKcRQ;
typedef struct tyObject_IOError_9czoZw3pzPyrBmb5zTHY1OQ tyObject_IOError_9czoZw3pzPyrBmb5zTHY1OQ;
typedef struct tySequence_sM4lkSb7zS6F7OVMvW9cffQ tySequence_sM4lkSb7zS6F7OVMvW9cffQ;
typedef struct tyObject_Message_HL5IGwP2RHTpwc47L5s7MQ tyObject_Message_HL5IGwP2RHTpwc47L5s7MQ;
typedef struct tyObject_StringTableObj_DKRIdH9c9cKI7YpQb9c0wKlEw tyObject_StringTableObj_DKRIdH9c9cKI7YpQb9c0wKlEw;
typedef struct tyTuple_UV3llMMYFckfui8YMBuUZA tyTuple_UV3llMMYFckfui8YMBuUZA;
typedef struct tySequence_4eQHGndY6XBYpFOH09apV8Q tySequence_4eQHGndY6XBYpFOH09apV8Q;
typedef struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w;
typedef struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ;
typedef struct tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA;
struct tyObject_PSSLContextcolonObjectType__2kCLMA7OHPpiY4mJ42cb7A {
char dummy;
};
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef N_NIMCALL_PTR(void, tyProc_T4eqaYlFJYZUv9aG9b1TV0bQ) (void);
struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack_7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* tyArray_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef NU32 tyArray_BHbOSqU1t9b3Gt7K2c6fQig[24];
typedef tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* tyArray_N1u1nqOgmuJN9cSZrnMHgOQ[32];
typedef tyArray_N1u1nqOgmuJN9cSZrnMHgOQ tyArray_B6durA4ZCi1xjJvRtyYxMg[24];
typedef tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* tyArray_lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA {
tyArray_lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* tyArray_0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw {
tyArray_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyArray_LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray_LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray_SiRwrEKZdLgxqz9a9aoVBglg freeSmallChunks;
NU32 flBitmap;
tyArray_BHbOSqU1t9b3Gt7K2c6fQig slBitmap;
tyArray_B6durA4ZCi1xjJvRtyYxMg matrix;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI occ;
NI lastSize;
tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack_7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w additionalRoots;
NI gcThreadId;
};
struct tyObject_SmtpBasecolonObjectType__VksVmFFn8e3v70S4inPcCw {
tyObject_SocketImpl_aIhANOOoETolVz9cccNO9cRQ* sock;
NIM_BOOL debug;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef NU8 tyEnum_Domain_Q79bEtFARvq0ekDNtvj3Vqg;
typedef NU8 tyEnum_SockType_NQT1bItGG2X9byGdrWX7ujw;
typedef NU8 tyEnum_Protocol_dqJ1OqRGclxIMMdSLRzzXg;
struct RootObj {
TNimType* m_type;
};
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct Exception {
  RootObj Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
tySequence_uB9b75OUPRENsBAu4AnoePA* trace;
Exception* up;
};
struct tyObject_SystemError_Fjf9b9b2IlzRO2tspHxG3tgg {
  Exception Sup;
};
typedef NU8 tySet_tyEnum_SocketFlag_4xio0cAXR7XG4pF9bVcpxEg;
typedef NimStringDesc* tyArray_nHXaesL0DJZHyVS07ARPRA[1];
struct tyObject_IOError_9czoZw3pzPyrBmb5zTHY1OQ {
  tyObject_SystemError_Fjf9b9b2IlzRO2tspHxG3tgg Sup;
};
struct tyObject_ReplyError_oMR49cgmw709ba6FEJzeKcRQ {
  tyObject_IOError_9czoZw3pzPyrBmb5zTHY1OQ Sup;
};
struct tyObject_Message_HL5IGwP2RHTpwc47L5s7MQ {
tySequence_sM4lkSb7zS6F7OVMvW9cffQ* msgTo;
tySequence_sM4lkSb7zS6F7OVMvW9cffQ* msgCc;
NimStringDesc* msgSubject;
tyObject_StringTableObj_DKRIdH9c9cKI7YpQb9c0wKlEw* msgOtherHeaders;
NimStringDesc* msgBody;
};
typedef NU8 tyEnum_StringTableMode_G9c4wVDFIzf0xHmQvxso9a9cQ;
struct tyTuple_UV3llMMYFckfui8YMBuUZA {
NimStringDesc* Field0;
NimStringDesc* Field1;
};
typedef tyTuple_UV3llMMYFckfui8YMBuUZA tyArray_9cQD2Rag5wSTKjlY7q5DZNg[1];
struct tyObject_StringTableObj_DKRIdH9c9cKI7YpQb9c0wKlEw {
  RootObj Sup;
NI counter;
tySequence_4eQHGndY6XBYpFOH09apV8Q* data;
tyEnum_StringTableMode_G9c4wVDFIzf0xHmQvxso9a9cQ mode;
};
struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w {
NI prevSize;
NI size;
};
struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* next;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* prev;
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* freeList;
NI free;
NI acc;
NF data;
};
struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* next;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* prev;
NF data;
};
struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw {
NI size;
NI acc;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* next;
};
typedef NI tyArray_9a8QARi5WsUggNU9bom7kzTQ[8];
struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw {
tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg {
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
typedef NIM_CHAR tyArray_QQGLPNVVwLhYjkngqAxXQQ[4001];
struct tyObject_SocketImpl_aIhANOOoETolVz9cccNO9cRQ {
int fd;
NIM_BOOL isBuffered;
union{
struct {tyArray_QQGLPNVVwLhYjkngqAxXQQ buffer;
NI currPos;
NI bufLen;
} S1;
} isBufferedU;
NI32 lastError;
tyEnum_Domain_Q79bEtFARvq0ekDNtvj3Vqg domain;
tyEnum_SockType_NQT1bItGG2X9byGdrWX7ujw sockType;
tyEnum_Protocol_dqJ1OqRGclxIMMdSLRzzXg protocol;
};
struct tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA {
NCSTRING procname;
NI line;
NCSTRING filename;
};
struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ {
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* next;
NI zeroField;
};
struct tySequence_sM4lkSb7zS6F7OVMvW9cffQ {
  TGenericSeq Sup;
  NimStringDesc* data[SEQ_DECL_SIZE];
};
struct tySequence_uB9b75OUPRENsBAu4AnoePA {
  TGenericSeq Sup;
  tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA data[SEQ_DECL_SIZE];
};
struct tySequence_4eQHGndY6XBYpFOH09apV8Q {
  TGenericSeq Sup;
  tyTuple_UV3llMMYFckfui8YMBuUZA data[SEQ_DECL_SIZE];
};
static N_NIMCALL(void, Marker_tyRef_Gb7FwaDXt9ats5d0JrVzLZw)(void* p, NI op);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, TM_FfLduUxTL9cCY8Zn0IkWAAA_2)(void);
N_NIMCALL(void, nimRegisterGlobalMarker)(tyProc_T4eqaYlFJYZUv9aG9b1TV0bQ markerProc);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr);
static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NOINLINE(void, addZCT_fCDI7oO1NNVXXURtxSzsRw)(tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_NIMCALL(void, Marker_tyRef_MbjHqOlzajEe5L49cENen4w)(void* p, NI op);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_LIB_PRIVATE N_NIMCALL(tyObject_SocketImpl_aIhANOOoETolVz9cccNO9cRQ*, newSocket_8Lrat9ciQTaGiwISp8ak13A)(tyEnum_Domain_Q79bEtFARvq0ekDNtvj3Vqg domain, tyEnum_SockType_NQT1bItGG2X9byGdrWX7ujw sockType, tyEnum_Protocol_dqJ1OqRGclxIMMdSLRzzXg protocol, NIM_BOOL buffered);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_NIMCALL(void, raiseException)(Exception* e, NCSTRING ename);
N_LIB_PRIVATE N_NIMCALL(void, emptyNoop_q9cSFCJLo26XZQjXW3c2FvA)(void);
N_LIB_PRIVATE N_NIMCALL(void, connect_v3he1j4BPHctgBidfSUq7g)(tyObject_SocketImpl_aIhANOOoETolVz9cccNO9cRQ* socket, NimStringDesc* address, NU16 port);
N_LIB_PRIVATE N_NIMCALL(void, checkReply_GG9cLwEnfmKjc0B20rO3lEg)(tyObject_SmtpBasecolonObjectType__VksVmFFn8e3v70S4inPcCw* smtp, NimStringDesc* reply);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, emptyNoop_Wku8LwQ9b9c4GuOk9cJPXhKLg)(NimStringDesc* x);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, debugRecv_vAOWWaqZbH7JDGGdUr4TyA)(tyObject_SmtpBasecolonObjectType__VksVmFFn8e3v70S4inPcCw* smtp);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, recvLine_xZGQ2vK49cDdWvtLMB8phHQ)(tyObject_SocketImpl_aIhANOOoETolVz9cccNO9cRQ* socket, NI timeout, tySet_tyEnum_SocketFlag_4xio0cAXR7XG4pF9bVcpxEg flags, NI maxLength);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
N_NIMCALL(void, echoBinSafe)(NimStringDesc** args, NI argsLen_0);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, nsuStartsWith)(NimStringDesc* s, NimStringDesc* prefix);
N_LIB_PRIVATE N_NIMCALL(void, quitExcpt_T8CdFcwGACJfPRW7QIaKJw)(tyObject_SmtpBasecolonObjectType__VksVmFFn8e3v70S4inPcCw* smtp, NimStringDesc* msg);
N_LIB_PRIVATE N_NIMCALL(void, debugSend_iJOkIHGBZ9aQlVVfGsVsh9bQ)(tyObject_SmtpBasecolonObjectType__VksVmFFn8e3v70S4inPcCw* smtp, NimStringDesc* cmd);
N_LIB_PRIVATE N_NIMCALL(void, send_pLXZNcF79c032efCu7EgyDg)(tyObject_SocketImpl_aIhANOOoETolVz9cccNO9cRQ* socket, NimStringDesc* data, tySet_tyEnum_SocketFlag_4xio0cAXR7XG4pF9bVcpxEg flags);
static N_NIMCALL(void, Marker_tyRef_T7bEWfSYr4BG2eHzY5spJg)(void* p, NI op);
N_NIMCALL(void, genericReset)(void* dest, TNimType* mt);
N_NIMCALL(void, genericSeqAssign)(void* dest, void* src, TNimType* mt);
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_LIB_PRIVATE N_NIMCALL(tyObject_StringTableObj_DKRIdH9c9cKI7YpQb9c0wKlEw*, nstnewStringTableWithTableConstr)(tyTuple_UV3llMMYFckfui8YMBuUZA* keyValuePairs, NI keyValuePairsLen_0, tyEnum_StringTableMode_G9c4wVDFIzf0xHmQvxso9a9cQ mode);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, nsuJoinSep)(NimStringDesc** a, NI aLen_0, NimStringDesc* sep);
N_NIMCALL(NimStringDesc*, resizeString)(NimStringDesc* dest, NI addlen);
N_LIB_PRIVATE N_NIMCALL(void, close_VEqnJXVWVBs5DtNQcd59aJw)(tyObject_SocketImpl_aIhANOOoETolVz9cccNO9cRQ* socket);
tyObject_PSSLContextcolonObjectType__2kCLMA7OHPpiY4mJ42cb7A* defaultSSLContext_dzzxzfEmWpfrZMRfTcMRBQ;
TNimType NTI_2kCLMA7OHPpiY4mJ42cb7A_;
TNimType NTI_Gb7FwaDXt9ats5d0JrVzLZw_;
extern tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
TNimType NTI_VksVmFFn8e3v70S4inPcCw_;
extern TNimType NTI_MkGXUPMSENeRDS7EppfLgA_;
extern TNimType NTI_VaVACK0bpYmqIQ0mKcHfQQ_;
TNimType NTI_MbjHqOlzajEe5L49cENen4w_;
extern TNimType NTI_cbkAl3v6Wvi9amL0n9aBFy3w_;
extern TNimType NTI_Fjf9b9b2IlzRO2tspHxG3tgg_;
extern TNimType NTI_9czoZw3pzPyrBmb5zTHY1OQ_;
TNimType NTI_oMR49cgmw709ba6FEJzeKcRQ_;
TNimType NTI_T7bEWfSYr4BG2eHzY5spJg_;
TNimType NTI_HL5IGwP2RHTpwc47L5s7MQ_;
extern TNimType NTI_sM4lkSb7zS6F7OVMvW9cffQ_;
extern TNimType NTI_77mFvmsOLKik79ci2hXkHEg_;
extern TNimType NTI_pkhT5bYRU9ayIZ9cBuuCx4Xw_;
STRING_LITERAL(TM_FfLduUxTL9cCY8Zn0IkWAAA_4, "SMTP module compiled without SSL support", 40);
STRING_LITERAL(TM_FfLduUxTL9cCY8Zn0IkWAAA_5, "S:", 2);
STRING_LITERAL(TM_FfLduUxTL9cCY8Zn0IkWAAA_6, "C:", 2);
STRING_LITERAL(TM_FfLduUxTL9cCY8Zn0IkWAAA_7, "QUIT", 4);
STRING_LITERAL(TM_FfLduUxTL9cCY8Zn0IkWAAA_8, "Expected ", 9);
STRING_LITERAL(TM_FfLduUxTL9cCY8Zn0IkWAAA_9, " reply, got: ", 13);
STRING_LITERAL(TM_FfLduUxTL9cCY8Zn0IkWAAA_10, "220", 3);
STRING_LITERAL(TM_FfLduUxTL9cCY8Zn0IkWAAA_11, "HELO ", 5);
STRING_LITERAL(TM_FfLduUxTL9cCY8Zn0IkWAAA_12, "\015\012", 2);
STRING_LITERAL(TM_FfLduUxTL9cCY8Zn0IkWAAA_13, "250", 3);
STRING_LITERAL(TM_FfLduUxTL9cCY8Zn0IkWAAA_15, "MAIL FROM:<", 11);
STRING_LITERAL(TM_FfLduUxTL9cCY8Zn0IkWAAA_16, ">\015\012", 3);
STRING_LITERAL(TM_FfLduUxTL9cCY8Zn0IkWAAA_17, "RCPT TO:<", 9);
STRING_LITERAL(TM_FfLduUxTL9cCY8Zn0IkWAAA_18, "DATA \015\012", 7);
STRING_LITERAL(TM_FfLduUxTL9cCY8Zn0IkWAAA_19, "354", 3);
STRING_LITERAL(TM_FfLduUxTL9cCY8Zn0IkWAAA_20, ".\015\012", 3);
STRING_LITERAL(TM_FfLduUxTL9cCY8Zn0IkWAAA_21, "", 0);
STRING_LITERAL(TM_FfLduUxTL9cCY8Zn0IkWAAA_22, "TO: ", 4);
STRING_LITERAL(TM_FfLduUxTL9cCY8Zn0IkWAAA_23, ", ", 2);
STRING_LITERAL(TM_FfLduUxTL9cCY8Zn0IkWAAA_24, "CC: ", 4);
STRING_LITERAL(TM_FfLduUxTL9cCY8Zn0IkWAAA_25, "Subject: ", 9);
STRING_LITERAL(TM_FfLduUxTL9cCY8Zn0IkWAAA_26, ": ", 2);
STRING_LITERAL(TM_FfLduUxTL9cCY8Zn0IkWAAA_27, "QUIT\015\012", 6);
static N_NIMCALL(void, Marker_tyRef_Gb7FwaDXt9ats5d0JrVzLZw)(void* p, NI op) {
	tyObject_PSSLContextcolonObjectType__2kCLMA7OHPpiY4mJ42cb7A* a;
	a = (tyObject_PSSLContextcolonObjectType__2kCLMA7OHPpiY4mJ42cb7A*)p;
}
static N_NIMCALL(void, TM_FfLduUxTL9cCY8Zn0IkWAAA_2)(void) {
	nimGCvisit((void*)defaultSSLContext_dzzxzfEmWpfrZMRfTcMRBQ, 0);
}

static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* result;
	result = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	result = ((tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*) ((NI)((NU64)(((NI) (ptrdiff_t) (usr))) - (NU64)(((NI)sizeof(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g))))));
	return result;
}

static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	addZCT_fCDI7oO1NNVXXURtxSzsRw((&gch_IcYaEuuWivYAS86vFMTS3Q.zct), c);
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
		if (!!((src == NIM_NIL))) goto LA3_;
		c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		(*c).refcount += ((NI) 8);
	}
	LA3_: ;
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c_2;
		if (!!(((*dest) == NIM_NIL))) goto LA7_;
		c_2 = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		{
			(*c_2).refcount -= ((NI) 8);
			if (!((NU64)((*c_2).refcount) < (NU64)(((NI) 8)))) goto LA11_;
			rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c_2);
		}
		LA11_: ;
	}
	LA7_: ;
	(*dest) = src;
}
static N_NIMCALL(void, Marker_tyRef_MbjHqOlzajEe5L49cENen4w)(void* p, NI op) {
	tyObject_SmtpBasecolonObjectType__VksVmFFn8e3v70S4inPcCw* a;
	a = (tyObject_SmtpBasecolonObjectType__VksVmFFn8e3v70S4inPcCw*)p;
	nimGCvisit((void*)(*a).sock, op);
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
	c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(p);
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
}

static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	(*c).refcount = (NI)((NU64)((*c).refcount) + (NU64)(((NI) 8)));
}

static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
}

static N_INLINE(void, asgnRef)(void** dest, void* src) {
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T5_;
		if (!!((src == NIM_NIL))) goto LA3_;
		T5_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T5_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		incRef_9cAA5YuQAAC3MVbnGeV86swsystem(T5_);
	}
	LA3_: ;
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T10_;
		if (!!(((*dest) == NIM_NIL))) goto LA8_;
		T10_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T10_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		decRef_MV4BBk6J1qu70IbBxwEn4wsystem(T10_);
	}
	LA8_: ;
	(*dest) = src;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_SmtpBasecolonObjectType__VksVmFFn8e3v70S4inPcCw*, newSmtp_Nfj9aqPFVmOAIhqu0AdSnwQ)(NIM_BOOL useSsl, NIM_BOOL debug, tyObject_PSSLContextcolonObjectType__2kCLMA7OHPpiY4mJ42cb7A* sslContext) {
	tyObject_SmtpBasecolonObjectType__VksVmFFn8e3v70S4inPcCw* result;
	result = (tyObject_SmtpBasecolonObjectType__VksVmFFn8e3v70S4inPcCw*)0;
	result = (tyObject_SmtpBasecolonObjectType__VksVmFFn8e3v70S4inPcCw*) newObj((&NTI_MbjHqOlzajEe5L49cENen4w_), sizeof(tyObject_SmtpBasecolonObjectType__VksVmFFn8e3v70S4inPcCw));
	(*result).debug = debug;
	asgnRefNoCycle((void**) (&(*result).sock), newSocket_8Lrat9ciQTaGiwISp8ak13A(((tyEnum_Domain_Q79bEtFARvq0ekDNtvj3Vqg) 2), ((tyEnum_SockType_NQT1bItGG2X9byGdrWX7ujw) 1), ((tyEnum_Protocol_dqJ1OqRGclxIMMdSLRzzXg) 6), NIM_TRUE));
	{
		tyObject_SystemError_Fjf9b9b2IlzRO2tspHxG3tgg* e;
		NimStringDesc* T5_;
		if (!useSsl) goto LA3_;
		e = (tyObject_SystemError_Fjf9b9b2IlzRO2tspHxG3tgg*)0;
		e = (tyObject_SystemError_Fjf9b9b2IlzRO2tspHxG3tgg*) newObj((&NTI_cbkAl3v6Wvi9amL0n9aBFy3w_), sizeof(tyObject_SystemError_Fjf9b9b2IlzRO2tspHxG3tgg));
		(*e).Sup.Sup.m_type = (&NTI_Fjf9b9b2IlzRO2tspHxG3tgg_);
		T5_ = (NimStringDesc*)0;
		T5_ = (*e).Sup.message; (*e).Sup.message = copyStringRC1(((NimStringDesc*) &TM_FfLduUxTL9cCY8Zn0IkWAAA_4));
		if (T5_) nimGCunrefNoCycle(T5_);
		asgnRef((void**) (&(*e).Sup.parent), NIM_NIL);
		raiseException((Exception*)e, "SystemError");
	}
	LA3_: ;
	return result;
}

static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	copyMem_E1xtACub5WcDa3vbrIXbwgsystem(((void*) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((void*) ((*src).data)), ((NI) ((NI)((*src).Sup.len + ((NI) 1)))));
	(*dest).Sup.len += (*src).Sup.len;
}

N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, debugRecv_vAOWWaqZbH7JDGGdUr4TyA)(tyObject_SmtpBasecolonObjectType__VksVmFFn8e3v70S4inPcCw* smtp) {
	NimStringDesc* result;
	NimStringDesc* T1_;
	result = (NimStringDesc*)0;
	T1_ = (NimStringDesc*)0;
	T1_ = recvLine_xZGQ2vK49cDdWvtLMB8phHQ((*smtp).sock, ((NI) -1), 2, ((NI) 1000000));
	result = emptyNoop_Wku8LwQ9b9c4GuOk9cJPXhKLg(T1_);
	{
		tyArray_nHXaesL0DJZHyVS07ARPRA T6_;
		NimStringDesc* T7_;
		if (!(*smtp).debug) goto LA4_;
		memset((void*)T6_, 0, sizeof(T6_));
		T7_ = (NimStringDesc*)0;
		T7_ = rawNewString(result->Sup.len + 2);
appendString(T7_, ((NimStringDesc*) &TM_FfLduUxTL9cCY8Zn0IkWAAA_5));
appendString(T7_, result);
		T6_[0] = T7_;
		echoBinSafe(T6_, 1);
	}
	LA4_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, debugSend_iJOkIHGBZ9aQlVVfGsVsh9bQ)(tyObject_SmtpBasecolonObjectType__VksVmFFn8e3v70S4inPcCw* smtp, NimStringDesc* cmd) {
	{
		tyArray_nHXaesL0DJZHyVS07ARPRA T5_;
		NimStringDesc* T6_;
		if (!(*smtp).debug) goto LA3_;
		memset((void*)T5_, 0, sizeof(T5_));
		T6_ = (NimStringDesc*)0;
		T6_ = rawNewString(cmd->Sup.len + 2);
appendString(T6_, ((NimStringDesc*) &TM_FfLduUxTL9cCY8Zn0IkWAAA_6));
appendString(T6_, cmd);
		T5_[0] = T6_;
		echoBinSafe(T5_, 1);
	}
	LA3_: ;
	send_pLXZNcF79c032efCu7EgyDg((*smtp).sock, cmd, 2);
	emptyNoop_q9cSFCJLo26XZQjXW3c2FvA();
}
static N_NIMCALL(void, Marker_tyRef_T7bEWfSYr4BG2eHzY5spJg)(void* p, NI op) {
	tyObject_ReplyError_oMR49cgmw709ba6FEJzeKcRQ* a;
	a = (tyObject_ReplyError_oMR49cgmw709ba6FEJzeKcRQ*)p;
	nimGCvisit((void*)(*a).Sup.Sup.Sup.parent, op);
	nimGCvisit((void*)(*a).Sup.Sup.Sup.message, op);
	nimGCvisit((void*)(*a).Sup.Sup.Sup.trace, op);
	nimGCvisit((void*)(*a).Sup.Sup.Sup.up, op);
}

N_LIB_PRIVATE N_NIMCALL(void, quitExcpt_T8CdFcwGACJfPRW7QIaKJw)(tyObject_SmtpBasecolonObjectType__VksVmFFn8e3v70S4inPcCw* smtp, NimStringDesc* msg) {
	tyObject_ReplyError_oMR49cgmw709ba6FEJzeKcRQ* e;
	NimStringDesc* T1_;
	debugSend_iJOkIHGBZ9aQlVVfGsVsh9bQ(smtp, ((NimStringDesc*) &TM_FfLduUxTL9cCY8Zn0IkWAAA_7));
	e = (tyObject_ReplyError_oMR49cgmw709ba6FEJzeKcRQ*)0;
	e = (tyObject_ReplyError_oMR49cgmw709ba6FEJzeKcRQ*) newObj((&NTI_T7bEWfSYr4BG2eHzY5spJg_), sizeof(tyObject_ReplyError_oMR49cgmw709ba6FEJzeKcRQ));
	(*e).Sup.Sup.Sup.Sup.m_type = (&NTI_oMR49cgmw709ba6FEJzeKcRQ_);
	T1_ = (NimStringDesc*)0;
	T1_ = (*e).Sup.Sup.Sup.message; (*e).Sup.Sup.Sup.message = copyStringRC1(msg);
	if (T1_) nimGCunrefNoCycle(T1_);
	asgnRef((void**) (&(*e).Sup.Sup.Sup.parent), NIM_NIL);
	raiseException((Exception*)e, "ReplyError");
}

N_LIB_PRIVATE N_NIMCALL(void, checkReply_GG9cLwEnfmKjc0B20rO3lEg)(tyObject_SmtpBasecolonObjectType__VksVmFFn8e3v70S4inPcCw* smtp, NimStringDesc* reply) {
	NimStringDesc* line;
	NimStringDesc* T1_;
	T1_ = (NimStringDesc*)0;
	T1_ = debugRecv_vAOWWaqZbH7JDGGdUr4TyA(smtp);
	line = emptyNoop_Wku8LwQ9b9c4GuOk9cJPXhKLg(T1_);
	{
		NIM_BOOL T4_;
		NimStringDesc* T7_;
		T4_ = (NIM_BOOL)0;
		T4_ = nsuStartsWith(line, reply);
		if (!!(T4_)) goto LA5_;
		T7_ = (NimStringDesc*)0;
		T7_ = rawNewString(reply->Sup.len + line->Sup.len + 22);
appendString(T7_, ((NimStringDesc*) &TM_FfLduUxTL9cCY8Zn0IkWAAA_8));
appendString(T7_, reply);
appendString(T7_, ((NimStringDesc*) &TM_FfLduUxTL9cCY8Zn0IkWAAA_9));
appendString(T7_, line);
		quitExcpt_T8CdFcwGACJfPRW7QIaKJw(smtp, T7_);
		emptyNoop_q9cSFCJLo26XZQjXW3c2FvA();
	}
	LA5_: ;
}

N_LIB_PRIVATE N_NIMCALL(void, connect_C7JzaUeEk1v89aIrEUFE6Kw)(tyObject_SmtpBasecolonObjectType__VksVmFFn8e3v70S4inPcCw* smtp, NimStringDesc* address, NU16 port) {
	NimStringDesc* T1_;
	connect_v3he1j4BPHctgBidfSUq7g((*smtp).sock, address, port);
	emptyNoop_q9cSFCJLo26XZQjXW3c2FvA();
	checkReply_GG9cLwEnfmKjc0B20rO3lEg(smtp, ((NimStringDesc*) &TM_FfLduUxTL9cCY8Zn0IkWAAA_10));
	emptyNoop_q9cSFCJLo26XZQjXW3c2FvA();
	T1_ = (NimStringDesc*)0;
	T1_ = rawNewString(address->Sup.len + 7);
appendString(T1_, ((NimStringDesc*) &TM_FfLduUxTL9cCY8Zn0IkWAAA_11));
appendString(T1_, address);
appendString(T1_, ((NimStringDesc*) &TM_FfLduUxTL9cCY8Zn0IkWAAA_12));
	debugSend_iJOkIHGBZ9aQlVVfGsVsh9bQ(smtp, T1_);
	emptyNoop_q9cSFCJLo26XZQjXW3c2FvA();
	checkReply_GG9cLwEnfmKjc0B20rO3lEg(smtp, ((NimStringDesc*) &TM_FfLduUxTL9cCY8Zn0IkWAAA_13));
	emptyNoop_q9cSFCJLo26XZQjXW3c2FvA();
}

N_LIB_PRIVATE N_NIMCALL(void, createMessage_VTgoPMl3ny6cuyc4q9c3iFg)(NimStringDesc* mSubject, NimStringDesc* mBody, tySequence_sM4lkSb7zS6F7OVMvW9cffQ* mTo, tySequence_sM4lkSb7zS6F7OVMvW9cffQ* mCc, tyObject_Message_HL5IGwP2RHTpwc47L5s7MQ* Result) {
	tyArray_9cQD2Rag5wSTKjlY7q5DZNg T1_;
	genericReset((void*)Result, (&NTI_HL5IGwP2RHTpwc47L5s7MQ_));
	genericSeqAssign((&(*Result).msgTo), mTo, (&NTI_sM4lkSb7zS6F7OVMvW9cffQ_));
	genericSeqAssign((&(*Result).msgCc), mCc, (&NTI_sM4lkSb7zS6F7OVMvW9cffQ_));
	unsureAsgnRef((void**) (&(*Result).msgSubject), copyString(mSubject));
	unsureAsgnRef((void**) (&(*Result).msgBody), copyString(mBody));
	memset((void*)T1_, 0, sizeof(T1_));
	unsureAsgnRef((void**) (&(*Result).msgOtherHeaders), nstnewStringTableWithTableConstr(T1_, 0, ((tyEnum_StringTableMode_G9c4wVDFIzf0xHmQvxso9a9cQ) 0)));
}

N_LIB_PRIVATE N_NIMCALL(void, sendMail_quVl9cZasl6ARt2XgBDMBeg)(tyObject_SmtpBasecolonObjectType__VksVmFFn8e3v70S4inPcCw* smtp, NimStringDesc* fromAddr, tySequence_sM4lkSb7zS6F7OVMvW9cffQ* toAddrs, NimStringDesc* msg) {
	NimStringDesc* T1_;
	NimStringDesc* T7_;
	T1_ = (NimStringDesc*)0;
	T1_ = rawNewString(fromAddr->Sup.len + 14);
appendString(T1_, ((NimStringDesc*) &TM_FfLduUxTL9cCY8Zn0IkWAAA_15));
appendString(T1_, fromAddr);
appendString(T1_, ((NimStringDesc*) &TM_FfLduUxTL9cCY8Zn0IkWAAA_16));
	debugSend_iJOkIHGBZ9aQlVVfGsVsh9bQ(smtp, T1_);
	emptyNoop_q9cSFCJLo26XZQjXW3c2FvA();
	checkReply_GG9cLwEnfmKjc0B20rO3lEg(smtp, ((NimStringDesc*) &TM_FfLduUxTL9cCY8Zn0IkWAAA_13));
	emptyNoop_q9cSFCJLo26XZQjXW3c2FvA();
	{
		NimStringDesc* address;
		NI i;
		NI L;
		NI T3_;
		address = (NimStringDesc*)0;
		i = ((NI) 0);
		T3_ = (toAddrs ? toAddrs->Sup.len : 0);
		L = T3_;
		{
			while (1) {
				NimStringDesc* T6_;
				if (!(i < L)) goto LA5;
				address = toAddrs->data[i];
				T6_ = (NimStringDesc*)0;
				T6_ = rawNewString(address->Sup.len + 12);
appendString(T6_, ((NimStringDesc*) &TM_FfLduUxTL9cCY8Zn0IkWAAA_17));
appendString(T6_, address);
appendString(T6_, ((NimStringDesc*) &TM_FfLduUxTL9cCY8Zn0IkWAAA_16));
				debugSend_iJOkIHGBZ9aQlVVfGsVsh9bQ(smtp, T6_);
				emptyNoop_q9cSFCJLo26XZQjXW3c2FvA();
				checkReply_GG9cLwEnfmKjc0B20rO3lEg(smtp, ((NimStringDesc*) &TM_FfLduUxTL9cCY8Zn0IkWAAA_13));
				emptyNoop_q9cSFCJLo26XZQjXW3c2FvA();
				i += ((NI) 1);
			} LA5: ;
		}
	}
	debugSend_iJOkIHGBZ9aQlVVfGsVsh9bQ(smtp, ((NimStringDesc*) &TM_FfLduUxTL9cCY8Zn0IkWAAA_18));
	emptyNoop_q9cSFCJLo26XZQjXW3c2FvA();
	checkReply_GG9cLwEnfmKjc0B20rO3lEg(smtp, ((NimStringDesc*) &TM_FfLduUxTL9cCY8Zn0IkWAAA_19));
	emptyNoop_q9cSFCJLo26XZQjXW3c2FvA();
	T7_ = (NimStringDesc*)0;
	T7_ = rawNewString(msg->Sup.len + 2);
appendString(T7_, msg);
appendString(T7_, ((NimStringDesc*) &TM_FfLduUxTL9cCY8Zn0IkWAAA_12));
	send_pLXZNcF79c032efCu7EgyDg((*smtp).sock, T7_, 2);
	emptyNoop_q9cSFCJLo26XZQjXW3c2FvA();
	debugSend_iJOkIHGBZ9aQlVVfGsVsh9bQ(smtp, ((NimStringDesc*) &TM_FfLduUxTL9cCY8Zn0IkWAAA_20));
	emptyNoop_q9cSFCJLo26XZQjXW3c2FvA();
	checkReply_GG9cLwEnfmKjc0B20rO3lEg(smtp, ((NimStringDesc*) &TM_FfLduUxTL9cCY8Zn0IkWAAA_13));
	emptyNoop_q9cSFCJLo26XZQjXW3c2FvA();
}

N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar__QWOX43qXQs7iDJ7vgNvGzQ)(tyObject_Message_HL5IGwP2RHTpwc47L5s7MQ* msg) {
	NimStringDesc* result;
	NimStringDesc* T15_;
	result = (NimStringDesc*)0;
	result = copyString(((NimStringDesc*) &TM_FfLduUxTL9cCY8Zn0IkWAAA_21));
	{
		NI T3_;
		NimStringDesc* T6_;
		NimStringDesc* T7_;
		T3_ = ((*msg).msgTo ? (*msg).msgTo->Sup.len : 0);
		if (!(((NI) 0) < T3_)) goto LA4_;
		T6_ = (NimStringDesc*)0;
		T7_ = (NimStringDesc*)0;
		T7_ = nsuJoinSep((*msg).msgTo->data, (*msg).msgTo->Sup.len, ((NimStringDesc*) &TM_FfLduUxTL9cCY8Zn0IkWAAA_23));
		T6_ = rawNewString(T7_->Sup.len + 6);
appendString(T6_, ((NimStringDesc*) &TM_FfLduUxTL9cCY8Zn0IkWAAA_22));
appendString(T6_, T7_);
appendString(T6_, ((NimStringDesc*) &TM_FfLduUxTL9cCY8Zn0IkWAAA_12));
		result = T6_;
	}
	LA4_: ;
	{
		NI T10_;
		NimStringDesc* T13_;
		NimStringDesc* T14_;
		T10_ = ((*msg).msgCc ? (*msg).msgCc->Sup.len : 0);
		if (!(((NI) 0) < T10_)) goto LA11_;
		T13_ = (NimStringDesc*)0;
		T14_ = (NimStringDesc*)0;
		T14_ = nsuJoinSep((*msg).msgCc->data, (*msg).msgCc->Sup.len, ((NimStringDesc*) &TM_FfLduUxTL9cCY8Zn0IkWAAA_23));
		T13_ = rawNewString(T14_->Sup.len + 6);
appendString(T13_, ((NimStringDesc*) &TM_FfLduUxTL9cCY8Zn0IkWAAA_24));
appendString(T13_, T14_);
appendString(T13_, ((NimStringDesc*) &TM_FfLduUxTL9cCY8Zn0IkWAAA_12));
		result = resizeString(result, T13_->Sup.len + 0);
appendString(result, T13_);
	}
	LA11_: ;
	T15_ = (NimStringDesc*)0;
	T15_ = rawNewString((*msg).msgSubject->Sup.len + 11);
appendString(T15_, ((NimStringDesc*) &TM_FfLduUxTL9cCY8Zn0IkWAAA_25));
appendString(T15_, (*msg).msgSubject);
appendString(T15_, ((NimStringDesc*) &TM_FfLduUxTL9cCY8Zn0IkWAAA_12));
	result = resizeString(result, T15_->Sup.len + 0);
appendString(result, T15_);
	{
		NimStringDesc* key;
		NimStringDesc* value;
		tyObject_StringTableObj_DKRIdH9c9cKI7YpQb9c0wKlEw* colontmp_;
		key = (NimStringDesc*)0;
		value = (NimStringDesc*)0;
		colontmp_ = (tyObject_StringTableObj_DKRIdH9c9cKI7YpQb9c0wKlEw*)0;
		colontmp_ = (*msg).msgOtherHeaders;
		{
			NI h;
			NI colontmp__2;
			NI T18_;
			NI res;
			h = (NI)0;
			colontmp__2 = (NI)0;
			T18_ = ((*colontmp_).data ? ((*colontmp_).data->Sup.len-1) : -1);
			colontmp__2 = T18_;
			res = ((NI) 0);
			{
				while (1) {
					if (!(res <= colontmp__2)) goto LA20;
					h = res;
					{
						NimStringDesc* T25_;
						if (!!(((*colontmp_).data->data[h].Field0 == 0))) goto LA23_;
						key = (*colontmp_).data->data[h].Field0;
						value = (*colontmp_).data->data[h].Field1;
						T25_ = (NimStringDesc*)0;
						T25_ = rawNewString(key->Sup.len + value->Sup.len + 4);
appendString(T25_, key);
appendString(T25_, ((NimStringDesc*) &TM_FfLduUxTL9cCY8Zn0IkWAAA_26));
appendString(T25_, value);
appendString(T25_, ((NimStringDesc*) &TM_FfLduUxTL9cCY8Zn0IkWAAA_12));
						result = resizeString(result, T25_->Sup.len + 0);
appendString(result, T25_);
					}
					LA23_: ;
					res += ((NI) 1);
				} LA20: ;
			}
		}
	}
	result = resizeString(result, 2);
appendString(result, ((NimStringDesc*) &TM_FfLduUxTL9cCY8Zn0IkWAAA_12));
	result = resizeString(result, (*msg).msgBody->Sup.len + 0);
appendString(result, (*msg).msgBody);
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, close_uZ9cBaasaypmmMJ58nGYPOw)(tyObject_SmtpBasecolonObjectType__VksVmFFn8e3v70S4inPcCw* smtp) {
	debugSend_iJOkIHGBZ9aQlVVfGsVsh9bQ(smtp, ((NimStringDesc*) &TM_FfLduUxTL9cCY8Zn0IkWAAA_27));
	emptyNoop_q9cSFCJLo26XZQjXW3c2FvA();
	close_VEqnJXVWVBs5DtNQcd59aJw((*smtp).sock);
}
NIM_EXTERNC N_NOINLINE(void, stdlib_smtpInit000)(void) {
nimRegisterGlobalMarker(TM_FfLduUxTL9cCY8Zn0IkWAAA_2);
	asgnRefNoCycle((void**) (&defaultSSLContext_dzzxzfEmWpfrZMRfTcMRBQ), NIM_NIL);
}

NIM_EXTERNC N_NOINLINE(void, stdlib_smtpDatInit000)(void) {
static TNimNode* TM_FfLduUxTL9cCY8Zn0IkWAAA_3[2];
static TNimNode* TM_FfLduUxTL9cCY8Zn0IkWAAA_14[5];
static TNimNode TM_FfLduUxTL9cCY8Zn0IkWAAA_0[11];
NTI_2kCLMA7OHPpiY4mJ42cb7A_.size = sizeof(tyObject_PSSLContextcolonObjectType__2kCLMA7OHPpiY4mJ42cb7A);
NTI_2kCLMA7OHPpiY4mJ42cb7A_.kind = 18;
NTI_2kCLMA7OHPpiY4mJ42cb7A_.base = 0;
NTI_2kCLMA7OHPpiY4mJ42cb7A_.flags = 3;
TM_FfLduUxTL9cCY8Zn0IkWAAA_0[0].len = 0; TM_FfLduUxTL9cCY8Zn0IkWAAA_0[0].kind = 2;
NTI_2kCLMA7OHPpiY4mJ42cb7A_.node = &TM_FfLduUxTL9cCY8Zn0IkWAAA_0[0];
NTI_Gb7FwaDXt9ats5d0JrVzLZw_.size = sizeof(tyObject_PSSLContextcolonObjectType__2kCLMA7OHPpiY4mJ42cb7A*);
NTI_Gb7FwaDXt9ats5d0JrVzLZw_.kind = 22;
NTI_Gb7FwaDXt9ats5d0JrVzLZw_.base = (&NTI_2kCLMA7OHPpiY4mJ42cb7A_);
NTI_Gb7FwaDXt9ats5d0JrVzLZw_.flags = 2;
NTI_Gb7FwaDXt9ats5d0JrVzLZw_.marker = Marker_tyRef_Gb7FwaDXt9ats5d0JrVzLZw;
NTI_VksVmFFn8e3v70S4inPcCw_.size = sizeof(tyObject_SmtpBasecolonObjectType__VksVmFFn8e3v70S4inPcCw);
NTI_VksVmFFn8e3v70S4inPcCw_.kind = 18;
NTI_VksVmFFn8e3v70S4inPcCw_.base = 0;
NTI_VksVmFFn8e3v70S4inPcCw_.flags = 2;
TM_FfLduUxTL9cCY8Zn0IkWAAA_3[0] = &TM_FfLduUxTL9cCY8Zn0IkWAAA_0[2];
TM_FfLduUxTL9cCY8Zn0IkWAAA_0[2].kind = 1;
TM_FfLduUxTL9cCY8Zn0IkWAAA_0[2].offset = offsetof(tyObject_SmtpBasecolonObjectType__VksVmFFn8e3v70S4inPcCw, sock);
TM_FfLduUxTL9cCY8Zn0IkWAAA_0[2].typ = (&NTI_MkGXUPMSENeRDS7EppfLgA_);
TM_FfLduUxTL9cCY8Zn0IkWAAA_0[2].name = "sock";
TM_FfLduUxTL9cCY8Zn0IkWAAA_3[1] = &TM_FfLduUxTL9cCY8Zn0IkWAAA_0[3];
TM_FfLduUxTL9cCY8Zn0IkWAAA_0[3].kind = 1;
TM_FfLduUxTL9cCY8Zn0IkWAAA_0[3].offset = offsetof(tyObject_SmtpBasecolonObjectType__VksVmFFn8e3v70S4inPcCw, debug);
TM_FfLduUxTL9cCY8Zn0IkWAAA_0[3].typ = (&NTI_VaVACK0bpYmqIQ0mKcHfQQ_);
TM_FfLduUxTL9cCY8Zn0IkWAAA_0[3].name = "debug";
TM_FfLduUxTL9cCY8Zn0IkWAAA_0[1].len = 2; TM_FfLduUxTL9cCY8Zn0IkWAAA_0[1].kind = 2; TM_FfLduUxTL9cCY8Zn0IkWAAA_0[1].sons = &TM_FfLduUxTL9cCY8Zn0IkWAAA_3[0];
NTI_VksVmFFn8e3v70S4inPcCw_.node = &TM_FfLduUxTL9cCY8Zn0IkWAAA_0[1];
NTI_MbjHqOlzajEe5L49cENen4w_.size = sizeof(tyObject_SmtpBasecolonObjectType__VksVmFFn8e3v70S4inPcCw*);
NTI_MbjHqOlzajEe5L49cENen4w_.kind = 22;
NTI_MbjHqOlzajEe5L49cENen4w_.base = (&NTI_VksVmFFn8e3v70S4inPcCw_);
NTI_MbjHqOlzajEe5L49cENen4w_.flags = 2;
NTI_MbjHqOlzajEe5L49cENen4w_.marker = Marker_tyRef_MbjHqOlzajEe5L49cENen4w;
NTI_oMR49cgmw709ba6FEJzeKcRQ_.size = sizeof(tyObject_ReplyError_oMR49cgmw709ba6FEJzeKcRQ);
NTI_oMR49cgmw709ba6FEJzeKcRQ_.kind = 17;
NTI_oMR49cgmw709ba6FEJzeKcRQ_.base = (&NTI_9czoZw3pzPyrBmb5zTHY1OQ_);
TM_FfLduUxTL9cCY8Zn0IkWAAA_0[4].len = 0; TM_FfLduUxTL9cCY8Zn0IkWAAA_0[4].kind = 2;
NTI_oMR49cgmw709ba6FEJzeKcRQ_.node = &TM_FfLduUxTL9cCY8Zn0IkWAAA_0[4];
NTI_T7bEWfSYr4BG2eHzY5spJg_.size = sizeof(tyObject_ReplyError_oMR49cgmw709ba6FEJzeKcRQ*);
NTI_T7bEWfSYr4BG2eHzY5spJg_.kind = 22;
NTI_T7bEWfSYr4BG2eHzY5spJg_.base = (&NTI_oMR49cgmw709ba6FEJzeKcRQ_);
NTI_T7bEWfSYr4BG2eHzY5spJg_.marker = Marker_tyRef_T7bEWfSYr4BG2eHzY5spJg;
NTI_HL5IGwP2RHTpwc47L5s7MQ_.size = sizeof(tyObject_Message_HL5IGwP2RHTpwc47L5s7MQ);
NTI_HL5IGwP2RHTpwc47L5s7MQ_.kind = 18;
NTI_HL5IGwP2RHTpwc47L5s7MQ_.base = 0;
TM_FfLduUxTL9cCY8Zn0IkWAAA_14[0] = &TM_FfLduUxTL9cCY8Zn0IkWAAA_0[6];
TM_FfLduUxTL9cCY8Zn0IkWAAA_0[6].kind = 1;
TM_FfLduUxTL9cCY8Zn0IkWAAA_0[6].offset = offsetof(tyObject_Message_HL5IGwP2RHTpwc47L5s7MQ, msgTo);
TM_FfLduUxTL9cCY8Zn0IkWAAA_0[6].typ = (&NTI_sM4lkSb7zS6F7OVMvW9cffQ_);
TM_FfLduUxTL9cCY8Zn0IkWAAA_0[6].name = "msgTo";
TM_FfLduUxTL9cCY8Zn0IkWAAA_14[1] = &TM_FfLduUxTL9cCY8Zn0IkWAAA_0[7];
TM_FfLduUxTL9cCY8Zn0IkWAAA_0[7].kind = 1;
TM_FfLduUxTL9cCY8Zn0IkWAAA_0[7].offset = offsetof(tyObject_Message_HL5IGwP2RHTpwc47L5s7MQ, msgCc);
TM_FfLduUxTL9cCY8Zn0IkWAAA_0[7].typ = (&NTI_sM4lkSb7zS6F7OVMvW9cffQ_);
TM_FfLduUxTL9cCY8Zn0IkWAAA_0[7].name = "msgCc";
TM_FfLduUxTL9cCY8Zn0IkWAAA_14[2] = &TM_FfLduUxTL9cCY8Zn0IkWAAA_0[8];
TM_FfLduUxTL9cCY8Zn0IkWAAA_0[8].kind = 1;
TM_FfLduUxTL9cCY8Zn0IkWAAA_0[8].offset = offsetof(tyObject_Message_HL5IGwP2RHTpwc47L5s7MQ, msgSubject);
TM_FfLduUxTL9cCY8Zn0IkWAAA_0[8].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_FfLduUxTL9cCY8Zn0IkWAAA_0[8].name = "msgSubject";
TM_FfLduUxTL9cCY8Zn0IkWAAA_14[3] = &TM_FfLduUxTL9cCY8Zn0IkWAAA_0[9];
TM_FfLduUxTL9cCY8Zn0IkWAAA_0[9].kind = 1;
TM_FfLduUxTL9cCY8Zn0IkWAAA_0[9].offset = offsetof(tyObject_Message_HL5IGwP2RHTpwc47L5s7MQ, msgOtherHeaders);
TM_FfLduUxTL9cCY8Zn0IkWAAA_0[9].typ = (&NTI_pkhT5bYRU9ayIZ9cBuuCx4Xw_);
TM_FfLduUxTL9cCY8Zn0IkWAAA_0[9].name = "msgOtherHeaders";
TM_FfLduUxTL9cCY8Zn0IkWAAA_14[4] = &TM_FfLduUxTL9cCY8Zn0IkWAAA_0[10];
TM_FfLduUxTL9cCY8Zn0IkWAAA_0[10].kind = 1;
TM_FfLduUxTL9cCY8Zn0IkWAAA_0[10].offset = offsetof(tyObject_Message_HL5IGwP2RHTpwc47L5s7MQ, msgBody);
TM_FfLduUxTL9cCY8Zn0IkWAAA_0[10].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_FfLduUxTL9cCY8Zn0IkWAAA_0[10].name = "msgBody";
TM_FfLduUxTL9cCY8Zn0IkWAAA_0[5].len = 5; TM_FfLduUxTL9cCY8Zn0IkWAAA_0[5].kind = 2; TM_FfLduUxTL9cCY8Zn0IkWAAA_0[5].sons = &TM_FfLduUxTL9cCY8Zn0IkWAAA_14[0];
NTI_HL5IGwP2RHTpwc47L5s7MQ_.node = &TM_FfLduUxTL9cCY8Zn0IkWAAA_0[5];
}

